In [1]:
%reset -f

In [2]:
debug = False

In [3]:
 %reload_ext autoreload
%autoreload 2

import sys
sys.path.append("/home/zhuchen/poc/scorecard") 
FILE_PATH = '/home/zhuchen/poc/01-mashang/DeltaV1/file/'
DATA_PATH = '/home/zhuchen/poc/01-mashang/DeltaV1/data/'
TMP_PATH  = '/home/zhuchen/poc/01-mashang/DeltaV1/tmp/'
DATA_OR_PATH = '/home/zhuchen/poc/01-mashang/data_or/'

import os
import gc
import pandas as pd 
import numpy as np  
import math  
import zipfile
import matplotlib.pyplot as plt
import copy
import seaborn as sns
from pylab import mpl
from ScoreCard.creat_report import Report
mpl.rcParams['font.sans-serif'] = ['SimHei']
mpl.rcParams['axes.unicode_minus'] = False  

isExists=os.path.exists(FILE_PATH)
if not isExists:
    os.makedirs(FILE_PATH) 
    
isExists=os.path.exists(DATA_PATH)
if not isExists:
    os.makedirs(DATA_PATH)

isExists=os.path.exists(TMP_PATH)
if not isExists:
    os.makedirs(TMP_PATH)  

import warnings
warnings.filterwarnings("ignore")

## 1. 数据预处理

In [4]:
with zipfile.ZipFile(DATA_OR_PATH + '驭鉴20250707_LH_deltaV1_result.txt.zip', 'r') as zip_file:
    file_list = zip_file.namelist()
    print("压缩包内文件:", file_list)
    csv_filename = [f for f in file_list if f.endswith('.txt') or f.endswith('.csv')][0]
    with zip_file.open(csv_filename) as csv_file:
        data_tmp = pd.read_csv(csv_file, nrows=100)

压缩包内文件: ['Θ⌐¡Θë┤20250707_LH_deltaV1_result.txt']

In [5]:
data_tmp

,name,mobile,idCard,reqToken,backPointTime,TZ_0000_m1,TZ_0000_m12,TZ_0000_m15,TZ_0000_m18,TZ_0000_m2,...,TZ_2024_T4_m4,TZ_2024_T4_m5,TZ_2024_T4_m6,TZ_2024_T4_m7,TZ_2024_T4_m8,TZ_2024_T4_m9,TZ_2025_T1_m24,TZ_2025_T2_m24,TZ_2025_T3_m24,TZ_2025_T4_m24
0,test,d45735e2015b20c4e8f95645096ae0dac3c9924b9e6b35...,test,2618468494244577696,2024/11/21,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,test,dff94df987f14dd7304d25f291729f0b4926adad0df39b...,test,2626479791808743072,2024/12/2,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,test,4d4d2304e9265b029491e1fec60e7431d55285fcad426e...,test,2582720644667933856,2024/10/3,0.0,8.0,8.0,8.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,test,f05c3b1367d78a5da0b060110d8724e72664c86dc456a4...,test,2597987997622206880,2024/10/24,0.0,4.0,4.0,4.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,test,d92c8174bf3dd98aa5d11edefef13f24512c53b694071d...,test,2654564558907114656,2025/1/10,0.0,1.0,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,test,f59a8da8330c5d7b1a53654cf76ad1a119e7e9799ed5fc...,test,2596556204524176288,2024/10/22,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
96,test,00286615a6d1a01a00e2468184e36494b0622f6eada4be...,test,2597999260377023904,2024/10/24,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
97,test,e5243c068f746779d9df02f90f145ba0c08c14343593de...,test,2614109851667662240,2024/11/15,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
98,test,96827ddc764da5e62964ed70359247a1bf10d40dd3a458...,test,2562479522452604064,2024/9/5,0.0,1.0,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
99,test,a5e3e58c5db6be5cb6c46a1fffc43452b4d7ecf6f6f8f3...,test,2665543083625547168,2025/1/25,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [6]:
data_tmp.select_dtypes('O')

,name,mobile,idCard,reqToken,backPointTime
0,test,d45735e2015b20c4e8f95645096ae0dac3c9924b9e6b35...,test,2618468494244577696,2024/11/21
1,test,dff94df987f14dd7304d25f291729f0b4926adad0df39b...,test,2626479791808743072,2024/12/2
2,test,4d4d2304e9265b029491e1fec60e7431d55285fcad426e...,test,2582720644667933856,2024/10/3
3,test,f05c3b1367d78a5da0b060110d8724e72664c86dc456a4...,test,2597987997622206880,2024/10/24
4,test,d92c8174bf3dd98aa5d11edefef13f24512c53b694071d...,test,2654564558907114656,2025/1/10
...,...,...,...,...,...
95,test,f59a8da8330c5d7b1a53654cf76ad1a119e7e9799ed5fc...,test,2596556204524176288,2024/10/22
96,test,00286615a6d1a01a00e2468184e36494b0622f6eada4be...,test,2597999260377023904,2024/10/24
97,test,e5243c068f746779d9df02f90f145ba0c08c14343593de...,test,2614109851667662240,2024/11/15
98,test,96827ddc764da5e62964ed70359247a1bf10d40dd3a458...,test,2562479522452604064,2024/9/5
99,test,a5e3e58c5db6be5cb6c46a1fffc43452b4d7ecf6f6f8f3...,test,2665543083625547168,2025/1/25

In [7]:
object_columns = []
for column in data_tmp.select_dtypes('O').columns:
    if column not in ['name','idCard','mobile','reqToken','backPointTime','version']:
        print(column)
        object_columns.append(column)

In [8]:
fea_list =list(data_tmp.columns[5:])

In [9]:
fea_list

['TZ_0000_m1',
 'TZ_0000_m12',
 'TZ_0000_m15',
 'TZ_0000_m18',
 'TZ_0000_m2',
 'TZ_0000_m24',
 'TZ_0000_m3',
 'TZ_0000_m4',
 'TZ_0000_m5',
 'TZ_0000_m6',
 'TZ_0000_m9',
 'TZ_0000_w1',
 'TZ_0000_w2',
 'TZ_0000_w3',
 'TZ_0000_w4',
 'TZ_0001_m12',
 'TZ_0001_m15',
 'TZ_0001_m18',
 'TZ_0001_m2',
 'TZ_0001_m24',
 'TZ_0001_m3',
 'TZ_0001_m4',
 'TZ_0001_m5',
 'TZ_0001_m6',
 'TZ_0001_m9',
 'TZ_0001_w2',
 'TZ_0001_w3',
 'TZ_0001_w4',
 'TZ_0002_m12',
 'TZ_0002_m15',
 'TZ_0002_m18',
 'TZ_0002_m2',
 'TZ_0002_m24',
 'TZ_0002_m3',
 'TZ_0002_m4',
 'TZ_0002_m5',
 'TZ_0002_m6',
 'TZ_0002_m9',
 'TZ_0002_w2',
 'TZ_0002_w3',
 'TZ_0002_w4',
 'TZ_0003_m12',
 'TZ_0003_m15',
 'TZ_0003_m18',
 'TZ_0003_m2',
 'TZ_0003_m24',
 'TZ_0003_m3',
 'TZ_0003_m4',
 'TZ_0003_m5',
 'TZ_0003_m6',
 'TZ_0003_m9',
 'TZ_0003_w2',
 'TZ_0003_w3',
 'TZ_0003_w4',
 'TZ_0004_m1',
 'TZ_0004_m12',
 'TZ_0004_m15',
 'TZ_0004_m18',
 'TZ_0004_m2',
 'TZ_0004_m24',
 'TZ_0004_m3',
 'TZ_0004_m4',
 'TZ_0004_m5',
 'TZ_0004_m6',
 'TZ_0004_m9',
 'TZ_0004_w1',
 'TZ_0004_w2',
 'TZ_0004_w3',
 'TZ_0004_w4',
 'TZ_0005_m12',
 'TZ_0005_m15',
 'TZ_0005_m18',
 'TZ_0005_m2',
 'TZ_0005_m24',
 'TZ_0005_m3',
 'TZ_0005_m4',
 'TZ_0005_m5',
 'TZ_0005_m6',
 'TZ_0005_m9',
 'TZ_0005_w2',
 'TZ_0005_w3',
 'TZ_0005_w4',
 'TZ_0006_m12',
 'TZ_0006_m15',
 'TZ_0006_m18',
 'TZ_0006_m2',
 'TZ_0006_m24',
 'TZ_0006_m3',
 'TZ_0006_m4',
 'TZ_0006_m5',
 'TZ_0006_m6',
 'TZ_0006_m9',
 'TZ_0006_w2',
 'TZ_0006_w3',
 'TZ_0006_w4',
 'TZ_0007_m12',
 'TZ_0007_m15',
 'TZ_0007_m18',
 'TZ_0007_m2',
 'TZ_0007_m24',
 'TZ_0007_m3',
 'TZ_0007_m4',
 'TZ_0007_m5',
 'TZ_0007_m6',
 'TZ_0007_m9',
 'TZ_0007_w2',
 'TZ_0007_w3',
 'TZ_0007_w4',
 'TZ_0008_m1',
 'TZ_0008_m12',
 'TZ_0008_m15',
 'TZ_0008_m18',
 'TZ_0008_m2',
 'TZ_0008_m24',
 'TZ_0008_m3',
 'TZ_0008_m4',
 'TZ_0008_m5',
 'TZ_0008_m6',
 'TZ_0008_m9',
 'TZ_0008_w1',
 'TZ_0008_w2',
 'TZ_0008_w3',
 'TZ_0008_w4',
 'TZ_0009_m12',
 'TZ_0009_m15',
 'TZ_0009_m18',
 'TZ_0009_m2',
 'TZ_0009_m24',
 'TZ_0009_m3',
 'TZ_0009_m4',
 'TZ_0009_m5',
 'TZ_0009_m6',
 'TZ_0009_m9',
 'TZ_0009_w2',
 'TZ_0009_w3',
 'TZ_0009_w4',
 'TZ_0010_m12',
 'TZ_0010_m15',
 'TZ_0010_m18',
 'TZ_0010_m2',
 'TZ_0010_m24',
 'TZ_0010_m3',
 'TZ_0010_m4',
 'TZ_0010_m5',
 'TZ_0010_m6',
 'TZ_0010_m9',
 'TZ_0010_w2',
 'TZ_0010_w3',
 'TZ_0010_w4',
 'TZ_0011_m12',
 'TZ_0011_m15',
 'TZ_0011_m18',
 'TZ_0011_m2',
 'TZ_0011_m24',
 'TZ_0011_m3',
 'TZ_0011_m4',
 'TZ_0011_m5',
 'TZ_0011_m6',
 'TZ_0011_m9',
 'TZ_0011_w2',
 'TZ_0011_w3',
 'TZ_0011_w4',
 'TZ_0012_m1',
 'TZ_0012_m12',
 'TZ_0012_m15',
 'TZ_0012_m18',
 'TZ_0012_m2',
 'TZ_0012_m24',
 'TZ_0012_m3',
 'TZ_0012_m4',
 'TZ_0012_m5',
 'TZ_0012_m6',
 'TZ_0012_m9',
 'TZ_0012_w1',
 'TZ_0012_w2',
 'TZ_0012_w3',
 'TZ_0012_w4',
 'TZ_0013_m12',
 'TZ_0013_m15',
 'TZ_0013_m18',
 'TZ_0013_m2',
 'TZ_0013_m24',
 'TZ_0013_m3',
 'TZ_0013_m4',
 'TZ_0013_m5',
 'TZ_0013_m6',
 'TZ_0013_m9',
 'TZ_0013_w2',
 'TZ_0013_w3',
 'TZ_0013_w4',
 'TZ_0014_m12',
 'TZ_0014_m15',
 'TZ_0014_m18',
 'TZ_0014_m2',
 'TZ_0014_m24',
 'TZ_0014_m3',
 'TZ_0014_m4',
 'TZ_0014_m5',
 'TZ_0014_m6',
 'TZ_0014_m9',
 'TZ_0014_w2',
 'TZ_0014_w3',
 'TZ_0014_w4',
 'TZ_0015_m12',
 'TZ_0015_m15',
 'TZ_0015_m18',
 'TZ_0015_m2',
 'TZ_0015_m24',
 'TZ_0015_m3',
 'TZ_0015_m4',
 'TZ_0015_m5',
 'TZ_0015_m6',
 'TZ_0015_m9',
 'TZ_0015_w2',
 'TZ_0015_w3',
 'TZ_0015_w4',
 'TZ_0016_m1',
 'TZ_0016_m12',
 'TZ_0016_m15',
 'TZ_0016_m18',
 'TZ_0016_m2',
 'TZ_0016_m24',
 'TZ_0016_m3',
 'TZ_0016_m4',
 'TZ_0016_m5',
 'TZ_0016_m6',
 'TZ_0016_m9',
 'TZ_0016_w1',
 'TZ_0016_w2',
 'TZ_0016_w3',
 'TZ_0016_w4',
 'TZ_0017_m12',
 'TZ_0017_m15',
 'TZ_0017_m18',
 'TZ_0017_m2',
 'TZ_0017_m24',
 'TZ_0017_m3',
 'TZ_0017_m4',
 'TZ_0017_m5',
 'TZ_0017_m6',
 'TZ_0017_m9',
 'TZ_0017_w2',
 'TZ_0017_w3',
 'TZ_0017_w4',
 'TZ_0018_m12',
 'TZ_0018_m15',
 'TZ_0018_m18',
 'TZ_0018_m2',
 'TZ_0018_m24',
 'TZ_0018_m3',
 'TZ_0018_m4',
 'TZ_0018_m5',
 'TZ_0018_m6',
 'TZ_0018_m9',
 'TZ_0018_w2',
 'TZ_0018_w3',
 'TZ_0018_w4',
 'TZ_0019_m12',
 'TZ_0019_m15',
 'TZ_0019_m18',
 'TZ_0019_m2',
 'TZ_0019_m24',
 'TZ_0019_m3',
 'TZ_0019_m4',
 'TZ_0019_m5',
 'TZ_0019_m6',
 'TZ_0019_m9',
 'TZ_0019_w2',
 'TZ_0019_w3',
 'TZ_0019_w4',
 'TZ_0020_m1',
 'TZ_0020_m12',
 'TZ_0020_m15',
 'TZ_0020_m18',
 'TZ_0020_m2',
 'TZ_0020_m24',
 'TZ_0020_m3',
 'TZ_0020_m4',
 'TZ_0020_m5',
 'TZ_0020_m6',
 'TZ_0020_m9',
 'TZ_0020_w1',
 'TZ_0020_w2',
 'TZ_0020_w3',
 'TZ_0020_w4',
 'TZ_0021_m12',
 'TZ_0021_m15',
 'TZ_0021_m18',
 'TZ_0021_m2',
 'TZ_0021_m24',
 'TZ_0021_m3',
 'TZ_0021_m4',
 'TZ_0021_m5',
 'TZ_0021_m6',
 'TZ_0021_m9',
 'TZ_0021_w2',
 'TZ_0021_w3',
 'TZ_0021_w4',
 'TZ_0022_m12',
 'TZ_0022_m15',
 'TZ_0022_m18',
 'TZ_0022_m2',
 'TZ_0022_m24',
 'TZ_0022_m3',
 'TZ_0022_m4',
 'TZ_0022_m5',
 'TZ_0022_m6',
 'TZ_0022_m9',
 'TZ_0022_w2',
 'TZ_0022_w3',
 'TZ_0022_w4',
 'TZ_0023_m12',
 'TZ_0023_m15',
 'TZ_0023_m18',
 'TZ_0023_m2',
 'TZ_0023_m24',
 'TZ_0023_m3',
 'TZ_0023_m4',
 'TZ_0023_m5',
 'TZ_0023_m6',
 'TZ_0023_m9',
 'TZ_0023_w2',
 'TZ_0023_w3',
 'TZ_0023_w4',
 'TZ_0024_m1',
 'TZ_0024_m12',
 'TZ_0024_m15',
 'TZ_0024_m18',
 'TZ_0024_m2',
 'TZ_0024_m24',
 'TZ_0024_m3',
 'TZ_0024_m4',
 'TZ_0024_m5',
 'TZ_0024_m6',
 'TZ_0024_m9',
 'TZ_0024_w1',
 'TZ_0024_w2',
 'TZ_0024_w3',
 'TZ_0024_w4',
 'TZ_0025_m12',
 'TZ_0025_m15',
 'TZ_0025_m18',
 'TZ_0025_m2',
 'TZ_0025_m24',
 'TZ_0025_m3',
 'TZ_0025_m4',
 'TZ_0025_m5',
 'TZ_0025_m6',
 'TZ_0025_m9',
 'TZ_0025_w2',
 'TZ_0025_w3',
 'TZ_0025_w4',
 'TZ_0026_m12',
 'TZ_0026_m15',
 'TZ_0026_m18',
 'TZ_0026_m2',
 'TZ_0026_m24',
 'TZ_0026_m3',
 'TZ_0026_m4',
 'TZ_0026_m5',
 'TZ_0026_m6',
 'TZ_0026_m9',
 'TZ_0026_w2',
 'TZ_0026_w3',
 'TZ_0026_w4',
 'TZ_0027_m12',
 'TZ_0027_m15',
 'TZ_0027_m18',
 'TZ_0027_m2',
 'TZ_0027_m24',
 'TZ_0027_m3',
 'TZ_0027_m4',
 'TZ_0027_m5',
 'TZ_0027_m6',
 'TZ_0027_m9',
 'TZ_0027_w2',
 'TZ_0027_w3',
 'TZ_0027_w4',
 'TZ_0028_m1',
 'TZ_0028_m12',
 'TZ_0028_m15',
 'TZ_0028_m18',
 'TZ_0028_m2',
 'TZ_0028_m24',
 'TZ_0028_m3',
 'TZ_0028_m4',
 'TZ_0028_m5',
 'TZ_0028_m6',
 'TZ_0028_m9',
 'TZ_0028_w1',
 'TZ_0028_w2',
 'TZ_0028_w3',
 'TZ_0028_w4',
 'TZ_0029_m12',
 'TZ_0029_m15',
 'TZ_0029_m18',
 'TZ_0029_m2',
 'TZ_0029_m24',
 'TZ_0029_m3',
 'TZ_0029_m4',
 'TZ_0029_m5',
 'TZ_0029_m6',
 'TZ_0029_m9',
 'TZ_0029_w2',
 'TZ_0029_w3',
 'TZ_0029_w4',
 'TZ_0030_m12',
 'TZ_0030_m15',
 'TZ_0030_m18',
 'TZ_0030_m2',
 'TZ_0030_m24',
 'TZ_0030_m3',
 'TZ_0030_m4',
 'TZ_0030_m5',
 'TZ_0030_m6',
 'TZ_0030_m9',
 'TZ_0030_w2',
 'TZ_0030_w3',
 'TZ_0030_w4',
 'TZ_0031_m12',
 'TZ_0031_m15',
 'TZ_0031_m18',
 'TZ_0031_m2',
 'TZ_0031_m24',
 'TZ_0031_m3',
 'TZ_0031_m4',
 'TZ_0031_m5',
 'TZ_0031_m6',
 'TZ_0031_m9',
 'TZ_0031_w2',
 'TZ_0031_w3',
 'TZ_0031_w4',
 'TZ_0032_m1',
 'TZ_0032_m12',
 'TZ_0032_m15',
 'TZ_0032_m18',
 'TZ_0032_m2',
 'TZ_0032_m24',
 'TZ_0032_m3',
 'TZ_0032_m4',
 'TZ_0032_m5',
 'TZ_0032_m6',
 'TZ_0032_m9',
 'TZ_0032_w1',
 'TZ_0032_w2',
 'TZ_0032_w3',
 'TZ_0032_w4',
 'TZ_0033_m12',
 'TZ_0033_m15',
 'TZ_0033_m18',
 'TZ_0033_m2',
 'TZ_0033_m24',
 'TZ_0033_m3',
 'TZ_0033_m4',
 'TZ_0033_m5',
 'TZ_0033_m6',
 'TZ_0033_m9',
 'TZ_0033_w2',
 'TZ_0033_w3',
 'TZ_0033_w4',
 'TZ_0034_m12',
 'TZ_0034_m15',
 'TZ_0034_m18',
 'TZ_0034_m2',
 'TZ_0034_m24',
 'TZ_0034_m3',
 'TZ_0034_m4',
 'TZ_0034_m5',
 'TZ_0034_m6',
 'TZ_0034_m9',
 'TZ_0034_w2',
 'TZ_0034_w3',
 'TZ_0034_w4',
 'TZ_0035_m12',
 'TZ_0035_m15',
 'TZ_0035_m18',
 'TZ_0035_m2',
 'TZ_0035_m24',
 'TZ_0035_m3',
 'TZ_0035_m4',
 'TZ_0035_m5',
 'TZ_0035_m6',
 'TZ_0035_m9',
 'TZ_0035_w2',
 'TZ_0035_w3',
 'TZ_0035_w4',
 'TZ_0036_m1',
 'TZ_0036_m12',
 'TZ_0036_m15',
 'TZ_0036_m18',
 'TZ_0036_m2',
 'TZ_0036_m24',
 'TZ_0036_m3',
 'TZ_0036_m4',
 'TZ_0036_m5',
 'TZ_0036_m6',
 'TZ_0036_m9',
 'TZ_0036_w1',
 'TZ_0036_w2',
 'TZ_0036_w3',
 'TZ_0036_w4',
 'TZ_0037_m12',
 'TZ_0037_m15',
 'TZ_0037_m18',
 'TZ_0037_m2',
 'TZ_0037_m24',
 'TZ_0037_m3',
 'TZ_0037_m4',
 'TZ_0037_m5',
 'TZ_0037_m6',
 'TZ_0037_m9',
 'TZ_0037_w2',
 'TZ_0037_w3',
 'TZ_0037_w4',
 'TZ_0038_m12',
 'TZ_0038_m15',
 'TZ_0038_m18',
 'TZ_0038_m2',
 'TZ_0038_m24',
 'TZ_0038_m3',
 'TZ_0038_m4',
 'TZ_0038_m5',
 'TZ_0038_m6',
 'TZ_0038_m9',
 'TZ_0038_w2',
 'TZ_0038_w3',
 'TZ_0038_w4',
 'TZ_0039_m12',
 'TZ_0039_m15',
 'TZ_0039_m18',
 'TZ_0039_m2',
 'TZ_0039_m24',
 'TZ_0039_m3',
 'TZ_0039_m4',
 'TZ_0039_m5',
 'TZ_0039_m6',
 'TZ_0039_m9',
 'TZ_0039_w2',
 'TZ_0039_w3',
 'TZ_0039_w4',
 'TZ_0040_m1',
 'TZ_0040_m12',
 'TZ_0040_m15',
 'TZ_0040_m18',
 'TZ_0040_m2',
 'TZ_0040_m24',
 'TZ_0040_m3',
 'TZ_0040_m4',
 'TZ_0040_m5',
 'TZ_0040_m6',
 'TZ_0040_m9',
 'TZ_0040_w1',
 'TZ_0040_w2',
 'TZ_0040_w3',
 'TZ_0040_w4',
 'TZ_0041_m12',
 'TZ_0041_m15',
 'TZ_0041_m18',
 'TZ_0041_m2',
 'TZ_0041_m24',
 'TZ_0041_m3',
 'TZ_0041_m4',
 'TZ_0041_m5',
 'TZ_0041_m6',
 'TZ_0041_m9',
 'TZ_0041_w2',
 'TZ_0041_w3',
 'TZ_0041_w4',
 'TZ_0042_m12',
 'TZ_0042_m15',
 'TZ_0042_m18',
 'TZ_0042_m2',
 'TZ_0042_m24',
 'TZ_0042_m3',
 'TZ_0042_m4',
 'TZ_0042_m5',
 'TZ_0042_m6',
 'TZ_0042_m9',
 'TZ_0042_w2',
 'TZ_0042_w3',
 'TZ_0042_w4',
 'TZ_0043_m12',
 'TZ_0043_m15',
 'TZ_0043_m18',
 'TZ_0043_m2',
 'TZ_0043_m24',
 'TZ_0043_m3',
 'TZ_0043_m4',
 'TZ_0043_m5',
 'TZ_0043_m6',
 'TZ_0043_m9',
 'TZ_0043_w2',
 'TZ_0043_w3',
 'TZ_0043_w4',
 'TZ_0044_m1',
 'TZ_0044_m12',
 'TZ_0044_m15',
 'TZ_0044_m18',
 'TZ_0044_m2',
 'TZ_0044_m24',
 'TZ_0044_m3',
 'TZ_0044_m4',
 'TZ_0044_m5',
 'TZ_0044_m6',
 'TZ_0044_m9',
 'TZ_0044_w1',
 'TZ_0044_w2',
 'TZ_0044_w3',
 'TZ_0044_w4',
 'TZ_0045_m12',
 'TZ_0045_m15',
 'TZ_0045_m18',
 'TZ_0045_m2',
 'TZ_0045_m24',
 'TZ_0045_m3',
 'TZ_0045_m4',
 'TZ_0045_m5',
 'TZ_0045_m6',
 'TZ_0045_m9',
 'TZ_0045_w2',
 'TZ_0045_w3',
 'TZ_0045_w4',
 'TZ_0046_m12',
 'TZ_0046_m15',
 'TZ_0046_m18',
 'TZ_0046_m2',
 'TZ_0046_m24',
 'TZ_0046_m3',
 'TZ_0046_m4',
 'TZ_0046_m5',
 'TZ_0046_m6',
 'TZ_0046_m9',
 'TZ_0046_w2',
 'TZ_0046_w3',
 'TZ_0046_w4',
 'TZ_0047_m12',
 'TZ_0047_m15',
 'TZ_0047_m18',
 'TZ_0047_m2',
 'TZ_0047_m24',
 'TZ_0047_m3',
 'TZ_0047_m4',
 'TZ_0047_m5',
 'TZ_0047_m6',
 'TZ_0047_m9',
 'TZ_0047_w2',
 'TZ_0047_w3',
 'TZ_0047_w4',
 'TZ_0048_m1',
 'TZ_0048_m12',
 'TZ_0048_m15',
 'TZ_0048_m18',
 'TZ_0048_m2',
 'TZ_0048_m24',
 'TZ_0048_m3',
 'TZ_0048_m4',
 'TZ_0048_m5',
 'TZ_0048_m6',
 'TZ_0048_m9',
 'TZ_0048_w1',
 'TZ_0048_w2',
 'TZ_0048_w3',
 'TZ_0048_w4',
 'TZ_0049_m12',
 'TZ_0049_m15',
 'TZ_0049_m18',
 'TZ_0049_m2',
 'TZ_0049_m24',
 'TZ_0049_m3',
 'TZ_0049_m4',
 'TZ_0049_m5',
 'TZ_0049_m6',
 'TZ_0049_m9',
 'TZ_0049_w2',
 'TZ_0049_w3',
 'TZ_0049_w4',
 'TZ_0050_m12',
 'TZ_0050_m15',
 'TZ_0050_m18',
 'TZ_0050_m2',
 'TZ_0050_m24',
 'TZ_0050_m3',
 'TZ_0050_m4',
 'TZ_0050_m5',
 'TZ_0050_m6',
 'TZ_0050_m9',
 'TZ_0050_w2',
 'TZ_0050_w3',
 'TZ_0050_w4',
 'TZ_0051_m12',
 'TZ_0051_m15',
 'TZ_0051_m18',
 'TZ_0051_m2',
 'TZ_0051_m24',
 'TZ_0051_m3',
 'TZ_0051_m4',
 'TZ_0051_m5',
 'TZ_0051_m6',
 'TZ_0051_m9',
 'TZ_0051_w2',
 'TZ_0051_w3',
 'TZ_0051_w4',
 'TZ_0052_m1',
 'TZ_0052_m12',
 'TZ_0052_m15',
 'TZ_0052_m18',
 'TZ_0052_m2',
 'TZ_0052_m24',
 'TZ_0052_m3',
 'TZ_0052_m4',
 'TZ_0052_m5',
 'TZ_0052_m6',
 'TZ_0052_m9',
 'TZ_0052_w1',
 'TZ_0052_w2',
 'TZ_0052_w3',
 'TZ_0052_w4',
 'TZ_0053_m12',
 'TZ_0053_m15',
 'TZ_0053_m18',
 'TZ_0053_m2',
 'TZ_0053_m24',
 'TZ_0053_m3',
 'TZ_0053_m4',
 'TZ_0053_m5',
 'TZ_0053_m6',
 'TZ_0053_m9',
 'TZ_0053_w2',
 'TZ_0053_w3',
 'TZ_0053_w4',
 'TZ_0054_m12',
 'TZ_0054_m15',
 'TZ_0054_m18',
 'TZ_0054_m2',
 'TZ_0054_m24',
 'TZ_0054_m3',
 'TZ_0054_m4',
 'TZ_0054_m5',
 'TZ_0054_m6',
 'TZ_0054_m9',
 'TZ_0054_w2',
 'TZ_0054_w3',
 'TZ_0054_w4',
 'TZ_0055_m12',
 'TZ_0055_m15',
 'TZ_0055_m18',
 'TZ_0055_m2',
 'TZ_0055_m24',
 'TZ_0055_m3',
 'TZ_0055_m4',
 'TZ_0055_m5',
 'TZ_0055_m6',
 'TZ_0055_m9',
 'TZ_0055_w2',
 'TZ_0055_w3',
 'TZ_0055_w4',
 'TZ_0056_m1',
 'TZ_0056_m12',
 'TZ_0056_m15',
 'TZ_0056_m18',
 'TZ_0056_m2',
 'TZ_0056_m24',
 'TZ_0056_m3',
 'TZ_0056_m4',
 'TZ_0056_m5',
 'TZ_0056_m6',
 'TZ_0056_m9',
 'TZ_0056_w1',
 'TZ_0056_w2',
 'TZ_0056_w3',
 'TZ_0056_w4',
 'TZ_0057_m12',
 'TZ_0057_m15',
 'TZ_0057_m18',
 'TZ_0057_m2',
 'TZ_0057_m24',
 'TZ_0057_m3',
 'TZ_0057_m4',
 'TZ_0057_m5',
 'TZ_0057_m6',
 'TZ_0057_m9',
 'TZ_0057_w2',
 'TZ_0057_w3',
 'TZ_0057_w4',
 'TZ_0058_m12',
 'TZ_0058_m15',
 'TZ_0058_m18',
 'TZ_0058_m2',
 'TZ_0058_m24',
 'TZ_0058_m3',
 'TZ_0058_m4',
 'TZ_0058_m5',
 'TZ_0058_m6',
 'TZ_0058_m9',
 'TZ_0058_w2',
 'TZ_0058_w3',
 'TZ_0058_w4',
 'TZ_0059_m12',
 'TZ_0059_m15',
 'TZ_0059_m18',
 'TZ_0059_m2',
 'TZ_0059_m24',
 'TZ_0059_m3',
 'TZ_0059_m4',
 'TZ_0059_m5',
 'TZ_0059_m6',
 'TZ_0059_m9',
 'TZ_0059_w2',
 'TZ_0059_w3',
 'TZ_0059_w4',
 'TZ_0060_m1',
 'TZ_0060_m12',
 'TZ_0060_m15',
 'TZ_0060_m18',
 'TZ_0060_m2',
 'TZ_0060_m24',
 'TZ_0060_m3',
 'TZ_0060_m4',
 'TZ_0060_m5',
 'TZ_0060_m6',
 'TZ_0060_m9',
 'TZ_0060_w1',
 'TZ_0060_w2',
 'TZ_0060_w3',
 'TZ_0060_w4',
 'TZ_0061_m12',
 'TZ_0061_m15',
 'TZ_0061_m18',
 'TZ_0061_m2',
 'TZ_0061_m24',
 'TZ_0061_m3',
 'TZ_0061_m4',
 'TZ_0061_m5',
 'TZ_0061_m6',
 'TZ_0061_m9',
 'TZ_0061_w2',
 'TZ_0061_w3',
 'TZ_0061_w4',
 'TZ_0062_m12',
 'TZ_0062_m15',
 'TZ_0062_m18',
 'TZ_0062_m2',
 'TZ_0062_m24',
 'TZ_0062_m3',
 'TZ_0062_m4',
 'TZ_0062_m5',
 'TZ_0062_m6',
 'TZ_0062_m9',
 'TZ_0062_w2',
 'TZ_0062_w3',
 'TZ_0062_w4',
 'TZ_0063_m12',
 'TZ_0063_m15',
 'TZ_0063_m18',
 'TZ_0063_m2',
 'TZ_0063_m24',
 'TZ_0063_m3',
 'TZ_0063_m4',
 'TZ_0063_m5',
 'TZ_0063_m6',
 'TZ_0063_m9',
 'TZ_0063_w2',
 'TZ_0063_w3',
 'TZ_0063_w4',
 'TZ_0064_m1',
 'TZ_0064_m12',
 'TZ_0064_m15',
 'TZ_0064_m18',
 'TZ_0064_m2',
 'TZ_0064_m24',
 'TZ_0064_m3',
 'TZ_0064_m4',
 'TZ_0064_m5',
 'TZ_0064_m6',
 'TZ_0064_m9',
 'TZ_0064_w1',
 'TZ_0064_w2',
 'TZ_0064_w3',
 'TZ_0064_w4',
 'TZ_0065_m12',
 'TZ_0065_m15',
 'TZ_0065_m18',
 'TZ_0065_m2',
 'TZ_0065_m24',
 'TZ_0065_m3',
 'TZ_0065_m4',
 'TZ_0065_m5',
 'TZ_0065_m6',
 'TZ_0065_m9',
 'TZ_0065_w2',
 'TZ_0065_w3',
 'TZ_0065_w4',
 'TZ_0066_m12',
 'TZ_0066_m15',
 'TZ_0066_m18',
 'TZ_0066_m2',
 'TZ_0066_m24',
 'TZ_0066_m3',
 'TZ_0066_m4',
 'TZ_0066_m5',
 'TZ_0066_m6',
 'TZ_0066_m9',
 'TZ_0066_w2',
 'TZ_0066_w3',
 'TZ_0066_w4',
 'TZ_0067_m12',
 'TZ_0067_m15',
 'TZ_0067_m18',
 'TZ_0067_m2',
 'TZ_0067_m24',
 'TZ_0067_m3',
 'TZ_0067_m4',
 'TZ_0067_m5',
 'TZ_0067_m6',
 'TZ_0067_m9',
 'TZ_0067_w2',
 'TZ_0067_w3',
 'TZ_0067_w4',
 'TZ_0068_m1',
 'TZ_0068_m12',
 'TZ_0068_m15',
 'TZ_0068_m18',
 'TZ_0068_m2',
 'TZ_0068_m24',
 'TZ_0068_m3',
 'TZ_0068_m4',
 'TZ_0068_m5',
 'TZ_0068_m6',
 'TZ_0068_m9',
 'TZ_0068_w1',
 'TZ_0068_w2',
 'TZ_0068_w3',
 'TZ_0068_w4',
 'TZ_0069_m12',
 'TZ_0069_m15',
 'TZ_0069_m18',
 'TZ_0069_m2',
 'TZ_0069_m24',
 'TZ_0069_m3',
 'TZ_0069_m4',
 'TZ_0069_m5',
 'TZ_0069_m6',
 'TZ_0069_m9',
 'TZ_0069_w2',
 'TZ_0069_w3',
 'TZ_0069_w4',
 'TZ_0070_m12',
 'TZ_0070_m15',
 'TZ_0070_m18',
 'TZ_0070_m2',
 'TZ_0070_m24',
 'TZ_0070_m3',
 'TZ_0070_m4',
 'TZ_0070_m5',
 'TZ_0070_m6',
 'TZ_0070_m9',
 'TZ_0070_w2',
 'TZ_0070_w3',
 'TZ_0070_w4',
 'TZ_0071_m12',
 'TZ_0071_m15',
 'TZ_0071_m18',
 'TZ_0071_m2',
 'TZ_0071_m24',
 'TZ_0071_m3',
 'TZ_0071_m4',
 'TZ_0071_m5',
 'TZ_0071_m6',
 'TZ_0071_m9',
 'TZ_0071_w2',
 'TZ_0071_w3',
 'TZ_0071_w4',
 'TZ_0072_m1',
 'TZ_0072_m12',
 'TZ_0072_m15',
 'TZ_0072_m18',
 'TZ_0072_m2',
 'TZ_0072_m24',
 'TZ_0072_m3',
 'TZ_0072_m4',
 'TZ_0072_m5',
 'TZ_0072_m6',
 'TZ_0072_m9',
 'TZ_0072_w1',
 'TZ_0072_w2',
 'TZ_0072_w3',
 'TZ_0072_w4',
 'TZ_0073_m12',
 'TZ_0073_m15',
 'TZ_0073_m18',
 'TZ_0073_m2',
 'TZ_0073_m24',
 'TZ_0073_m3',
 'TZ_0073_m4',
 'TZ_0073_m5',
 'TZ_0073_m6',
 'TZ_0073_m9',
 'TZ_0073_w2',
 'TZ_0073_w3',
 'TZ_0073_w4',
 ...]

In [10]:
len(fea_list)

15160

In [11]:
if debug:
    fea_list = fea_list[:1000]

In [ ]:
from new_tools import flitter_by_std_fpr
ftr1_keep_dict = {}
length = 500
for i in range(0,(len(fea_list) // length) + 1):
    start,end  = i * length, min((i + 1) * length, len(fea_list))
    print(start, ' - ', end)
    tmp_lst = [i for i in fea_list[start:end] if i not in object_columns]
    with zipfile.ZipFile(DATA_OR_PATH + '驭鉴20250707_LH_deltaV1_result.txt.zip', 'r') as zip_file:
        file_list = zip_file.namelist()
        # print("压缩包内文件:", file_list)
        csv_filename = [f for f in file_list if f.endswith('.txt') or f.endswith('.csv')][0]
        with zip_file.open(csv_filename) as csv_file:
            each_df = pd.read_csv(csv_file, usecols=tmp_lst)
    # each_df = pd.read_csv(DATA_OR_PATH + '驭鉴20250707_LH1__result.txt', usecols=fea_list[start:end])
    ftr1_keep = flitter_by_std_fpr.drop_svr(each_df.fillna(-999), 0.95, tmp_lst)
    ftr1_keep = flitter_by_std_fpr.drop_std(each_df.fillna(-999), 0, ftr1_keep)
    ftr1_keep_dict[i] = ftr1_keep
    del each_df, ftr1_keep
    gc.collect()

In [ ]:
fea_list = []
for k,v in ftr1_keep_dict.items():
    fea_list.extend(v)

In [14]:
fea_list = list(set(fea_list))
fea_list

['TZ_0687_m24',
 'TZ_0091_m9',
 'TZ_1401_m3',
 'TZ_0016_w3',
 'TZ_1641_m6',
 'TZ_0124_m5',
 'TZ_0012_m4',
 'TZ_0971_m12',
 'TZ_1191_m1',
 'TZ_1807_m3',
 'TZ_0149_m18',
 'TZ_0171_m5',
 'TZ_1822_m18',
 'TZ_0214_m2',
 'TZ_1661_m6',
 'TZ_0634_m24',
 'TZ_1486_m6',
 'TZ_1212_m6',
 'TZ_1558_m24',
 'TZ_1717_m12',
 'TZ_0895_m24',
 'TZ_0335_m9',
 'TZ_1977_m6',
 'TZ_1850_m6',
 'TZ_0574_w1',
 'TZ_0136_m6',
 'TZ_1263_m12',
 'TZ_1961_m3',
 'TZ_0323_m24',
 'TZ_0577_T3_m3',
 'TZ_0110_m4',
 'TZ_0605_m9',
 'TZ_1475_m24',
 'TZ_1877_m6',
 'TZ_0115_m24',
 'TZ_0434_m8',
 'TZ_1209_m18',
 'TZ_0155_w3',
 'TZ_1936_m1',
 'TZ_1734_m3',
 'TZ_0318_m15',
 'TZ_1615_m12',
 'TZ_1282_m3',
 'TZ_0416_m4',
 'TZ_0320_w3',
 'TZ_0271_m15',
 'TZ_0255_w4',
 'TZ_0279_w2',
 'TZ_0302_m24',
 'TZ_0049_w4',
 'TZ_1867_m3',
 'TZ_0221_w2',
 'TZ_0239_w4',
 'TZ_0454_m12',
 'TZ_0072_m4',
 'TZ_1508_m3',
 'TZ_0327_m15',
 'TZ_0086_w2',
 'TZ_0133_w4',
 'TZ_0650_m6',
 'TZ_0233_m9',
 'TZ_1515_m12',
 'TZ_1535_m24',
 'TZ_1585_m24',
 'TZ_1628_m18',
 'TZ_1954_m12',
 'TZ_1114_m1',
 'TZ_0287_m6',
 'TZ_1977_m1',
 'TZ_0728_m24',
 'TZ_0020_m5',
 'TZ_0547_m5',
 'TZ_1619_m12',
 'TZ_0503_m12',
 'TZ_0087_m5',
 'TZ_1351_m3',
 'TZ_0635_m12',
 'TZ_1325_m18',
 'TZ_1938_m18',
 'TZ_1300_m18',
 'TZ_0045_m12',
 'TZ_0241_m24',
 'TZ_0206_m3',
 'TZ_1139_m24',
 'TZ_0041_m24',
 'TZ_1947_m1',
 'TZ_1821_m24',
 'TZ_2016_T2_m18',
 'TZ_0209_w4',
 'TZ_0512_m9',
 'TZ_0514_m10',
 'TZ_0685_m12',
 'TZ_0193_m2',
 'TZ_0404_m1',
 'TZ_0541_m1',
 'TZ_1638_m1',
 'TZ_1628_m3',
 'TZ_1525_m1',
 'TZ_0577_T3_m1',
 'TZ_1843_m12',
 'TZ_0219_w2',
 'TZ_1919_m3',
 'TZ_0841_m1',
 'TZ_0692_m1',
 'TZ_0510_m1',
 'TZ_0082_m5',
 'TZ_0220_m9',
 'TZ_1406_m24',
 'TZ_1365_m3',
 'TZ_0637_m12',
 'TZ_0263_w2',
 'TZ_0513_m6',
 'TZ_0316_m1',
 'TZ_0757_m9',
 'TZ_0757_m3',
 'TZ_0010_m9',
 'TZ_0164_m9',
 'TZ_1326_m1',
 'TZ_1616_m24',
 'TZ_1772_m12',
 'TZ_1974_m1',
 'TZ_0148_m3',
 'TZ_0534_m24',
 'TZ_1510_m24',
 'TZ_0239_w3',
 'TZ_0933_m12',
 'TZ_1958_m18',
 'TZ_0210_m2',
 'TZ_2003_m4',
 'TZ_0558_m2',
 'TZ_2018_T2_m2',
 'TZ_1304_m6',
 'TZ_0795_m3',
 'TZ_1981_m18',
 'TZ_0091_w4',
 'TZ_0255_m24',
 'TZ_0522_m24',
 'TZ_0889_m6',
 'TZ_1198_m18',
 'TZ_1262_m12',
 'TZ_1506_m24',
 'TZ_1640_m12',
 'TZ_0128_m18',
 'TZ_0068_m24',
 'TZ_0178_w3',
 'TZ_0133_m18',
 'TZ_0525_m1',
 'TZ_0534_m12',
 'TZ_0809_m3',
 'TZ_1368_m12',
 'TZ_0047_m9',
 'TZ_1224_m12',
 'TZ_0477_m12',
 'TZ_0298_m12',
 'TZ_0045_w3',
 'TZ_1641_m24',
 'TZ_0320_m18',
 'TZ_1155_m6',
 'TZ_1235_m18',
 'TZ_1811_m12',
 'TZ_0345_w2',
 'TZ_0191_m6',
 'TZ_1063_m7',
 'TZ_1260_m12',
 'TZ_0468_m3',
 'TZ_0237_m18',
 'TZ_1520_m1',
 'TZ_0036_m2',
 'TZ_1654_m12',
 'TZ_1877_m18',
 'TZ_0349_w1',
 'TZ_0410_m7',
 'TZ_0411_m8',
 'TZ_0172_w2',
 'TZ_0357_w3',
 'TZ_0654_m7',
 'TZ_1887_m24',
 'TZ_1159_m3',
 'TZ_1918_m18',
 'TZ_0320_m15',
 'TZ_0215_m5',
 'TZ_0124_m1',
 'TZ_1614_m3',
 'TZ_1809_m1',
 'TZ_1664_m18',
 'TZ_0435_m7',
 'TZ_1160_m24',
 'TZ_0045_m24',
 'TZ_0008_m2',
 'TZ_0439_m24',
 'TZ_0197_m9',
 'TZ_1557_m24',
 'TZ_0864_m18',
 'TZ_0006_m6',
 'TZ_2018_T1_m9',
 'TZ_0416_m2',
 'TZ_0101_m15',
 'TZ_0427_m9',
 'TZ_1465_m24',
 'TZ_0340_m3',
 'TZ_0073_m4',
 'TZ_1558_m3',
 'TZ_1619_m1',
 'TZ_1110',
 'TZ_0139_m9',
 'TZ_1364_m18',
 'TZ_0507_m4',
 'TZ_0418_m12',
 'TZ_0296_w4',
 'TZ_1780_m3',
 'TZ_1773_m6',
 'TZ_1455_m18',
 'TZ_0260_w1',
 'TZ_0001_w2',
 'TZ_1349_m18',
 'TZ_1930_m6',
 'TZ_0246_w4',
 'TZ_1315_m12',
 'TZ_0416_m1',
 'TZ_0082_w2',
 'TZ_0093_w2',
 'TZ_0307_w2',
 'TZ_0348_m24',
 'TZ_0052_m1',
 'TZ_0263_w4',
 'TZ_0334_m6',
 'TZ_0194_m2',
 'TZ_0401_m1',
 'TZ_1625_m1',
 'TZ_0091_m18',
 'TZ_0415_m11',
 'TZ_0517_m24',
 'TZ_0682_m2',
 'TZ_1500_m24',
 'TZ_1487_m6',
 'TZ_2022_T1_m7',
 'TZ_0473_m3',
 'TZ_0719_m3',
 'TZ_0026_m15',
 'TZ_0769_w1',
 'TZ_0684_m4',
 'TZ_0844_w1',
 'TZ_0316_w2',
 'TZ_1731_m24',
 'TZ_0137_m9',
 'TZ_0526_m24',
 'TZ_0236_m4',
 'TZ_0518_m4',
 'TZ_0356_m6',
 'TZ_0023_w3',
 'TZ_0721_m3',
 'TZ_0684_m8',
 'TZ_0194_m18',
 'TZ_0304_m24',
 'TZ_1976_m24',
 'TZ_1137_m12',
 'TZ_0768_m1',
 'TZ_0558_m8',
 'TZ_1760_m18',
 'TZ_1444_m12',
 'TZ_0449_m9',
 'TZ_0212_m2',
 'TZ_1595_m12',
 'TZ_1792_m12',
 'TZ_0406_m10',
 'TZ_0124_w4',
 'TZ_1555_m6',
 'TZ_0339_m9',
 'TZ_2024_T3_m4',
 'TZ_0715_m24',
 'TZ_1965_m18',
 'TZ_0607_m3',
 'TZ_1482_m1',
 'TZ_1413_m3',
 'TZ_1899_m24',
 'TZ_1452_m24',
 'TZ_0559_m9',
 'TZ_0857_m1',
 'TZ_1065_m6',
 'TZ_1389_m1',
 'TZ_0140_m24',
 'TZ_0080_m9',
 'TZ_0864_w1',
 'TZ_1390_m1',
 'TZ_0315_m12',
 'TZ_0165_w3',
 'TZ_0042_m9',
 'TZ_1415_m6',
 'TZ_1424_m6',
 'TZ_1972_m6',
 'TZ_0335_w4',
 'TZ_0118_m3',
 'TZ_1269_m12',
 'TZ_2002_m9',
 'TZ_0712_m24',
 'TZ_1879_m12',
 'TZ_0061_w3',
 'TZ_0180_w4',
 'TZ_0292_w1',
 'TZ_0470_m2',
 'TZ_0317_m6',
 'TZ_1034_m1',
 'TZ_0103_w4',
 'TZ_1956_m18',
 'TZ_0255_m4',
 'TZ_0322_w4',
 'TZ_1679_m3',
 'TZ_0414_m10',
 'TZ_1755_m6',
 'TZ_2024_T1_m7',
 'TZ_0092_w4',
 'TZ_2017_T3_m3',
 'TZ_1735_m12',
 'TZ_1765_m24',
 'TZ_0949',
 'TZ_0192_m6',
 'TZ_1906_m18',
 'TZ_0000_w4',
 'TZ_0463_m6',
 'TZ_0181_m5',
 'TZ_1194_m24',
 'TZ_0611_m12',
 'TZ_1448_m1',
 'TZ_0307_m4',
 'TZ_0933_m24',
 'TZ_0792_m6',
 'TZ_0434_m4',
 'TZ_1775_m18',
 'TZ_1864_m6',
 'TZ_0630_m2',
 'TZ_2001_w4',
 'TZ_0615_m11',
 'TZ_0706_m7',
 'TZ_0000_m2',
 'TZ_0874_m1',
 'TZ_1995_m3',
 'TZ_0064_m12',
 'TZ_0750_m24',
 'TZ_1184_m3',
 'TZ_1355_m3',
 'TZ_1593_m3',
 'TZ_0067_m6',
 'TZ_0187_m2',
 'TZ_0477_m6',
 'TZ_1817_m18',
 'TZ_2003_m6',
 'TZ_0336_w2',
 'TZ_0841_m12',
 'TZ_1980_m24',
 'TZ_1366_m24',
 'TZ_0292_m15',
 'TZ_0824_m12',
 'TZ_1380_m24',
 'TZ_1490_m6',
 'TZ_0249_m24',
 'TZ_0329_m9',
 'TZ_1825_m1',
 'TZ_1973_m18',
 'TZ_0021_w4',
 'TZ_0760_m18',
 'TZ_0815_m12',
 'TZ_1667_m24',
 'TZ_0190_m5',
 'TZ_1694_m18',
 'TZ_1905_m24',
 'TZ_0177_m15',
 'TZ_0360_w4',
 'TZ_0258_m6',
 'TZ_0285_w3',
 'TZ_1290_m12',
 'TZ_0000_m1',
 'TZ_0983_m12',
 'TZ_1578_m24',
 'TZ_1748_m24',
 'TZ_0026_m24',
 'TZ_1120_m12',
 'TZ_1946_m1',
 'TZ_0467_m7',
 'TZ_0234_m12',
 'TZ_1216_m12',
 'TZ_0823_m3',
 'TZ_1163_m3',
 'TZ_0029_m12',
 'TZ_0904_m12',
 'TZ_1786_m1',
 'TZ_1197_m12',
 'TZ_0514_m9',
 'TZ_0873_m11',
 'TZ_0287_m18',
 'TZ_2024_T4_m24',
 'TZ_1609_m12',
 'TZ_0275_m6',
 'TZ_0499_m6',
 'TZ_0247_m2',
 'TZ_1342_m6',
 'TZ_0809_m2',
 'TZ_1648_m24',
 'TZ_0287_w2',
 'TZ_1127_m6',
 'TZ_2020_T2_m8',
 'TZ_0392_m2',
 'TZ_1896_m18',
 'TZ_0325_w3',
 'TZ_0147_m18',
 'TZ_0071_w2',
 'TZ_1690_m3',
 'TZ_0158_m2',
 'TZ_1346_m18',
 'TZ_0359_m9',
 'TZ_0861_m6',
 'TZ_1424_m12',
 'TZ_0634_m2',
 'TZ_1995_m18',
 'TZ_0353_m2',
 'TZ_0685_m3',
 'TZ_0441_m7',
 'TZ_0105_m3',
 'TZ_0229_m4',
 'TZ_0328_m12',
 'TZ_0108_m15',
 'TZ_0119_m2',
 'TZ_1387_m3',
 'TZ_0148_m2',
 'TZ_2013_m3',
 'TZ_1857_m1',
 'TZ_0060_m6',
 'TZ_0516_m7',
 'TZ_1868_m6',
 'TZ_0310_m6',
 'TZ_0924_m24',
 'TZ_0272_m6',
 'TZ_1890_m12',
 'TZ_0475_m9',
 'TZ_0140_m4',
 'TZ_0144_m1',
 'TZ_0139_m6',
 'TZ_1322_m6',
 'TZ_0605_m8',
 'TZ_1994_m3',
 'TZ_0006_m5',
 'TZ_0568_m24',
 'TZ_0134_m18',
 'TZ_0520_m4',
 'TZ_0194_m5',
 'TZ_1529_m1',
 'TZ_1148_m12',
 'TZ_1574_m3',
 'TZ_0236_w3',
 'TZ_0676_m8',
 'TZ_0141_w4',
 'TZ_1176_m6',
 'TZ_1908_m1',
 'TZ_0184_m18',
 'TZ_0568_m18',
 'TZ_0906_m12',
 'TZ_1191_m12',
 'TZ_1558_m12',
 'TZ_1323_m18',
 'TZ_0106_m3',
 'TZ_0413_m3',
 'TZ_1646_m6',
 'TZ_1488_m6',
 'TZ_0431_m9',
 'TZ_1271_m6',
 'TZ_0259_m15',
 'TZ_0169_m12',
 'TZ_1138_m24',
 'TZ_0080_m5',
 'TZ_0070_m4',
 'TZ_0018_m3',
 'TZ_0302_w4',
 'TZ_0404_m24',
 'TZ_0214_w2',
 'TZ_1113_m6',
 'TZ_1349_m1',
 'TZ_0739_m6',
 'TZ_1761_m1',
 'TZ_0358_w4',
 'TZ_1810_m3',
 'TZ_1897_m12',
 'TZ_0271_m5',
 'TZ_1416_m6',
 'TZ_1329_m18',
 'TZ_0300_w2',
 'TZ_0621_m5',
 'TZ_1204_m1',
 'TZ_0781_m3',
 'TZ_2018_T1_m5',
 'TZ_0340_m5',
 'TZ_0601_m24',
 'TZ_0311_m4',
 'TZ_1820_m6',
 'TZ_1171_m12',
 'TZ_0068_w3',
 'TZ_0079_m18',
 'TZ_0209_w3',
 'TZ_0080_m4',
 'TZ_1782_m18',
 'TZ_1597_m3',
 'TZ_1858_m6',
 'TZ_0059_m12',
 'TZ_0338_m24',
 'TZ_1676_m1',
 'TZ_0264_m6',
 'TZ_0487_m12',
 'TZ_0804_m24',
 'TZ_0403_m6',
 'TZ_1937_m6',
 'TZ_0557_m6',
 'TZ_1805_m24',
 'TZ_0109_w4',
 'TZ_0074_m2',
 'TZ_0288_m18',
 'TZ_1351_m24',
 'TZ_1459_m3',
 'TZ_0610_m1',
 'TZ_1692_m1',
 'TZ_1791_m3',
 'TZ_0116_w4',
 'TZ_2016_T4_m24',
 'TZ_1126_m24',
 'TZ_0271_w4',
 'TZ_0330_m2',
 'TZ_0839_m1',
 'TZ_0248_m5',
 'TZ_0613_m4',
 'TZ_1263_m18',
 'TZ_1848_m6',
 'TZ_0228_m6',
 'TZ_0575_w1',
 'TZ_0883_m12',
 'TZ_1801_m1',
 'TZ_1623_m1',
 'TZ_0049_m15',
 'TZ_2005_m6',
 'TZ_0039_m12',
 'TZ_0325_m18',
 'TZ_1297_m24',
 'TZ_0020_w4',
 'TZ_0212_m6',
 'TZ_1512_m6',
 'TZ_0155_m4',
 'TZ_0426_m10',
 'TZ_0658_m1',
 'TZ_1704_m24',
 'TZ_1735_m6',
 'TZ_0501_m5',
 'TZ_0539_m12',
 'TZ_0549_m3',
 'TZ_0231_w2',
 'TZ_0425_m11',
 'TZ_1879_m18',
 'TZ_0350_m6',
 'TZ_0396_m6',
 'TZ_0038_m15',
 'TZ_1967_m3',
 'TZ_1945_m6',
 'TZ_1539_m1',
 'TZ_0727_m24',
 'TZ_0675_m6',
 'TZ_0105_m4',
 'TZ_0604_m24',
 'TZ_0479_m4',
 'TZ_0190_m15',
 'TZ_0224_m9',
 'TZ_0780_m1',
 'TZ_1429_m6',
 'TZ_0628_m6',
 'TZ_1910_m1',
 'TZ_0045_m3',
 'TZ_2014_m3',
 'TZ_1310_m3',
 'TZ_2018_T1_m4',
 'TZ_0454_m6',
 'TZ_0293_m1',
 'TZ_0200_m6',
 'TZ_0425_m2',
 'TZ_0236_w2',
 'TZ_0530_m24',
 'TZ_1391_m6',
 'TZ_1752_m6',
 'TZ_0219_m12',
 'TZ_0409_m2',
 'TZ_0066_w3',
 'TZ_0156_m5',
 'TZ_2024_T2_m24',
 'TZ_0234_w3',
 'TZ_0252_m2',
 'TZ_0353_m5',
 'TZ_1151_m6',
 'TZ_1191_m6',
 'TZ_0445_m12',
 'TZ_0775_m6',
 'TZ_0601_m3',
 'TZ_0418_m7',
 'TZ_1852_m6',
 'TZ_1410_m3',
 'TZ_1444_m24',
 'TZ_0425_m6',
 'TZ_1574_m1',
 'TZ_0333_m18',
 'TZ_0251_w4',
 'TZ_0451_m12',
 'TZ_0649_m3',
 'TZ_1197_m3',
 'TZ_0100_m15',
 'TZ_0255_m12',
 'TZ_0058_m18',
 'TZ_1270_m18',
 'TZ_0340_m4',
 'TZ_0615_m5',
 'TZ_0415_m1',
 'TZ_1405_m18',
 'TZ_0516_m4',
 'TZ_0909_m24',
 'TZ_1424_m24',
 'TZ_0092_w3',
 'TZ_1751_m24',
 'TZ_1315_m24',
 'TZ_0188_w4',
 'TZ_0228_m9',
 'TZ_0236_m3',
 'TZ_1471_m1',
 'TZ_1824_m1',
 'TZ_1913_m3',
 'TZ_0062_m24',
 'TZ_0103_m4',
 'TZ_0634_m10',
 'TZ_1293_m18',
 'TZ_0390_m3',
 'TZ_0040_m9',
 'TZ_0025_m4',
 'TZ_1856_m24',
 'TZ_1313_m3',
 'TZ_0117_w2',
 'TZ_0090_w4',
 'TZ_1646_m18',
 'TZ_1240_m3',
 'TZ_1311_m12',
 'TZ_1645_m6',
 'TZ_0252_m5',
 'TZ_0304_m5',
 'TZ_0936_m1',
 'TZ_0775_m3',
 'TZ_1175_m18',
 'TZ_1445_m3',
 'TZ_0058_m4',
 'TZ_0235_m4',
 'TZ_0242_w3',
 'TZ_0452_m12',
 'TZ_0532_m12',
 'TZ_0330_m18',
 'TZ_1960_m3',
 'TZ_1412_m24',
 'TZ_0031_m4',
 'TZ_0087_m9',
 'TZ_1716_m3',
 'TZ_0428_m1',
 'TZ_0084_m24',
 'TZ_1799_m12',
 'TZ_1180_m12',
 'TZ_1959_m18',
 'TZ_1305_m12',
 'TZ_1714_m1',
 'TZ_0685_m2',
 'TZ_0095_m2',
 'TZ_0357_w2',
 'TZ_1886_m1',
 'TZ_0634_m1',
 'TZ_2015_m12',
 'TZ_1644_m1',
 'TZ_1273_m3',
 'TZ_1231_m12',
 'TZ_0281_m12',
 'TZ_1914_m6',
 'TZ_1779_m3',
 'TZ_1698_m18',
 'TZ_2002_m6',
 'TZ_0559_m12',
 'TZ_0335_w2',
 'TZ_0137_m3',
 'TZ_0112_w3',
 'TZ_1441_m18',
 'TZ_0834_m6',
 'TZ_1385_m12',
 'TZ_0219_m24',
 'TZ_1252_m1',
 'TZ_0343_m4',
 'TZ_1288_m12',
 'TZ_0747_m6',
 'TZ_2017_T2_m12',
 'TZ_0071_m12',
 'TZ_0473_m5',
 'TZ_0525_m8',
 'TZ_0030_w2',
 'TZ_1875_m6',
 'TZ_1395_m3',
 'TZ_1778_m3',
 'TZ_0065_m3',
 'TZ_0229_m2',
 'TZ_0287_w4',
 'TZ_0592_m3',
 'TZ_0086_m24',
 'TZ_0626_m24',
 'TZ_0701_m12',
 'TZ_0115_m15',
 'TZ_0872_m9',
 'TZ_0543_m8',
 'TZ_0054_m2',
 'TZ_1215_m18',
 'TZ_0540_m24',
 'TZ_1772_m18',
 'TZ_0401_m24',
 'TZ_1151_m3',
 'TZ_0341_w2',
 'TZ_0875_m5',
 'TZ_0671_m7',
 'TZ_2003_m11',
 'TZ_0616_m24',
 'TZ_1909_m3',
 'TZ_0514_m6',
 'TZ_0182_m18',
 'TZ_1845_m6',
 'TZ_0291_m2',
 'TZ_0439_m3',
 'TZ_1245_m18',
 'TZ_1839_m12',
 'TZ_0198_m9',
 'TZ_0221_w3',
 'TZ_0607_m2',
 'TZ_0608_m8',
 'TZ_1560_m12',
 'TZ_0211_m15',
 'TZ_1241_m6',
 'TZ_1360_m12',
 'TZ_0154_m9',
 'TZ_1369_m12',
 'TZ_1984_m3',
 'TZ_0088_m6',
 'TZ_0350_w4',
 'TZ_1405_m24',
 'TZ_0316_m3',
 'TZ_1685_m3',
 'TZ_0280_m2',
 'TZ_0424_m10',
 'TZ_0577_T1_m3',
 'TZ_2016_T4_m15',
 'TZ_0586_w1',
 'TZ_1945_m24',
 'TZ_0053_m5',
 'TZ_0155_m2',
 'TZ_1627_m6',
 'TZ_0702_m7',
 'TZ_0541_m5',
 'TZ_1378_m3',
 'TZ_0475_m24',
 'TZ_2016_T2_m15',
 'TZ_1152_m18',
 'TZ_0275_m24',
 'TZ_0247_m12',
 'TZ_0682_m9',
 'TZ_1756_m3',
 'TZ_1862_m12',
 'TZ_0700_m4',
 'TZ_1355_m6',
 'TZ_0148_w2',
 'TZ_0481_m5',
 'TZ_1733_m1',
 'TZ_1944_m18',
 'TZ_0112_m2',
 'TZ_0399_m24',
 'TZ_0467_m12',
 'TZ_0330_m3',
 'TZ_0411_m10',
 'TZ_0290_m6',
 'TZ_0280_m18',
 'TZ_1547_m18',
 'TZ_2016_T4_m6',
 'TZ_0424_m3',
 'TZ_0017_m4',
 'TZ_0266_m6',
 'TZ_0549_m7',
 'TZ_0111_m3',
 'TZ_0241_m9',
 'TZ_0283_m2',
 'TZ_0281_w3',
 'TZ_0038_w2',
 'TZ_0329_w1',
 'TZ_0320_m6',
 'TZ_0135_m12',
 'TZ_1835_m1',
 'TZ_0036_w1',
 'TZ_0567_m6',
 'TZ_1283_m3',
 'TZ_0512_m6',
 'TZ_0085_m4',
 'TZ_0520_m9',
 'TZ_0581_m9',
 'TZ_1220_m12',
 'TZ_1666_m1',
 'TZ_0365_w3',
 'TZ_2017_T3_m4',
 'TZ_0252_w2',
 'TZ_1481_m12',
 'TZ_0533_m12',
 'TZ_0929_m6',
 'TZ_0283_w2',
 'TZ_0808_m6',
 'TZ_0013_w3',
 'TZ_0363_m3',
 'TZ_1781_m12',
 'TZ_1998_m24',
 'TZ_1149_m1',
 'TZ_0267_m4',
 'TZ_1210_m6',
 'TZ_0472_m8',
 'TZ_2016_T1_w2',
 'TZ_0184_m1',
 'TZ_0352_m2',
 'TZ_1135_m18',
 'TZ_1261_m3',
 'TZ_0291_m15',
 'TZ_0433_m12',
 'TZ_0181_m2',
 'TZ_0339_m18',
 'TZ_1397_m3',
 'TZ_1882_m1',
 'TZ_2024_T2_m4',
 'TZ_1116_m18',
 'TZ_1963_m18',
 'TZ_0009_w2',
 'TZ_1709_m24',
 'TZ_0382_m6',
 'TZ_1076_m3',
 'TZ_1343_m12',
 'TZ_0809_m6',
 'TZ_0469_m10',
 'TZ_0062_m18',
 'TZ_2022_T4_m8',
 'TZ_0635_m24',
 'TZ_1653_m18',
 'TZ_0429_m2',
 'TZ_0256_m5',
 'TZ_0421_m6',
 'TZ_0775_w1',
 'TZ_0819_m24',
 'TZ_0932_m1',
 'TZ_0748_m12',
 'TZ_0231_m9',
 'TZ_0407_m5',
 'TZ_0649_m12',
 'TZ_1132_m3',
 'TZ_1225_m24',
 'TZ_1467_m6',
 'TZ_0228_m12',
 'TZ_2003_m9',
 'TZ_1976_m1',
 'TZ_0003_m9',
 'TZ_0505_m8',
 'TZ_0524_m7',
 'TZ_0746_m24',
 'TZ_0331_m2',
 'TZ_1559_m12',
 'TZ_0662_m3',
 'TZ_1151_m12',
 'TZ_0097_m6',
 'TZ_1467_m18',
 'TZ_1201_m12',
 'TZ_1481_m1',
 'TZ_0320_m9',
 'TZ_0033_m24',
 'TZ_0475_m10',
 'TZ_1520_m24',
 'TZ_0444_m7',
 'TZ_1035_m6',
 'TZ_1861_m3',
 'TZ_1926_m18',
 'TZ_0345_m3',
 'TZ_1515_m3',
 'TZ_1996_m3',
 'TZ_0200_m5',
 'TZ_1514_m1',
 'TZ_0356_m18',
 'TZ_0260_m3',
 'TZ_0220_m18',
 'TZ_0268_m2',
 'TZ_0766_m6',
 'TZ_0328_m15',
 'TZ_0091_m3',
 'TZ_1935_m18',
 'TZ_1673_m6',
 'TZ_0244_m2',
 'TZ_1648_m18',
 'TZ_0510_m9',
 'TZ_0075_w2',
 'TZ_0587_m6',
 'TZ_0061_m15',
 'TZ_0780_m18',
 'TZ_0211_m3',
 'TZ_1219_m3',
 'TZ_0547_m2',
 'TZ_0224_m18',
 'TZ_1845_m18',
 'TZ_1744_m1',
 'TZ_0016_w2',
 'TZ_0080_m3',
 'TZ_0191_m5',
 'TZ_1371_m24',
 'TZ_1381_m12',
 'TZ_0304_m12',
 'TZ_1685_m24',
 'TZ_0276_m18',
 'TZ_0874_m6',
 'TZ_1313_m6',
 'TZ_0872_m10',
 'TZ_0768_m24',
 'TZ_0033_m5',
 'TZ_0371',
 'TZ_1131_m1',
 'TZ_0197_m12',
 'TZ_0077_m9',
 'TZ_1307_m12',
 'TZ_1480_m12',
 'TZ_1551_m24',
 'TZ_0800_m6',
 'TZ_1148_m3',
 'TZ_1841_m24',
 'TZ_2024_T2_m7',
 'TZ_0247_w4',
 'TZ_0769_m9',
 'TZ_1398_m12',
 'TZ_0617_m4',
 'TZ_0469_m9',
 'TZ_0313_m18',
 'TZ_1126_m6',
 'TZ_1358_m12',
 'TZ_0117_m18',
 'TZ_0509_m24',
 'TZ_0016_m1',
 'TZ_0514_m7',
 'TZ_1647_m18',
 'TZ_1774_m18',
 'TZ_1275_m24',
 'TZ_1768_m6',
 'TZ_0590_m24',
 'TZ_1853_m1',
 'TZ_0106_m2',
 'TZ_0477_m9',
 'TZ_0743_m12',
 'TZ_0253_w4',
 'TZ_0016_m18',
 'TZ_1982_m3',
 'TZ_0328_m18',
 'TZ_0430_m5',
 'TZ_0412_m2',
 'TZ_0560_m12',
 'TZ_0176_m6',
 'TZ_0037_m18',
 'TZ_0725_m3',
 'TZ_0415_m9',
 'TZ_1026_m1',
 'TZ_1573_m24',
 'TZ_1609_m18',
 'TZ_1639_m12',
 'TZ_1977_m24',
 'TZ_0207_w3',
 'TZ_0070_m2',
 'TZ_2018_T1_m3',
 'TZ_0105_w3',
 'TZ_1700_m1',
 'TZ_0191_w4',
 'TZ_0005_m9',
 'TZ_0177_w2',
 'TZ_0198_m12',
 'TZ_0249_m5',
 'TZ_0344_m9',
 'TZ_0194_m9',
 'TZ_0147_m24',
 'TZ_1896_m12',
 'TZ_0725_m12',
 'TZ_1738_m12',
 'TZ_1056_m6',
 'TZ_0271_m6',
 'TZ_0865_m6',
 'TZ_1070_m6',
 'TZ_1121_m3',
 'TZ_1795_m6',
 'TZ_1642_m24',
 'TZ_0001_m3',
 'TZ_0071_w3',
 'TZ_0302_m15',
 'TZ_0516_m2',
 'TZ_0330_m12',
 'TZ_0353_m6',
 'TZ_0220_w3',
 'TZ_0054_m12',
 'TZ_0323_w4',
 'TZ_0591_m1',
 'TZ_1304_m24',
 'TZ_0293_m18',
 ...]

In [15]:
pd.DataFrame({'var_names': fea_list}).to_csv(DATA_PATH + 'fea_list.csv')

In [ ]:
# fea_list = pd.read_csv(DATA_PATH + 'fea_list.csv')
# fea_list = fea_list['var_names'].tolist()
fea_list

['TZ_0687_m24',
 'TZ_0091_m9',
 'TZ_1401_m3',
 'TZ_0016_w3',
 'TZ_1641_m6',
 'TZ_0124_m5',
 'TZ_0012_m4',
 'TZ_0971_m12',
 'TZ_1191_m1',
 'TZ_1807_m3',
 'TZ_0149_m18',
 'TZ_0171_m5',
 'TZ_1822_m18',
 'TZ_0214_m2',
 'TZ_1661_m6',
 'TZ_0634_m24',
 'TZ_1486_m6',
 'TZ_1212_m6',
 'TZ_1558_m24',
 'TZ_1717_m12',
 'TZ_0895_m24',
 'TZ_0335_m9',
 'TZ_1977_m6',
 'TZ_1850_m6',
 'TZ_0574_w1',
 'TZ_0136_m6',
 'TZ_1263_m12',
 'TZ_1961_m3',
 'TZ_0323_m24',
 'TZ_0577_T3_m3',
 'TZ_0110_m4',
 'TZ_0605_m9',
 'TZ_1475_m24',
 'TZ_1877_m6',
 'TZ_0115_m24',
 'TZ_0434_m8',
 'TZ_1209_m18',
 'TZ_0155_w3',
 'TZ_1936_m1',
 'TZ_1734_m3',
 'TZ_0318_m15',
 'TZ_1615_m12',
 'TZ_1282_m3',
 'TZ_0416_m4',
 'TZ_0320_w3',
 'TZ_0271_m15',
 'TZ_0255_w4',
 'TZ_0279_w2',
 'TZ_0302_m24',
 'TZ_0049_w4',
 'TZ_1867_m3',
 'TZ_0221_w2',
 'TZ_0239_w4',
 'TZ_0454_m12',
 'TZ_0072_m4',
 'TZ_1508_m3',
 'TZ_0327_m15',
 'TZ_0086_w2',
 'TZ_0133_w4',
 'TZ_0650_m6',
 'TZ_0233_m9',
 'TZ_1515_m12',
 'TZ_1535_m24',
 'TZ_1585_m24',
 'TZ_1628_m18',
 'TZ_1954_m12',
 'TZ_1114_m1',
 'TZ_0287_m6',
 'TZ_1977_m1',
 'TZ_0728_m24',
 'TZ_0020_m5',
 'TZ_0547_m5',
 'TZ_1619_m12',
 'TZ_0503_m12',
 'TZ_0087_m5',
 'TZ_1351_m3',
 'TZ_0635_m12',
 'TZ_1325_m18',
 'TZ_1938_m18',
 'TZ_1300_m18',
 'TZ_0045_m12',
 'TZ_0241_m24',
 'TZ_0206_m3',
 'TZ_1139_m24',
 'TZ_0041_m24',
 'TZ_1947_m1',
 'TZ_1821_m24',
 'TZ_2016_T2_m18',
 'TZ_0209_w4',
 'TZ_0512_m9',
 'TZ_0514_m10',
 'TZ_0685_m12',
 'TZ_0193_m2',
 'TZ_0404_m1',
 'TZ_0541_m1',
 'TZ_1638_m1',
 'TZ_1628_m3',
 'TZ_1525_m1',
 'TZ_0577_T3_m1',
 'TZ_1843_m12',
 'TZ_0219_w2',
 'TZ_1919_m3',
 'TZ_0841_m1',
 'TZ_0692_m1',
 'TZ_0510_m1',
 'TZ_0082_m5',
 'TZ_0220_m9',
 'TZ_1406_m24',
 'TZ_1365_m3',
 'TZ_0637_m12',
 'TZ_0263_w2',
 'TZ_0513_m6',
 'TZ_0316_m1',
 'TZ_0757_m9',
 'TZ_0757_m3',
 'TZ_0010_m9',
 'TZ_0164_m9',
 'TZ_1326_m1',
 'TZ_1616_m24',
 'TZ_1772_m12',
 'TZ_1974_m1',
 'TZ_0148_m3',
 'TZ_0534_m24',
 'TZ_1510_m24',
 'TZ_0239_w3',
 'TZ_0933_m12',
 'TZ_1958_m18',
 'TZ_0210_m2',
 'TZ_2003_m4',
 'TZ_0558_m2',
 'TZ_2018_T2_m2',
 'TZ_1304_m6',
 'TZ_0795_m3',
 'TZ_1981_m18',
 'TZ_0091_w4',
 'TZ_0255_m24',
 'TZ_0522_m24',
 'TZ_0889_m6',
 'TZ_1198_m18',
 'TZ_1262_m12',
 'TZ_1506_m24',
 'TZ_1640_m12',
 'TZ_0128_m18',
 'TZ_0068_m24',
 'TZ_0178_w3',
 'TZ_0133_m18',
 'TZ_0525_m1',
 'TZ_0534_m12',
 'TZ_0809_m3',
 'TZ_1368_m12',
 'TZ_0047_m9',
 'TZ_1224_m12',
 'TZ_0477_m12',
 'TZ_0298_m12',
 'TZ_0045_w3',
 'TZ_1641_m24',
 'TZ_0320_m18',
 'TZ_1155_m6',
 'TZ_1235_m18',
 'TZ_1811_m12',
 'TZ_0345_w2',
 'TZ_0191_m6',
 'TZ_1063_m7',
 'TZ_1260_m12',
 'TZ_0468_m3',
 'TZ_0237_m18',
 'TZ_1520_m1',
 'TZ_0036_m2',
 'TZ_1654_m12',
 'TZ_1877_m18',
 'TZ_0349_w1',
 'TZ_0410_m7',
 'TZ_0411_m8',
 'TZ_0172_w2',
 'TZ_0357_w3',
 'TZ_0654_m7',
 'TZ_1887_m24',
 'TZ_1159_m3',
 'TZ_1918_m18',
 'TZ_0320_m15',
 'TZ_0215_m5',
 'TZ_0124_m1',
 'TZ_1614_m3',
 'TZ_1809_m1',
 'TZ_1664_m18',
 'TZ_0435_m7',
 'TZ_1160_m24',
 'TZ_0045_m24',
 'TZ_0008_m2',
 'TZ_0439_m24',
 'TZ_0197_m9',
 'TZ_1557_m24',
 'TZ_0864_m18',
 'TZ_0006_m6',
 'TZ_2018_T1_m9',
 'TZ_0416_m2',
 'TZ_0101_m15',
 'TZ_0427_m9',
 'TZ_1465_m24',
 'TZ_0340_m3',
 'TZ_0073_m4',
 'TZ_1558_m3',
 'TZ_1619_m1',
 'TZ_1110',
 'TZ_0139_m9',
 'TZ_1364_m18',
 'TZ_0507_m4',
 'TZ_0418_m12',
 'TZ_0296_w4',
 'TZ_1780_m3',
 'TZ_1773_m6',
 'TZ_1455_m18',
 'TZ_0260_w1',
 'TZ_0001_w2',
 'TZ_1349_m18',
 'TZ_1930_m6',
 'TZ_0246_w4',
 'TZ_1315_m12',
 'TZ_0416_m1',
 'TZ_0082_w2',
 'TZ_0093_w2',
 'TZ_0307_w2',
 'TZ_0348_m24',
 'TZ_0052_m1',
 'TZ_0263_w4',
 'TZ_0334_m6',
 'TZ_0194_m2',
 'TZ_0401_m1',
 'TZ_1625_m1',
 'TZ_0091_m18',
 'TZ_0415_m11',
 'TZ_0517_m24',
 'TZ_0682_m2',
 'TZ_1500_m24',
 'TZ_1487_m6',
 'TZ_2022_T1_m7',
 'TZ_0473_m3',
 'TZ_0719_m3',
 'TZ_0026_m15',
 'TZ_0769_w1',
 'TZ_0684_m4',
 'TZ_0844_w1',
 'TZ_0316_w2',
 'TZ_1731_m24',
 'TZ_0137_m9',
 'TZ_0526_m24',
 'TZ_0236_m4',
 'TZ_0518_m4',
 'TZ_0356_m6',
 'TZ_0023_w3',
 'TZ_0721_m3',
 'TZ_0684_m8',
 'TZ_0194_m18',
 'TZ_0304_m24',
 'TZ_1976_m24',
 'TZ_1137_m12',
 'TZ_0768_m1',
 'TZ_0558_m8',
 'TZ_1760_m18',
 'TZ_1444_m12',
 'TZ_0449_m9',
 'TZ_0212_m2',
 'TZ_1595_m12',
 'TZ_1792_m12',
 'TZ_0406_m10',
 'TZ_0124_w4',
 'TZ_1555_m6',
 'TZ_0339_m9',
 'TZ_2024_T3_m4',
 'TZ_0715_m24',
 'TZ_1965_m18',
 'TZ_0607_m3',
 'TZ_1482_m1',
 'TZ_1413_m3',
 'TZ_1899_m24',
 'TZ_1452_m24',
 'TZ_0559_m9',
 'TZ_0857_m1',
 'TZ_1065_m6',
 'TZ_1389_m1',
 'TZ_0140_m24',
 'TZ_0080_m9',
 'TZ_0864_w1',
 'TZ_1390_m1',
 'TZ_0315_m12',
 'TZ_0165_w3',
 'TZ_0042_m9',
 'TZ_1415_m6',
 'TZ_1424_m6',
 'TZ_1972_m6',
 'TZ_0335_w4',
 'TZ_0118_m3',
 'TZ_1269_m12',
 'TZ_2002_m9',
 'TZ_0712_m24',
 'TZ_1879_m12',
 'TZ_0061_w3',
 'TZ_0180_w4',
 'TZ_0292_w1',
 'TZ_0470_m2',
 'TZ_0317_m6',
 'TZ_1034_m1',
 'TZ_0103_w4',
 'TZ_1956_m18',
 'TZ_0255_m4',
 'TZ_0322_w4',
 'TZ_1679_m3',
 'TZ_0414_m10',
 'TZ_1755_m6',
 'TZ_2024_T1_m7',
 'TZ_0092_w4',
 'TZ_2017_T3_m3',
 'TZ_1735_m12',
 'TZ_1765_m24',
 'TZ_0949',
 'TZ_0192_m6',
 'TZ_1906_m18',
 'TZ_0000_w4',
 'TZ_0463_m6',
 'TZ_0181_m5',
 'TZ_1194_m24',
 'TZ_0611_m12',
 'TZ_1448_m1',
 'TZ_0307_m4',
 'TZ_0933_m24',
 'TZ_0792_m6',
 'TZ_0434_m4',
 'TZ_1775_m18',
 'TZ_1864_m6',
 'TZ_0630_m2',
 'TZ_2001_w4',
 'TZ_0615_m11',
 'TZ_0706_m7',
 'TZ_0000_m2',
 'TZ_0874_m1',
 'TZ_1995_m3',
 'TZ_0064_m12',
 'TZ_0750_m24',
 'TZ_1184_m3',
 'TZ_1355_m3',
 'TZ_1593_m3',
 'TZ_0067_m6',
 'TZ_0187_m2',
 'TZ_0477_m6',
 'TZ_1817_m18',
 'TZ_2003_m6',
 'TZ_0336_w2',
 'TZ_0841_m12',
 'TZ_1980_m24',
 'TZ_1366_m24',
 'TZ_0292_m15',
 'TZ_0824_m12',
 'TZ_1380_m24',
 'TZ_1490_m6',
 'TZ_0249_m24',
 'TZ_0329_m9',
 'TZ_1825_m1',
 'TZ_1973_m18',
 'TZ_0021_w4',
 'TZ_0760_m18',
 'TZ_0815_m12',
 'TZ_1667_m24',
 'TZ_0190_m5',
 'TZ_1694_m18',
 'TZ_1905_m24',
 'TZ_0177_m15',
 'TZ_0360_w4',
 'TZ_0258_m6',
 'TZ_0285_w3',
 'TZ_1290_m12',
 'TZ_0000_m1',
 'TZ_0983_m12',
 'TZ_1578_m24',
 'TZ_1748_m24',
 'TZ_0026_m24',
 'TZ_1120_m12',
 'TZ_1946_m1',
 'TZ_0467_m7',
 'TZ_0234_m12',
 'TZ_1216_m12',
 'TZ_0823_m3',
 'TZ_1163_m3',
 'TZ_0029_m12',
 'TZ_0904_m12',
 'TZ_1786_m1',
 'TZ_1197_m12',
 'TZ_0514_m9',
 'TZ_0873_m11',
 'TZ_0287_m18',
 'TZ_2024_T4_m24',
 'TZ_1609_m12',
 'TZ_0275_m6',
 'TZ_0499_m6',
 'TZ_0247_m2',
 'TZ_1342_m6',
 'TZ_0809_m2',
 'TZ_1648_m24',
 'TZ_0287_w2',
 'TZ_1127_m6',
 'TZ_2020_T2_m8',
 'TZ_0392_m2',
 'TZ_1896_m18',
 'TZ_0325_w3',
 'TZ_0147_m18',
 'TZ_0071_w2',
 'TZ_1690_m3',
 'TZ_0158_m2',
 'TZ_1346_m18',
 'TZ_0359_m9',
 'TZ_0861_m6',
 'TZ_1424_m12',
 'TZ_0634_m2',
 'TZ_1995_m18',
 'TZ_0353_m2',
 'TZ_0685_m3',
 'TZ_0441_m7',
 'TZ_0105_m3',
 'TZ_0229_m4',
 'TZ_0328_m12',
 'TZ_0108_m15',
 'TZ_0119_m2',
 'TZ_1387_m3',
 'TZ_0148_m2',
 'TZ_2013_m3',
 'TZ_1857_m1',
 'TZ_0060_m6',
 'TZ_0516_m7',
 'TZ_1868_m6',
 'TZ_0310_m6',
 'TZ_0924_m24',
 'TZ_0272_m6',
 'TZ_1890_m12',
 'TZ_0475_m9',
 'TZ_0140_m4',
 'TZ_0144_m1',
 'TZ_0139_m6',
 'TZ_1322_m6',
 'TZ_0605_m8',
 'TZ_1994_m3',
 'TZ_0006_m5',
 'TZ_0568_m24',
 'TZ_0134_m18',
 'TZ_0520_m4',
 'TZ_0194_m5',
 'TZ_1529_m1',
 'TZ_1148_m12',
 'TZ_1574_m3',
 'TZ_0236_w3',
 'TZ_0676_m8',
 'TZ_0141_w4',
 'TZ_1176_m6',
 'TZ_1908_m1',
 'TZ_0184_m18',
 'TZ_0568_m18',
 'TZ_0906_m12',
 'TZ_1191_m12',
 'TZ_1558_m12',
 'TZ_1323_m18',
 'TZ_0106_m3',
 'TZ_0413_m3',
 'TZ_1646_m6',
 'TZ_1488_m6',
 'TZ_0431_m9',
 'TZ_1271_m6',
 'TZ_0259_m15',
 'TZ_0169_m12',
 'TZ_1138_m24',
 'TZ_0080_m5',
 'TZ_0070_m4',
 'TZ_0018_m3',
 'TZ_0302_w4',
 'TZ_0404_m24',
 'TZ_0214_w2',
 'TZ_1113_m6',
 'TZ_1349_m1',
 'TZ_0739_m6',
 'TZ_1761_m1',
 'TZ_0358_w4',
 'TZ_1810_m3',
 'TZ_1897_m12',
 'TZ_0271_m5',
 'TZ_1416_m6',
 'TZ_1329_m18',
 'TZ_0300_w2',
 'TZ_0621_m5',
 'TZ_1204_m1',
 'TZ_0781_m3',
 'TZ_2018_T1_m5',
 'TZ_0340_m5',
 'TZ_0601_m24',
 'TZ_0311_m4',
 'TZ_1820_m6',
 'TZ_1171_m12',
 'TZ_0068_w3',
 'TZ_0079_m18',
 'TZ_0209_w3',
 'TZ_0080_m4',
 'TZ_1782_m18',
 'TZ_1597_m3',
 'TZ_1858_m6',
 'TZ_0059_m12',
 'TZ_0338_m24',
 'TZ_1676_m1',
 'TZ_0264_m6',
 'TZ_0487_m12',
 'TZ_0804_m24',
 'TZ_0403_m6',
 'TZ_1937_m6',
 'TZ_0557_m6',
 'TZ_1805_m24',
 'TZ_0109_w4',
 'TZ_0074_m2',
 'TZ_0288_m18',
 'TZ_1351_m24',
 'TZ_1459_m3',
 'TZ_0610_m1',
 'TZ_1692_m1',
 'TZ_1791_m3',
 'TZ_0116_w4',
 'TZ_2016_T4_m24',
 'TZ_1126_m24',
 'TZ_0271_w4',
 'TZ_0330_m2',
 'TZ_0839_m1',
 'TZ_0248_m5',
 'TZ_0613_m4',
 'TZ_1263_m18',
 'TZ_1848_m6',
 'TZ_0228_m6',
 'TZ_0575_w1',
 'TZ_0883_m12',
 'TZ_1801_m1',
 'TZ_1623_m1',
 'TZ_0049_m15',
 'TZ_2005_m6',
 'TZ_0039_m12',
 'TZ_0325_m18',
 'TZ_1297_m24',
 'TZ_0020_w4',
 'TZ_0212_m6',
 'TZ_1512_m6',
 'TZ_0155_m4',
 'TZ_0426_m10',
 'TZ_0658_m1',
 'TZ_1704_m24',
 'TZ_1735_m6',
 'TZ_0501_m5',
 'TZ_0539_m12',
 'TZ_0549_m3',
 'TZ_0231_w2',
 'TZ_0425_m11',
 'TZ_1879_m18',
 'TZ_0350_m6',
 'TZ_0396_m6',
 'TZ_0038_m15',
 'TZ_1967_m3',
 'TZ_1945_m6',
 'TZ_1539_m1',
 'TZ_0727_m24',
 'TZ_0675_m6',
 'TZ_0105_m4',
 'TZ_0604_m24',
 'TZ_0479_m4',
 'TZ_0190_m15',
 'TZ_0224_m9',
 'TZ_0780_m1',
 'TZ_1429_m6',
 'TZ_0628_m6',
 'TZ_1910_m1',
 'TZ_0045_m3',
 'TZ_2014_m3',
 'TZ_1310_m3',
 'TZ_2018_T1_m4',
 'TZ_0454_m6',
 'TZ_0293_m1',
 'TZ_0200_m6',
 'TZ_0425_m2',
 'TZ_0236_w2',
 'TZ_0530_m24',
 'TZ_1391_m6',
 'TZ_1752_m6',
 'TZ_0219_m12',
 'TZ_0409_m2',
 'TZ_0066_w3',
 'TZ_0156_m5',
 'TZ_2024_T2_m24',
 'TZ_0234_w3',
 'TZ_0252_m2',
 'TZ_0353_m5',
 'TZ_1151_m6',
 'TZ_1191_m6',
 'TZ_0445_m12',
 'TZ_0775_m6',
 'TZ_0601_m3',
 'TZ_0418_m7',
 'TZ_1852_m6',
 'TZ_1410_m3',
 'TZ_1444_m24',
 'TZ_0425_m6',
 'TZ_1574_m1',
 'TZ_0333_m18',
 'TZ_0251_w4',
 'TZ_0451_m12',
 'TZ_0649_m3',
 'TZ_1197_m3',
 'TZ_0100_m15',
 'TZ_0255_m12',
 'TZ_0058_m18',
 'TZ_1270_m18',
 'TZ_0340_m4',
 'TZ_0615_m5',
 'TZ_0415_m1',
 'TZ_1405_m18',
 'TZ_0516_m4',
 'TZ_0909_m24',
 'TZ_1424_m24',
 'TZ_0092_w3',
 'TZ_1751_m24',
 'TZ_1315_m24',
 'TZ_0188_w4',
 'TZ_0228_m9',
 'TZ_0236_m3',
 'TZ_1471_m1',
 'TZ_1824_m1',
 'TZ_1913_m3',
 'TZ_0062_m24',
 'TZ_0103_m4',
 'TZ_0634_m10',
 'TZ_1293_m18',
 'TZ_0390_m3',
 'TZ_0040_m9',
 'TZ_0025_m4',
 'TZ_1856_m24',
 'TZ_1313_m3',
 'TZ_0117_w2',
 'TZ_0090_w4',
 'TZ_1646_m18',
 'TZ_1240_m3',
 'TZ_1311_m12',
 'TZ_1645_m6',
 'TZ_0252_m5',
 'TZ_0304_m5',
 'TZ_0936_m1',
 'TZ_0775_m3',
 'TZ_1175_m18',
 'TZ_1445_m3',
 'TZ_0058_m4',
 'TZ_0235_m4',
 'TZ_0242_w3',
 'TZ_0452_m12',
 'TZ_0532_m12',
 'TZ_0330_m18',
 'TZ_1960_m3',
 'TZ_1412_m24',
 'TZ_0031_m4',
 'TZ_0087_m9',
 'TZ_1716_m3',
 'TZ_0428_m1',
 'TZ_0084_m24',
 'TZ_1799_m12',
 'TZ_1180_m12',
 'TZ_1959_m18',
 'TZ_1305_m12',
 'TZ_1714_m1',
 'TZ_0685_m2',
 'TZ_0095_m2',
 'TZ_0357_w2',
 'TZ_1886_m1',
 'TZ_0634_m1',
 'TZ_2015_m12',
 'TZ_1644_m1',
 'TZ_1273_m3',
 'TZ_1231_m12',
 'TZ_0281_m12',
 'TZ_1914_m6',
 'TZ_1779_m3',
 'TZ_1698_m18',
 'TZ_2002_m6',
 'TZ_0559_m12',
 'TZ_0335_w2',
 'TZ_0137_m3',
 'TZ_0112_w3',
 'TZ_1441_m18',
 'TZ_0834_m6',
 'TZ_1385_m12',
 'TZ_0219_m24',
 'TZ_1252_m1',
 'TZ_0343_m4',
 'TZ_1288_m12',
 'TZ_0747_m6',
 'TZ_2017_T2_m12',
 'TZ_0071_m12',
 'TZ_0473_m5',
 'TZ_0525_m8',
 'TZ_0030_w2',
 'TZ_1875_m6',
 'TZ_1395_m3',
 'TZ_1778_m3',
 'TZ_0065_m3',
 'TZ_0229_m2',
 'TZ_0287_w4',
 'TZ_0592_m3',
 'TZ_0086_m24',
 'TZ_0626_m24',
 'TZ_0701_m12',
 'TZ_0115_m15',
 'TZ_0872_m9',
 'TZ_0543_m8',
 'TZ_0054_m2',
 'TZ_1215_m18',
 'TZ_0540_m24',
 'TZ_1772_m18',
 'TZ_0401_m24',
 'TZ_1151_m3',
 'TZ_0341_w2',
 'TZ_0875_m5',
 'TZ_0671_m7',
 'TZ_2003_m11',
 'TZ_0616_m24',
 'TZ_1909_m3',
 'TZ_0514_m6',
 'TZ_0182_m18',
 'TZ_1845_m6',
 'TZ_0291_m2',
 'TZ_0439_m3',
 'TZ_1245_m18',
 'TZ_1839_m12',
 'TZ_0198_m9',
 'TZ_0221_w3',
 'TZ_0607_m2',
 'TZ_0608_m8',
 'TZ_1560_m12',
 'TZ_0211_m15',
 'TZ_1241_m6',
 'TZ_1360_m12',
 'TZ_0154_m9',
 'TZ_1369_m12',
 'TZ_1984_m3',
 'TZ_0088_m6',
 'TZ_0350_w4',
 'TZ_1405_m24',
 'TZ_0316_m3',
 'TZ_1685_m3',
 'TZ_0280_m2',
 'TZ_0424_m10',
 'TZ_0577_T1_m3',
 'TZ_2016_T4_m15',
 'TZ_0586_w1',
 'TZ_1945_m24',
 'TZ_0053_m5',
 'TZ_0155_m2',
 'TZ_1627_m6',
 'TZ_0702_m7',
 'TZ_0541_m5',
 'TZ_1378_m3',
 'TZ_0475_m24',
 'TZ_2016_T2_m15',
 'TZ_1152_m18',
 'TZ_0275_m24',
 'TZ_0247_m12',
 'TZ_0682_m9',
 'TZ_1756_m3',
 'TZ_1862_m12',
 'TZ_0700_m4',
 'TZ_1355_m6',
 'TZ_0148_w2',
 'TZ_0481_m5',
 'TZ_1733_m1',
 'TZ_1944_m18',
 'TZ_0112_m2',
 'TZ_0399_m24',
 'TZ_0467_m12',
 'TZ_0330_m3',
 'TZ_0411_m10',
 'TZ_0290_m6',
 'TZ_0280_m18',
 'TZ_1547_m18',
 'TZ_2016_T4_m6',
 'TZ_0424_m3',
 'TZ_0017_m4',
 'TZ_0266_m6',
 'TZ_0549_m7',
 'TZ_0111_m3',
 'TZ_0241_m9',
 'TZ_0283_m2',
 'TZ_0281_w3',
 'TZ_0038_w2',
 'TZ_0329_w1',
 'TZ_0320_m6',
 'TZ_0135_m12',
 'TZ_1835_m1',
 'TZ_0036_w1',
 'TZ_0567_m6',
 'TZ_1283_m3',
 'TZ_0512_m6',
 'TZ_0085_m4',
 'TZ_0520_m9',
 'TZ_0581_m9',
 'TZ_1220_m12',
 'TZ_1666_m1',
 'TZ_0365_w3',
 'TZ_2017_T3_m4',
 'TZ_0252_w2',
 'TZ_1481_m12',
 'TZ_0533_m12',
 'TZ_0929_m6',
 'TZ_0283_w2',
 'TZ_0808_m6',
 'TZ_0013_w3',
 'TZ_0363_m3',
 'TZ_1781_m12',
 'TZ_1998_m24',
 'TZ_1149_m1',
 'TZ_0267_m4',
 'TZ_1210_m6',
 'TZ_0472_m8',
 'TZ_2016_T1_w2',
 'TZ_0184_m1',
 'TZ_0352_m2',
 'TZ_1135_m18',
 'TZ_1261_m3',
 'TZ_0291_m15',
 'TZ_0433_m12',
 'TZ_0181_m2',
 'TZ_0339_m18',
 'TZ_1397_m3',
 'TZ_1882_m1',
 'TZ_2024_T2_m4',
 'TZ_1116_m18',
 'TZ_1963_m18',
 'TZ_0009_w2',
 'TZ_1709_m24',
 'TZ_0382_m6',
 'TZ_1076_m3',
 'TZ_1343_m12',
 'TZ_0809_m6',
 'TZ_0469_m10',
 'TZ_0062_m18',
 'TZ_2022_T4_m8',
 'TZ_0635_m24',
 'TZ_1653_m18',
 'TZ_0429_m2',
 'TZ_0256_m5',
 'TZ_0421_m6',
 'TZ_0775_w1',
 'TZ_0819_m24',
 'TZ_0932_m1',
 'TZ_0748_m12',
 'TZ_0231_m9',
 'TZ_0407_m5',
 'TZ_0649_m12',
 'TZ_1132_m3',
 'TZ_1225_m24',
 'TZ_1467_m6',
 'TZ_0228_m12',
 'TZ_2003_m9',
 'TZ_1976_m1',
 'TZ_0003_m9',
 'TZ_0505_m8',
 'TZ_0524_m7',
 'TZ_0746_m24',
 'TZ_0331_m2',
 'TZ_1559_m12',
 'TZ_0662_m3',
 'TZ_1151_m12',
 'TZ_0097_m6',
 'TZ_1467_m18',
 'TZ_1201_m12',
 'TZ_1481_m1',
 'TZ_0320_m9',
 'TZ_0033_m24',
 'TZ_0475_m10',
 'TZ_1520_m24',
 'TZ_0444_m7',
 'TZ_1035_m6',
 'TZ_1861_m3',
 'TZ_1926_m18',
 'TZ_0345_m3',
 'TZ_1515_m3',
 'TZ_1996_m3',
 'TZ_0200_m5',
 'TZ_1514_m1',
 'TZ_0356_m18',
 'TZ_0260_m3',
 'TZ_0220_m18',
 'TZ_0268_m2',
 'TZ_0766_m6',
 'TZ_0328_m15',
 'TZ_0091_m3',
 'TZ_1935_m18',
 'TZ_1673_m6',
 'TZ_0244_m2',
 'TZ_1648_m18',
 'TZ_0510_m9',
 'TZ_0075_w2',
 'TZ_0587_m6',
 'TZ_0061_m15',
 'TZ_0780_m18',
 'TZ_0211_m3',
 'TZ_1219_m3',
 'TZ_0547_m2',
 'TZ_0224_m18',
 'TZ_1845_m18',
 'TZ_1744_m1',
 'TZ_0016_w2',
 'TZ_0080_m3',
 'TZ_0191_m5',
 'TZ_1371_m24',
 'TZ_1381_m12',
 'TZ_0304_m12',
 'TZ_1685_m24',
 'TZ_0276_m18',
 'TZ_0874_m6',
 'TZ_1313_m6',
 'TZ_0872_m10',
 'TZ_0768_m24',
 'TZ_0033_m5',
 'TZ_0371',
 'TZ_1131_m1',
 'TZ_0197_m12',
 'TZ_0077_m9',
 'TZ_1307_m12',
 'TZ_1480_m12',
 'TZ_1551_m24',
 'TZ_0800_m6',
 'TZ_1148_m3',
 'TZ_1841_m24',
 'TZ_2024_T2_m7',
 'TZ_0247_w4',
 'TZ_0769_m9',
 'TZ_1398_m12',
 'TZ_0617_m4',
 'TZ_0469_m9',
 'TZ_0313_m18',
 'TZ_1126_m6',
 'TZ_1358_m12',
 'TZ_0117_m18',
 'TZ_0509_m24',
 'TZ_0016_m1',
 'TZ_0514_m7',
 'TZ_1647_m18',
 'TZ_1774_m18',
 'TZ_1275_m24',
 'TZ_1768_m6',
 'TZ_0590_m24',
 'TZ_1853_m1',
 'TZ_0106_m2',
 'TZ_0477_m9',
 'TZ_0743_m12',
 'TZ_0253_w4',
 'TZ_0016_m18',
 'TZ_1982_m3',
 'TZ_0328_m18',
 'TZ_0430_m5',
 'TZ_0412_m2',
 'TZ_0560_m12',
 'TZ_0176_m6',
 'TZ_0037_m18',
 'TZ_0725_m3',
 'TZ_0415_m9',
 'TZ_1026_m1',
 'TZ_1573_m24',
 'TZ_1609_m18',
 'TZ_1639_m12',
 'TZ_1977_m24',
 'TZ_0207_w3',
 'TZ_0070_m2',
 'TZ_2018_T1_m3',
 'TZ_0105_w3',
 'TZ_1700_m1',
 'TZ_0191_w4',
 'TZ_0005_m9',
 'TZ_0177_w2',
 'TZ_0198_m12',
 'TZ_0249_m5',
 'TZ_0344_m9',
 'TZ_0194_m9',
 'TZ_0147_m24',
 'TZ_1896_m12',
 'TZ_0725_m12',
 'TZ_1738_m12',
 'TZ_1056_m6',
 'TZ_0271_m6',
 'TZ_0865_m6',
 'TZ_1070_m6',
 'TZ_1121_m3',
 'TZ_1795_m6',
 'TZ_1642_m24',
 'TZ_0001_m3',
 'TZ_0071_w3',
 'TZ_0302_m15',
 'TZ_0516_m2',
 'TZ_0330_m12',
 'TZ_0353_m6',
 'TZ_0220_w3',
 'TZ_0054_m12',
 'TZ_0323_w4',
 'TZ_0591_m1',
 'TZ_1304_m24',
 'TZ_0293_m18',
 ...]

In [17]:
len(fea_list)

15160

In [18]:
import gc
gc.collect()

0

In [19]:
label = pd.read_csv(DATA_OR_PATH + '22_mashang_200w_20240901_20250131.csv', encoding='gbk')

In [20]:
label.head()

,ms_no,mobile_sha256,hs_date,prod_flag,sample_type,target1_mi,target2_mi,stage
0,2618468494244577696,d45735e2015b20c4e8f95645096ae0dac3c9924b9e6b35...,2024-11-21,S,CA,0.0,0.0,test
1,2626479791808743072,dff94df987f14dd7304d25f291729f0b4926adad0df39b...,2024-12-02,S,CA,0.0,0.0,test
2,2582720644667933856,4d4d2304e9265b029491e1fec60e7431d55285fcad426e...,2024-10-03,S,CA,0.0,0.0,train
3,2597987997622206880,f05c3b1367d78a5da0b060110d8724e72664c86dc456a4...,2024-10-24,S,CA,0.0,0.0,train
4,2654564558907114656,d92c8174bf3dd98aa5d11edefef13f24512c53b694071d...,2025-01-10,S,CA,0.0,NaN,test

In [21]:
from new_tools.reduce_mem_usage import reduce_mem_usage_dic 

def chunk_reduce_mem_usage(file_name,columns):
    chunks = pd.read_csv(file_name, usecols=columns, chunksize=200_000)
    chunk_list = []
    for chunk in chunks:
        chunk_reduce_mem = reduce_mem_usage_dic(chunk)
        del chunk
        chunk_list.append(chunk_reduce_mem)
        del chunk_reduce_mem
    df = pd.concat(chunk_list)
    return df

In [22]:
# from new_tools.reduce_mem_usage import reduce_mem_usage_dic 
# from new_tools import iv_report


# with zipfile.ZipFile(DATA_OR_PATH + '驭鉴20250707_LH_deltaV1_result.txt.zip', 'r') as zip_file:
#     file_list = zip_file.namelist()
#     csv_filename = [f for f in file_list if f.endswith('.txt') or f.endswith('.csv')][0]
    
#     with zip_file.open(csv_filename) as csv_file:
#         result_list2 = []
#         result_list1 = []
#         length = 2000
#         for i in range(0,(len(fea_list) // length) + 1):
#             start, end = i * length, min((i + 1) * length, len(fea_list))
#             print(start, ' - ', end)
#             temp_fea_list = fea_list[start:end]

#             temp_df = chunk_reduce_mem_usage(csv_file, columns=['mobile','backPointTime'] + temp_fea_list)
#             temp_df['backPointTime'] = pd.to_datetime(temp_df['backPointTime']).dt.strftime('%Y-%m-%d')
#             temp_df.rename(columns={'backPointTime': 'hs_date','mobile':'mobile_sha256'}, inplace=True)
#             # temp_df_reduce_mem = reduce_mem_usage_dic(temp_df)
#             # del temp_df
#             temp_data_all = pd.merge(label, temp_df, how='left', on=['mobile_sha256', 'hs_date'])
#             del temp_df
#             temp_data_all['weight'] = 1
#             temp_data_all['target'] = 'train'
#             # temp_data_all.loc[(pd.to_datetime(temp_data_all['backDateTime']) >= pd.to_datetime('2024-06-01')) & (temp_data_all['target'] =='train'),'target'] = 'oot'
#             iv_calculator1 = iv_report.IVCalculator(temp_data_all.fillna(-999),label='target1_mi',target='target',keep_list=temp_fea_list, max_leaf_nodes=6, min_samples_leaf=0.05)
#             iv_calculator2 = iv_report.IVCalculator(temp_data_all.fillna(-999),label='target2_mi',target='target',keep_list=temp_fea_list, max_leaf_nodes=6, min_samples_leaf=0.05)
#             del temp_data_all
#             iv_df1 = iv_calculator1.iv_report(use_thread=True,max_workers=20)
#             iv_df2 = iv_calculator2.iv_report(use_thread=True,max_workers=20)
#             # iv_df['dif'] = iv_df['train_iv']/iv_df['oot_iv']
#             result_list1 = result_list1.append(iv_df1)
#             result_list2 = result_list2.append(iv_df2)
#             del iv_calculator1,iv_df1,iv_calculator2,iv_df2
#             gc.collect()

In [23]:
# from new_tools.reduce_mem_usage import reduce_mem_usage_dic 
# from new_tools import iv_report


# with zipfile.ZipFile(DATA_OR_PATH + '驭鉴20250707_LH_deltaV1_result.txt.zip', 'r') as zip_file:
#     file_list = zip_file.namelist()
#     csv_filename = [f for f in file_list if f.endswith('.txt') or f.endswith('.csv')][0]
    
#     with zip_file.open(csv_filename) as csv_file:
#         result_list2 = []
#         result_list1 = []
#         length = 2000
#         for i in range(0,(len(fea_list) // length) + 1):
#             start, end = i * length, min((i + 1) * length, len(fea_list))
#             print(start, ' - ', end)
#             temp_fea_list = fea_list[start:end]

#             temp_df = pd.read_csv(csv_file, usecols=['mobile','backPointTime'] + temp_fea_list)
#             temp_df['backPointTime'] = pd.to_datetime(temp_df['backPointTime']).dt.strftime('%Y-%m-%d')
#             temp_df.rename(columns={'backPointTime': 'hs_date','mobile':'mobile_sha256'}, inplace=True)
#             temp_df_reduce_mem = reduce_mem_usage_dic(temp_df)
#             del temp_df
#             temp_data_all = pd.merge(label, temp_df_reduce_mem, how='left', on=['mobile_sha256', 'hs_date'])
#             del temp_df_reduce_mem
#             temp_data_all['weight'] = 1
#             temp_data_all['target'] = 'train'
#             # temp_data_all.loc[(pd.to_datetime(temp_data_all['backDateTime']) >= pd.to_datetime('2024-06-01')) & (temp_data_all['target'] =='train'),'target'] = 'oot'
#             iv_calculator1 = iv_report.IVCalculator(temp_data_all.fillna(-999),label='target1_mi',target='target',keep_list=temp_fea_list, max_leaf_nodes=6, min_samples_leaf=0.05)
#             iv_calculator2 = iv_report.IVCalculator(temp_data_all.fillna(-999),label='target2_mi',target='target',keep_list=temp_fea_list, max_leaf_nodes=6, min_samples_leaf=0.05)
#             del temp_data_all
#             iv_df1 = iv_calculator1.iv_report(use_thread=True,max_workers=20)
#             iv_df2 = iv_calculator2.iv_report(use_thread=True,max_workers=20)
#             # iv_df['dif'] = iv_df['train_iv']/iv_df['oot_iv']
#             result_list1 = result_list1.append(iv_df1)
#             result_list2 = result_list2.append(iv_df2)
#             del iv_calculator1,iv_df1,iv_calculator2,iv_df2
#             gc.collect()

In [24]:
object_columns

[]

In [ ]:
# 这个版本是最优版本
# from meu_tools.reduce_menu_usage import reduce_menu_usage_dic
# import pandas as pd
# import zipfile
# import gc

# def chunk_func(name):
#     print("===" * 20)
#     print(name)
    
#     # 读取特征列表
#     fea_list = pd.read_csv(DATA_OR_PATH + f'fea_list_{name}.csv')
#     fea_list = fea_list['var_names'].tolist()
    
#     processed_chunks = []
    
#     # 创建标签索引列表
#     label_index_lst = (label['mobile'] + label['backDateTime'].astype(str)).tolist()
#     label_tmp = label.copy()
    
#     print('first file')
    
#     with zipfile.ZipFile(DATA_PATH + f'联合建模样本_12%_2025805_UI_{name}_result.txt.zip', 'r') as zip_file:
#         file_list = zip_file.namelist()
#         csv_filename = [f for f in file_list if f.endswith('.txt') or f.endswith('.csv')][0]
        
#         with zip_file.open(csv_filename) as csv_file:
#             # 读取分块数据
#             chunks = pd.read_csv(csv_file, usecols=["bucketTime"] + fea_list, chunksize=100000)
            
#             for chunk in chunks:
#                 # 处理数据
#                 temp_df = reduce_menu_usage_dic(chunk)
                
#                 # 删除重复项
#                 temp_df.drop_duplicates(['mobile', 'backDateTime'], inplace=True)
#                 print(1)
                
#                 # 转换时间格式
#                 temp_df['backDateTime'] = pd.to_datetime(temp_df['backDateTime']).dt.strftime('%Y-%m-%d')
#                 temp_df.drop(columns=['backDateTime'], inplace=True)
#                 print(2)
                
#                 # 合并标签数据
#                 temp_df = pd.merge(label_tmp, temp_df, how='inner', on=['mobile', 'backDateTime'])
#                 print(3)
                
#                 # 更新标签索引列表
#                 remove_set = set((temp_df['mobile'] + temp_df['backDateTime'].astype(str)).tolist())
#                 label_index_lst = list(set(label_index_lst) - remove_set)
                
#                 # 过滤标签数据
#                 label_tmp = label[
#                     (label['mobile'] + label['backDateTime'].astype(str)).isin(label_index_lst)
#                 ]
#                 print(4)
                
#                 processed_chunks.append(temp_df)
#                 print(f"Processed chunk: {len(processed_chunks)}")
                
#                 # 清理内存
#                 del chunk, temp_df, remove_set
#                 gc.collect()
#     print('second file')
#     with zipfile.ZipFile(DATA_PATH + f'联合建模样本_id_20250827_LL_{name}_result.txt.zip', 'r') as zip_file:
#         file_list = zip_file.namelist()
#         csv_filename = [f for f in file_list if f.endswith('.txt') or f.endswith('.csv')][0]

#         with zip_file.open(csv_filename) as csv_file:
#             chunks = pd.read_csv(csv_file, usecols=['mobile', 'backPointTime'] + fea_list, chunksize=100000)

#             for chunk in chunks:  # 在 with 块内完成迭代
#                 temp_df = reduce_menu_usage_dic(chunk)
#                 temp_df.drop_duplicates(['mobile', 'backPointTime'], inplace=True)
#                 print(1)

#                 # 转换时间格式并重命名列
#                 temp_df['backPointTime'] = pd.to_datetime(temp_df['backPointTime']).dt.strftime('%Y-%m-%d')
#                 temp_df.rename(columns={'backPointTime': 'backDateTime'}, inplace=True)
#                 print(2)

#                 # 合并数据
#                 temp_df = pd.merge(label_tmp, temp_df, how='inner', on=['mobile', 'backDateTime'])
#                 print(3)

#                 # 更新标签索引列表
#                 remove_set = set((temp_df['mobile'] + temp_df['backDateTime']).tolist())
#                 label_index_lst = list(set(label_index_lst) - remove_set)

#                 # 过滤标签数据
#                 label_tmp = label[
#                     (label['mobile'].astype(str) + label['backDateTime'].astype(str)).isin(label_index_lst)
#                 ]
#                 print(4)

#                 processed_chunks.append(temp_df)
#                 print(5)

#                 # 清理内存
#                 del chunk, temp_df, remove_set
#                 gc.collect()

#     # 处理剩余的mobile数据（没有匹配的样本）
#     mobile_num_df = label[pd.isna(label['mobile'])]  # 或者根据实际逻辑调整
#     mobile_num_df[fea_list] = np.nan
#     processed_chunks.append(mobile_num_df)

#     # 合并所有处理后的数据
#     data_all1 = pd.concat(processed_chunks, ignore_index=True)
#     del processed_chunks
#     gc.collect()

#     print(len(label_index_lst))
#     print(data_all1.shape)
    
#     # you can add some error output if you worry about label_temp remain some keys
#     return data_all1,label_index_lst

In [ ]:
from new_tools.reduce_mem_usage import reduce_mem_usage_dic

processed_chunks = []
label_index_lst = (label['mobile'] + label['backPointTime']).to_list()
label_tmp = label.copy()

with zipfile.ZipFile(DATA_OR_PATH + '信飞20251023_d1_t2_z2_deltaV1_result.zip', 'r') as zip_file:
    file_list = zip_file.namelist()
    csv_filename = [f for f in file_list if f.endswith('.txt') or f.endswith('.csv')][0]
    
    with zip_file.open(csv_filename) as csv_file:
        chunks = pd.read_csv(csv_file, usecols=['mobile','backPointTime'] + fea_list + object_columns, chunksize=200_000)
        i = 1
        for chunk in chunks:  # 在 with 块内完成迭代
            temp_df = reduce_mem_usage_dic(chunk)
            temp_df.drop_duplicates(['mobile', 'backPointTime'], inplace=True)
            print(1)
            temp_df['backPointTime'] = pd.to_datetime(temp_df['backPointTime']).dt.strftime('%Y-%m-%d')            
            print(2)
            temp_df = pd.merge(label_tmp, temp_df, how='inner', on=['mobile', 'backPointTime'])
            print(3)
            remove_set = set((temp_df['mobile'] + temp_df['backPointTime']).to_list())
            label_index_lst = list(set(label_index_lst) - remove_set)
            label_tmp = label[(label['mobile'] + label['backPointTime'].astype(str)).isin(label_index_lst)]
            print(4)
            # processed_chunks.append(temp_df)
            temp_df.to_parquet(DATA_PATH + f'chunk_{i}.parquet')
            print(5)
            del chunk, temp_df, remove_set
            gc.collect()
            i = i+1
        mobile_num_df = label[pd.isna(label['mobile'])]  # 或者根据实际逻辑调整
        mobile_num_df[fea_list] = np.nan
        # processed_chunks.append(mobile_num_df)

print(len(label_index_lst))

当前内存占用: 11567.69 MB

100%|██████████| 15162/15162 [00:07<00:00, 2018.42it/s]

最终内存占用: 5784.61 MB
下降了 50.0%
1
2
3
4
5
当前内存占用: 11567.69 MB

100%|██████████| 15162/15162 [00:07<00:00, 1997.47it/s]

最终内存占用: 5784.61 MB
下降了 50.0%
1
2
3
4
5
当前内存占用: 11567.69 MB

100%|██████████| 15162/15162 [00:07<00:00, 2014.59it/s]

最终内存占用: 5784.61 MB
下降了 50.0%
1
2
3
4
5
当前内存占用: 11567.69 MB

100%|██████████| 15162/15162 [00:07<00:00, 2023.38it/s]

最终内存占用: 5784.61 MB
下降了 50.0%
1
2
3
4
5
当前内存占用: 11567.69 MB

100%|██████████| 15162/15162 [00:07<00:00, 2010.86it/s]

最终内存占用: 5784.61 MB
下降了 50.0%
1
2
3
4
5
当前内存占用: 11567.69 MB

100%|██████████| 15162/15162 [00:07<00:00, 2026.76it/s]

最终内存占用: 5784.61 MB
下降了 50.0%
1
2
3
4
5
当前内存占用: 11567.69 MB

100%|██████████| 15162/15162 [00:07<00:00, 1984.79it/s]

最终内存占用: 5784.61 MB
下降了 50.0%
1
2
3
4
5
当前内存占用: 11567.69 MB

100%|██████████| 15162/15162 [00:07<00:00, 1959.06it/s]

最终内存占用: 5784.61 MB
下降了 50.0%
1
2
3
4
5
当前内存占用: 11567.69 MB

100%|██████████| 15162/15162 [00:07<00:00, 1962.92it/s]

最终内存占用: 5784.61 MB
下降了 50.0%
1
2
3
4
5
当前内存占用: 11567.69 MB

100%|██████████| 15162/15162 [00:07<00:00, 1965.99it/s]

最终内存占用: 5784.61 MB
下降了 50.0%
1
2
3
4
5
当前内存占用: 11567.69 MB

100%|██████████| 15162/15162 [00:10<00:00, 1496.91it/s]

最终内存占用: 5784.61 MB
下降了 50.0%
1
2
3
4
5
当前内存占用: 11567.69 MB

100%|██████████| 15162/15162 [00:10<00:00, 1503.39it/s]

最终内存占用: 5784.61 MB
下降了 50.0%
1
2
3
4
5
当前内存占用: 11567.69 MB

100%|██████████| 15162/15162 [00:10<00:00, 1494.67it/s]

最终内存占用: 5784.61 MB
下降了 50.0%
1
2
3
4
5
当前内存占用: 11567.69 MB

100%|██████████| 15162/15162 [00:10<00:00, 1499.24it/s]

最终内存占用: 5784.61 MB
下降了 50.0%
1
2
3
4
5
当前内存占用: 11567.69 MB

100%|██████████| 15162/15162 [00:10<00:00, 1498.81it/s]

最终内存占用: 5784.61 MB
下降了 50.0%
1
2
3
4
5
当前内存占用: 11567.69 MB

100%|██████████| 15162/15162 [00:10<00:00, 1497.20it/s]

最终内存占用: 5784.61 MB
下降了 50.0%
1
2
3
4
5
当前内存占用: 11567.69 MB

100%|██████████| 15162/15162 [00:10<00:00, 1512.60it/s]

最终内存占用: 5784.61 MB
下降了 50.0%
1
2
3
4
5
当前内存占用: 11567.69 MB

100%|██████████| 15162/15162 [00:10<00:00, 1513.87it/s]

最终内存占用: 5784.61 MB
下降了 50.0%
1
2
3
4
5
当前内存占用: 11567.69 MB

100%|██████████| 15162/15162 [00:10<00:00, 1514.12it/s]

最终内存占用: 5784.61 MB
下降了 50.0%
1
2
3
4
5
当前内存占用: 11567.69 MB

100%|██████████| 15162/15162 [00:10<00:00, 1512.45it/s]

最终内存占用: 5784.61 MB
下降了 50.0%
1
2
3
4
5

In [ ]:
data_all1 = pd.concat(processed_chunks, ignore_index=True)
del processed_chunks
gc.collect()
print(data_all1.shape)

In [ ]:
label_index_lst

[]

In [24]:
data_all1.shape

(2000578, 1008)

In [25]:
data_all1.head()

,ms_no,mobile_sha256,hs_date,prod_flag,sample_type,target1_mi,target2_mi,stage,TZ_0000_m1,TZ_0000_m12,...,TZ_0073_m2,TZ_0073_m24,TZ_0073_m3,TZ_0073_m4,TZ_0073_m5,TZ_0073_m6,TZ_0073_m9,TZ_0073_w2,TZ_0073_w3,TZ_0073_w4
0,2618468494244577696,d45735e2015b20c4e8f95645096ae0dac3c9924b9e6b35...,2024-11-21,S,CA,0.0,0.0,test,0.0,0.0,...,0.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0
1,2626479791808743072,dff94df987f14dd7304d25f291729f0b4926adad0df39b...,2024-12-02,S,CA,0.0,0.0,test,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2582720644667933856,4d4d2304e9265b029491e1fec60e7431d55285fcad426e...,2024-10-03,S,CA,0.0,0.0,train,0.0,8.0,...,0.0,3.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0
3,2597987997622206880,f05c3b1367d78a5da0b060110d8724e72664c86dc456a4...,2024-10-24,S,CA,0.0,0.0,train,0.0,4.0,...,3.0,3.0,3.0,3.0,3.0,3.0,3.0,0.0,0.0,1.0
4,2654564558907114656,d92c8174bf3dd98aa5d11edefef13f24512c53b694071d...,2025-01-10,S,CA,0.0,NaN,test,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [26]:
data_all1['ms_no'] = data_all1['ms_no'].astype('str')

In [27]:
data_all1.to_parquet(DATA_PATH + 'data_all1.parquet')

In [28]:
# data_all1 = pd.read_parquet(DATA_PATH + 'data_all1.parquet')

In [29]:
# data_all1[object_columns] = data_all1[object_columns].apply(
#     lambda x: x.astype('category').cat.codes.replace({-1: np.nan}).astype('float64')
# )

In [30]:
data_all1[object_columns]

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]

[2000578 rows x 0 columns]

In [31]:
# data_all1[object_columns].count()

In [32]:
data_all1[data_all1['sample_type'] == 'CA'].to_parquet(DATA_PATH + 'data_all1_CA.parquet')

In [33]:
gc.collect()

0

In [34]:
data_all1[data_all1['sample_type'] == 'CR'].to_parquet(DATA_PATH + 'data_all1_CR.parquet')

In [35]:
%reset -f