In [1]:
%reset -f

In [2]:
debug = False

In [3]:
import os,sys
current_path = os.getcwd()

In [4]:
name = current_path.split('\\')[-1].split('_')
data = name[0]

In [5]:
%reload_ext autoreload
%autoreload 2

import sys
sys.path.append("D:/work/scorecard") 
base_path = 'D:/work/06.std_product/wxjk_test/'
 
FILE_PATH = base_path + f'{data}/file/'
DATA_PATH = base_path + f'{data}/data/'
TMP_PATH  = base_path + f'{data}/tmp/'
DATA_OR_PATH = base_path + f'data_or/'

import os
import gc
import pandas as pd 
import numpy as np  
import math  
import zipfile
import matplotlib.pyplot as plt
import copy
import seaborn as sns
from pylab import mpl
from ScoreCard.creat_report import Report
mpl.rcParams['font.sans-serif'] = ['SimHei']
mpl.rcParams['axes.unicode_minus'] = False  

isExists=os.path.exists(FILE_PATH)
if not isExists:
    os.makedirs(FILE_PATH) 
    
isExists=os.path.exists(DATA_PATH)
if not isExists:
    os.makedirs(DATA_PATH)

isExists=os.path.exists(TMP_PATH)
if not isExists:
    os.makedirs(TMP_PATH)  

import warnings
warnings.filterwarnings("ignore")

## 1. feature 结构查看

In [6]:
if data == 'delta':
    dataV = data + 'V1'
else:
    dataV = data + 'V2'

In [7]:
the_data_path = DATA_OR_PATH + f'维信20251106_d1_t2_z2_{dataV}_result.zip'
parquet_zip_path= the_data_path.replace(".zip", ".parquet")

In [ ]:
with zipfile.ZipFile(the_data_path, 'r') as zip_file:
    file_list = zip_file.namelist()
    print("压缩包内文件:", file_list)
    csv_filename = [f for f in file_list if f.endswith('.txt') or f.endswith('.csv')][0]
    with zip_file.open(csv_filename) as csv_file:
        data_tmp = pd.read_csv(csv_file, nrows=100)

压缩包内文件: ['╬¼╨┼20251106_d1_t2_z2_deltaV1_result.txt']

In [9]:
data_tmp

,name,mobile,idCard,reqToken,backPointTime,TZ_0000_m1,TZ_0000_m12,TZ_0000_m15,TZ_0000_m18,TZ_0000_m2,...,TZ_2024_T4_m4,TZ_2024_T4_m5,TZ_2024_T4_m6,TZ_2024_T4_m7,TZ_2024_T4_m8,TZ_2024_T4_m9,TZ_2025_T1_m24,TZ_2025_T2_m24,TZ_2025_T3_m24,TZ_2025_T4_m24
0,729599939935314ad7796963a4ac81f4,6afc7f594e81633d58bf091562d0ae43,8b3a71e6517de7391e5f2fc1f20eb778,1,2025/1/22,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,d74b62337c90fb492cf1d27a35500e79,02947e5fb54d2203bf03f2a13f13d92e,58d6eedcf45eebfed22b506a03e8feb7,2,2025/9/20,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0deee47fffaa56cab2b085c3b173d2eb,642f657575362a912b6ce80606b79cf9,d3f71f697b5f0a8cbde4772e7bb18f06,3,2024/11/29,0,1,1,1,0,...,0,0,0,0,0,0,0,0,0,0
3,8dd18d524f30529d8f0910dbd2d015af,71d234b2a1b0ee10fb36229d8575f6c9,8f5161712dc8c618598ad4ec0632036a,4,2024/12/26,0,3,3,3,0,...,0,0,0,0,0,0,0,0,0,0
4,2ecc12f6df07e5d0b982592df0c0924f,eb2d382e9f02be6e4d24498d324a64d1,98cfd4e53010fcede77dcde9bd7787be,5,2024/10/22,0,1,1,1,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,f712d041d97638c1d95fe8fbcf9b3fda,680bab1a2eded00535fb9b3425fe6f6a,0f7ca5a6505d58de44b97e718782984e,96,2024/11/23,0,1,1,1,0,...,0,0,0,0,0,0,0,0,0,0
96,f7364b06e9eba56c09250b6c4a8a5956,4197b7e68c21092d731f501572e88027,2ab88ae7397ed1bed5c244a7a815db57,97,2024/12/7,0,9,9,9,0,...,0,0,0,0,0,0,0,0,0,0
97,0558e2cf3edbcf1dc3f57867ca381024,11b38b7ba131789680d336e5f28b95c6,9bd6cadc189e9e81d0dcffaff9555041,98,2024/12/23,0,5,5,5,1,...,0,0,0,0,0,0,0,0,0,0
98,fae976114952812aec007041aed866e8,640cd560eb0fd51bdf56eb3481bd1fff,a93ad3f9bb204037870d2aff28b0c53b,99,2024/11/29,0,2,2,2,1,...,0,0,0,0,0,0,0,0,0,0
99,84578a67d5794f050e3ab3ccd785e6cb,cd5c80107de1593146db1b0fe760beee,c1bbde9def630e969999ff8a5cbdf600,100,2024/11/2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [10]:
data_tmp.select_dtypes('O')

,name,mobile,idCard,backPointTime
0,729599939935314ad7796963a4ac81f4,6afc7f594e81633d58bf091562d0ae43,8b3a71e6517de7391e5f2fc1f20eb778,2025/1/22
1,d74b62337c90fb492cf1d27a35500e79,02947e5fb54d2203bf03f2a13f13d92e,58d6eedcf45eebfed22b506a03e8feb7,2025/9/20
2,0deee47fffaa56cab2b085c3b173d2eb,642f657575362a912b6ce80606b79cf9,d3f71f697b5f0a8cbde4772e7bb18f06,2024/11/29
3,8dd18d524f30529d8f0910dbd2d015af,71d234b2a1b0ee10fb36229d8575f6c9,8f5161712dc8c618598ad4ec0632036a,2024/12/26
4,2ecc12f6df07e5d0b982592df0c0924f,eb2d382e9f02be6e4d24498d324a64d1,98cfd4e53010fcede77dcde9bd7787be,2024/10/22
...,...,...,...,...
95,f712d041d97638c1d95fe8fbcf9b3fda,680bab1a2eded00535fb9b3425fe6f6a,0f7ca5a6505d58de44b97e718782984e,2024/11/23
96,f7364b06e9eba56c09250b6c4a8a5956,4197b7e68c21092d731f501572e88027,2ab88ae7397ed1bed5c244a7a815db57,2024/12/7
97,0558e2cf3edbcf1dc3f57867ca381024,11b38b7ba131789680d336e5f28b95c6,9bd6cadc189e9e81d0dcffaff9555041,2024/12/23
98,fae976114952812aec007041aed866e8,640cd560eb0fd51bdf56eb3481bd1fff,a93ad3f9bb204037870d2aff28b0c53b,2024/11/29
99,84578a67d5794f050e3ab3ccd785e6cb,cd5c80107de1593146db1b0fe760beee,c1bbde9def630e969999ff8a5cbdf600,2024/11/2

In [11]:
object_columns = []
for column in data_tmp.select_dtypes('O').columns:
    if column not in ['name','idCard','mobile','reqToken','backPointTime','version']:
        print(column)
        object_columns.append(column)

In [12]:
fea_list =list(data_tmp.columns[5:])

In [13]:
fea_list

['TZ_0000_m1',
 'TZ_0000_m12',
 'TZ_0000_m15',
 'TZ_0000_m18',
 'TZ_0000_m2',
 'TZ_0000_m24',
 'TZ_0000_m3',
 'TZ_0000_m4',
 'TZ_0000_m5',
 'TZ_0000_m6',
 'TZ_0000_m9',
 'TZ_0000_w1',
 'TZ_0000_w2',
 'TZ_0000_w3',
 'TZ_0000_w4',
 'TZ_0001_m12',
 'TZ_0001_m15',
 'TZ_0001_m18',
 'TZ_0001_m2',
 'TZ_0001_m24',
 'TZ_0001_m3',
 'TZ_0001_m4',
 'TZ_0001_m5',
 'TZ_0001_m6',
 'TZ_0001_m9',
 'TZ_0001_w2',
 'TZ_0001_w3',
 'TZ_0001_w4',
 'TZ_0002_m12',
 'TZ_0002_m15',
 'TZ_0002_m18',
 'TZ_0002_m2',
 'TZ_0002_m24',
 'TZ_0002_m3',
 'TZ_0002_m4',
 'TZ_0002_m5',
 'TZ_0002_m6',
 'TZ_0002_m9',
 'TZ_0002_w2',
 'TZ_0002_w3',
 'TZ_0002_w4',
 'TZ_0003_m12',
 'TZ_0003_m15',
 'TZ_0003_m18',
 'TZ_0003_m2',
 'TZ_0003_m24',
 'TZ_0003_m3',
 'TZ_0003_m4',
 'TZ_0003_m5',
 'TZ_0003_m6',
 'TZ_0003_m9',
 'TZ_0003_w2',
 'TZ_0003_w3',
 'TZ_0003_w4',
 'TZ_0004_m1',
 'TZ_0004_m12',
 'TZ_0004_m15',
 'TZ_0004_m18',
 'TZ_0004_m2',
 'TZ_0004_m24',
 'TZ_0004_m3',
 'TZ_0004_m4',
 'TZ_0004_m5',
 'TZ_0004_m6',
 'TZ_0004_m9',
 'TZ_0004_w1',
 'TZ_0004_w2',
 'TZ_0004_w3',
 'TZ_0004_w4',
 'TZ_0005_m12',
 'TZ_0005_m15',
 'TZ_0005_m18',
 'TZ_0005_m2',
 'TZ_0005_m24',
 'TZ_0005_m3',
 'TZ_0005_m4',
 'TZ_0005_m5',
 'TZ_0005_m6',
 'TZ_0005_m9',
 'TZ_0005_w2',
 'TZ_0005_w3',
 'TZ_0005_w4',
 'TZ_0006_m12',
 'TZ_0006_m15',
 'TZ_0006_m18',
 'TZ_0006_m2',
 'TZ_0006_m24',
 'TZ_0006_m3',
 'TZ_0006_m4',
 'TZ_0006_m5',
 'TZ_0006_m6',
 'TZ_0006_m9',
 'TZ_0006_w2',
 'TZ_0006_w3',
 'TZ_0006_w4',
 'TZ_0007_m12',
 'TZ_0007_m15',
 'TZ_0007_m18',
 'TZ_0007_m2',
 'TZ_0007_m24',
 'TZ_0007_m3',
 'TZ_0007_m4',
 'TZ_0007_m5',
 'TZ_0007_m6',
 'TZ_0007_m9',
 'TZ_0007_w2',
 'TZ_0007_w3',
 'TZ_0007_w4',
 'TZ_0008_m1',
 'TZ_0008_m12',
 'TZ_0008_m15',
 'TZ_0008_m18',
 'TZ_0008_m2',
 'TZ_0008_m24',
 'TZ_0008_m3',
 'TZ_0008_m4',
 'TZ_0008_m5',
 'TZ_0008_m6',
 'TZ_0008_m9',
 'TZ_0008_w1',
 'TZ_0008_w2',
 'TZ_0008_w3',
 'TZ_0008_w4',
 'TZ_0009_m12',
 'TZ_0009_m15',
 'TZ_0009_m18',
 'TZ_0009_m2',
 'TZ_0009_m24',
 'TZ_0009_m3',
 'TZ_0009_m4',
 'TZ_0009_m5',
 'TZ_0009_m6',
 'TZ_0009_m9',
 'TZ_0009_w2',
 'TZ_0009_w3',
 'TZ_0009_w4',
 'TZ_0010_m12',
 'TZ_0010_m15',
 'TZ_0010_m18',
 'TZ_0010_m2',
 'TZ_0010_m24',
 'TZ_0010_m3',
 'TZ_0010_m4',
 'TZ_0010_m5',
 'TZ_0010_m6',
 'TZ_0010_m9',
 'TZ_0010_w2',
 'TZ_0010_w3',
 'TZ_0010_w4',
 'TZ_0011_m12',
 'TZ_0011_m15',
 'TZ_0011_m18',
 'TZ_0011_m2',
 'TZ_0011_m24',
 'TZ_0011_m3',
 'TZ_0011_m4',
 'TZ_0011_m5',
 'TZ_0011_m6',
 'TZ_0011_m9',
 'TZ_0011_w2',
 'TZ_0011_w3',
 'TZ_0011_w4',
 'TZ_0012_m1',
 'TZ_0012_m12',
 'TZ_0012_m15',
 'TZ_0012_m18',
 'TZ_0012_m2',
 'TZ_0012_m24',
 'TZ_0012_m3',
 'TZ_0012_m4',
 'TZ_0012_m5',
 'TZ_0012_m6',
 'TZ_0012_m9',
 'TZ_0012_w1',
 'TZ_0012_w2',
 'TZ_0012_w3',
 'TZ_0012_w4',
 'TZ_0013_m12',
 'TZ_0013_m15',
 'TZ_0013_m18',
 'TZ_0013_m2',
 'TZ_0013_m24',
 'TZ_0013_m3',
 'TZ_0013_m4',
 'TZ_0013_m5',
 'TZ_0013_m6',
 'TZ_0013_m9',
 'TZ_0013_w2',
 'TZ_0013_w3',
 'TZ_0013_w4',
 'TZ_0014_m12',
 'TZ_0014_m15',
 'TZ_0014_m18',
 'TZ_0014_m2',
 'TZ_0014_m24',
 'TZ_0014_m3',
 'TZ_0014_m4',
 'TZ_0014_m5',
 'TZ_0014_m6',
 'TZ_0014_m9',
 'TZ_0014_w2',
 'TZ_0014_w3',
 'TZ_0014_w4',
 'TZ_0015_m12',
 'TZ_0015_m15',
 'TZ_0015_m18',
 'TZ_0015_m2',
 'TZ_0015_m24',
 'TZ_0015_m3',
 'TZ_0015_m4',
 'TZ_0015_m5',
 'TZ_0015_m6',
 'TZ_0015_m9',
 'TZ_0015_w2',
 'TZ_0015_w3',
 'TZ_0015_w4',
 'TZ_0016_m1',
 'TZ_0016_m12',
 'TZ_0016_m15',
 'TZ_0016_m18',
 'TZ_0016_m2',
 'TZ_0016_m24',
 'TZ_0016_m3',
 'TZ_0016_m4',
 'TZ_0016_m5',
 'TZ_0016_m6',
 'TZ_0016_m9',
 'TZ_0016_w1',
 'TZ_0016_w2',
 'TZ_0016_w3',
 'TZ_0016_w4',
 'TZ_0017_m12',
 'TZ_0017_m15',
 'TZ_0017_m18',
 'TZ_0017_m2',
 'TZ_0017_m24',
 'TZ_0017_m3',
 'TZ_0017_m4',
 'TZ_0017_m5',
 'TZ_0017_m6',
 'TZ_0017_m9',
 'TZ_0017_w2',
 'TZ_0017_w3',
 'TZ_0017_w4',
 'TZ_0018_m12',
 'TZ_0018_m15',
 'TZ_0018_m18',
 'TZ_0018_m2',
 'TZ_0018_m24',
 'TZ_0018_m3',
 'TZ_0018_m4',
 'TZ_0018_m5',
 'TZ_0018_m6',
 'TZ_0018_m9',
 'TZ_0018_w2',
 'TZ_0018_w3',
 'TZ_0018_w4',
 'TZ_0019_m12',
 'TZ_0019_m15',
 'TZ_0019_m18',
 'TZ_0019_m2',
 'TZ_0019_m24',
 'TZ_0019_m3',
 'TZ_0019_m4',
 'TZ_0019_m5',
 'TZ_0019_m6',
 'TZ_0019_m9',
 'TZ_0019_w2',
 'TZ_0019_w3',
 'TZ_0019_w4',
 'TZ_0020_m1',
 'TZ_0020_m12',
 'TZ_0020_m15',
 'TZ_0020_m18',
 'TZ_0020_m2',
 'TZ_0020_m24',
 'TZ_0020_m3',
 'TZ_0020_m4',
 'TZ_0020_m5',
 'TZ_0020_m6',
 'TZ_0020_m9',
 'TZ_0020_w1',
 'TZ_0020_w2',
 'TZ_0020_w3',
 'TZ_0020_w4',
 'TZ_0021_m12',
 'TZ_0021_m15',
 'TZ_0021_m18',
 'TZ_0021_m2',
 'TZ_0021_m24',
 'TZ_0021_m3',
 'TZ_0021_m4',
 'TZ_0021_m5',
 'TZ_0021_m6',
 'TZ_0021_m9',
 'TZ_0021_w2',
 'TZ_0021_w3',
 'TZ_0021_w4',
 'TZ_0022_m12',
 'TZ_0022_m15',
 'TZ_0022_m18',
 'TZ_0022_m2',
 'TZ_0022_m24',
 'TZ_0022_m3',
 'TZ_0022_m4',
 'TZ_0022_m5',
 'TZ_0022_m6',
 'TZ_0022_m9',
 'TZ_0022_w2',
 'TZ_0022_w3',
 'TZ_0022_w4',
 'TZ_0023_m12',
 'TZ_0023_m15',
 'TZ_0023_m18',
 'TZ_0023_m2',
 'TZ_0023_m24',
 'TZ_0023_m3',
 'TZ_0023_m4',
 'TZ_0023_m5',
 'TZ_0023_m6',
 'TZ_0023_m9',
 'TZ_0023_w2',
 'TZ_0023_w3',
 'TZ_0023_w4',
 'TZ_0024_m1',
 'TZ_0024_m12',
 'TZ_0024_m15',
 'TZ_0024_m18',
 'TZ_0024_m2',
 'TZ_0024_m24',
 'TZ_0024_m3',
 'TZ_0024_m4',
 'TZ_0024_m5',
 'TZ_0024_m6',
 'TZ_0024_m9',
 'TZ_0024_w1',
 'TZ_0024_w2',
 'TZ_0024_w3',
 'TZ_0024_w4',
 'TZ_0025_m12',
 'TZ_0025_m15',
 'TZ_0025_m18',
 'TZ_0025_m2',
 'TZ_0025_m24',
 'TZ_0025_m3',
 'TZ_0025_m4',
 'TZ_0025_m5',
 'TZ_0025_m6',
 'TZ_0025_m9',
 'TZ_0025_w2',
 'TZ_0025_w3',
 'TZ_0025_w4',
 'TZ_0026_m12',
 'TZ_0026_m15',
 'TZ_0026_m18',
 'TZ_0026_m2',
 'TZ_0026_m24',
 'TZ_0026_m3',
 'TZ_0026_m4',
 'TZ_0026_m5',
 'TZ_0026_m6',
 'TZ_0026_m9',
 'TZ_0026_w2',
 'TZ_0026_w3',
 'TZ_0026_w4',
 'TZ_0027_m12',
 'TZ_0027_m15',
 'TZ_0027_m18',
 'TZ_0027_m2',
 'TZ_0027_m24',
 'TZ_0027_m3',
 'TZ_0027_m4',
 'TZ_0027_m5',
 'TZ_0027_m6',
 'TZ_0027_m9',
 'TZ_0027_w2',
 'TZ_0027_w3',
 'TZ_0027_w4',
 'TZ_0028_m1',
 'TZ_0028_m12',
 'TZ_0028_m15',
 'TZ_0028_m18',
 'TZ_0028_m2',
 'TZ_0028_m24',
 'TZ_0028_m3',
 'TZ_0028_m4',
 'TZ_0028_m5',
 'TZ_0028_m6',
 'TZ_0028_m9',
 'TZ_0028_w1',
 'TZ_0028_w2',
 'TZ_0028_w3',
 'TZ_0028_w4',
 'TZ_0029_m12',
 'TZ_0029_m15',
 'TZ_0029_m18',
 'TZ_0029_m2',
 'TZ_0029_m24',
 'TZ_0029_m3',
 'TZ_0029_m4',
 'TZ_0029_m5',
 'TZ_0029_m6',
 'TZ_0029_m9',
 'TZ_0029_w2',
 'TZ_0029_w3',
 'TZ_0029_w4',
 'TZ_0030_m12',
 'TZ_0030_m15',
 'TZ_0030_m18',
 'TZ_0030_m2',
 'TZ_0030_m24',
 'TZ_0030_m3',
 'TZ_0030_m4',
 'TZ_0030_m5',
 'TZ_0030_m6',
 'TZ_0030_m9',
 'TZ_0030_w2',
 'TZ_0030_w3',
 'TZ_0030_w4',
 'TZ_0031_m12',
 'TZ_0031_m15',
 'TZ_0031_m18',
 'TZ_0031_m2',
 'TZ_0031_m24',
 'TZ_0031_m3',
 'TZ_0031_m4',
 'TZ_0031_m5',
 'TZ_0031_m6',
 'TZ_0031_m9',
 'TZ_0031_w2',
 'TZ_0031_w3',
 'TZ_0031_w4',
 'TZ_0032_m1',
 'TZ_0032_m12',
 'TZ_0032_m15',
 'TZ_0032_m18',
 'TZ_0032_m2',
 'TZ_0032_m24',
 'TZ_0032_m3',
 'TZ_0032_m4',
 'TZ_0032_m5',
 'TZ_0032_m6',
 'TZ_0032_m9',
 'TZ_0032_w1',
 'TZ_0032_w2',
 'TZ_0032_w3',
 'TZ_0032_w4',
 'TZ_0033_m12',
 'TZ_0033_m15',
 'TZ_0033_m18',
 'TZ_0033_m2',
 'TZ_0033_m24',
 'TZ_0033_m3',
 'TZ_0033_m4',
 'TZ_0033_m5',
 'TZ_0033_m6',
 'TZ_0033_m9',
 'TZ_0033_w2',
 'TZ_0033_w3',
 'TZ_0033_w4',
 'TZ_0034_m12',
 'TZ_0034_m15',
 'TZ_0034_m18',
 'TZ_0034_m2',
 'TZ_0034_m24',
 'TZ_0034_m3',
 'TZ_0034_m4',
 'TZ_0034_m5',
 'TZ_0034_m6',
 'TZ_0034_m9',
 'TZ_0034_w2',
 'TZ_0034_w3',
 'TZ_0034_w4',
 'TZ_0035_m12',
 'TZ_0035_m15',
 'TZ_0035_m18',
 'TZ_0035_m2',
 'TZ_0035_m24',
 'TZ_0035_m3',
 'TZ_0035_m4',
 'TZ_0035_m5',
 'TZ_0035_m6',
 'TZ_0035_m9',
 'TZ_0035_w2',
 'TZ_0035_w3',
 'TZ_0035_w4',
 'TZ_0036_m1',
 'TZ_0036_m12',
 'TZ_0036_m15',
 'TZ_0036_m18',
 'TZ_0036_m2',
 'TZ_0036_m24',
 'TZ_0036_m3',
 'TZ_0036_m4',
 'TZ_0036_m5',
 'TZ_0036_m6',
 'TZ_0036_m9',
 'TZ_0036_w1',
 'TZ_0036_w2',
 'TZ_0036_w3',
 'TZ_0036_w4',
 'TZ_0037_m12',
 'TZ_0037_m15',
 'TZ_0037_m18',
 'TZ_0037_m2',
 'TZ_0037_m24',
 'TZ_0037_m3',
 'TZ_0037_m4',
 'TZ_0037_m5',
 'TZ_0037_m6',
 'TZ_0037_m9',
 'TZ_0037_w2',
 'TZ_0037_w3',
 'TZ_0037_w4',
 'TZ_0038_m12',
 'TZ_0038_m15',
 'TZ_0038_m18',
 'TZ_0038_m2',
 'TZ_0038_m24',
 'TZ_0038_m3',
 'TZ_0038_m4',
 'TZ_0038_m5',
 'TZ_0038_m6',
 'TZ_0038_m9',
 'TZ_0038_w2',
 'TZ_0038_w3',
 'TZ_0038_w4',
 'TZ_0039_m12',
 'TZ_0039_m15',
 'TZ_0039_m18',
 'TZ_0039_m2',
 'TZ_0039_m24',
 'TZ_0039_m3',
 'TZ_0039_m4',
 'TZ_0039_m5',
 'TZ_0039_m6',
 'TZ_0039_m9',
 'TZ_0039_w2',
 'TZ_0039_w3',
 'TZ_0039_w4',
 'TZ_0040_m1',
 'TZ_0040_m12',
 'TZ_0040_m15',
 'TZ_0040_m18',
 'TZ_0040_m2',
 'TZ_0040_m24',
 'TZ_0040_m3',
 'TZ_0040_m4',
 'TZ_0040_m5',
 'TZ_0040_m6',
 'TZ_0040_m9',
 'TZ_0040_w1',
 'TZ_0040_w2',
 'TZ_0040_w3',
 'TZ_0040_w4',
 'TZ_0041_m12',
 'TZ_0041_m15',
 'TZ_0041_m18',
 'TZ_0041_m2',
 'TZ_0041_m24',
 'TZ_0041_m3',
 'TZ_0041_m4',
 'TZ_0041_m5',
 'TZ_0041_m6',
 'TZ_0041_m9',
 'TZ_0041_w2',
 'TZ_0041_w3',
 'TZ_0041_w4',
 'TZ_0042_m12',
 'TZ_0042_m15',
 'TZ_0042_m18',
 'TZ_0042_m2',
 'TZ_0042_m24',
 'TZ_0042_m3',
 'TZ_0042_m4',
 'TZ_0042_m5',
 'TZ_0042_m6',
 'TZ_0042_m9',
 'TZ_0042_w2',
 'TZ_0042_w3',
 'TZ_0042_w4',
 'TZ_0043_m12',
 'TZ_0043_m15',
 'TZ_0043_m18',
 'TZ_0043_m2',
 'TZ_0043_m24',
 'TZ_0043_m3',
 'TZ_0043_m4',
 'TZ_0043_m5',
 'TZ_0043_m6',
 'TZ_0043_m9',
 'TZ_0043_w2',
 'TZ_0043_w3',
 'TZ_0043_w4',
 'TZ_0044_m1',
 'TZ_0044_m12',
 'TZ_0044_m15',
 'TZ_0044_m18',
 'TZ_0044_m2',
 'TZ_0044_m24',
 'TZ_0044_m3',
 'TZ_0044_m4',
 'TZ_0044_m5',
 'TZ_0044_m6',
 'TZ_0044_m9',
 'TZ_0044_w1',
 'TZ_0044_w2',
 'TZ_0044_w3',
 'TZ_0044_w4',
 'TZ_0045_m12',
 'TZ_0045_m15',
 'TZ_0045_m18',
 'TZ_0045_m2',
 'TZ_0045_m24',
 'TZ_0045_m3',
 'TZ_0045_m4',
 'TZ_0045_m5',
 'TZ_0045_m6',
 'TZ_0045_m9',
 'TZ_0045_w2',
 'TZ_0045_w3',
 'TZ_0045_w4',
 'TZ_0046_m12',
 'TZ_0046_m15',
 'TZ_0046_m18',
 'TZ_0046_m2',
 'TZ_0046_m24',
 'TZ_0046_m3',
 'TZ_0046_m4',
 'TZ_0046_m5',
 'TZ_0046_m6',
 'TZ_0046_m9',
 'TZ_0046_w2',
 'TZ_0046_w3',
 'TZ_0046_w4',
 'TZ_0047_m12',
 'TZ_0047_m15',
 'TZ_0047_m18',
 'TZ_0047_m2',
 'TZ_0047_m24',
 'TZ_0047_m3',
 'TZ_0047_m4',
 'TZ_0047_m5',
 'TZ_0047_m6',
 'TZ_0047_m9',
 'TZ_0047_w2',
 'TZ_0047_w3',
 'TZ_0047_w4',
 'TZ_0048_m1',
 'TZ_0048_m12',
 'TZ_0048_m15',
 'TZ_0048_m18',
 'TZ_0048_m2',
 'TZ_0048_m24',
 'TZ_0048_m3',
 'TZ_0048_m4',
 'TZ_0048_m5',
 'TZ_0048_m6',
 'TZ_0048_m9',
 'TZ_0048_w1',
 'TZ_0048_w2',
 'TZ_0048_w3',
 'TZ_0048_w4',
 'TZ_0049_m12',
 'TZ_0049_m15',
 'TZ_0049_m18',
 'TZ_0049_m2',
 'TZ_0049_m24',
 'TZ_0049_m3',
 'TZ_0049_m4',
 'TZ_0049_m5',
 'TZ_0049_m6',
 'TZ_0049_m9',
 'TZ_0049_w2',
 'TZ_0049_w3',
 'TZ_0049_w4',
 'TZ_0050_m12',
 'TZ_0050_m15',
 'TZ_0050_m18',
 'TZ_0050_m2',
 'TZ_0050_m24',
 'TZ_0050_m3',
 'TZ_0050_m4',
 'TZ_0050_m5',
 'TZ_0050_m6',
 'TZ_0050_m9',
 'TZ_0050_w2',
 'TZ_0050_w3',
 'TZ_0050_w4',
 'TZ_0051_m12',
 'TZ_0051_m15',
 'TZ_0051_m18',
 'TZ_0051_m2',
 'TZ_0051_m24',
 'TZ_0051_m3',
 'TZ_0051_m4',
 'TZ_0051_m5',
 'TZ_0051_m6',
 'TZ_0051_m9',
 'TZ_0051_w2',
 'TZ_0051_w3',
 'TZ_0051_w4',
 'TZ_0052_m1',
 'TZ_0052_m12',
 'TZ_0052_m15',
 'TZ_0052_m18',
 'TZ_0052_m2',
 'TZ_0052_m24',
 'TZ_0052_m3',
 'TZ_0052_m4',
 'TZ_0052_m5',
 'TZ_0052_m6',
 'TZ_0052_m9',
 'TZ_0052_w1',
 'TZ_0052_w2',
 'TZ_0052_w3',
 'TZ_0052_w4',
 'TZ_0053_m12',
 'TZ_0053_m15',
 'TZ_0053_m18',
 'TZ_0053_m2',
 'TZ_0053_m24',
 'TZ_0053_m3',
 'TZ_0053_m4',
 'TZ_0053_m5',
 'TZ_0053_m6',
 'TZ_0053_m9',
 'TZ_0053_w2',
 'TZ_0053_w3',
 'TZ_0053_w4',
 'TZ_0054_m12',
 'TZ_0054_m15',
 'TZ_0054_m18',
 'TZ_0054_m2',
 'TZ_0054_m24',
 'TZ_0054_m3',
 'TZ_0054_m4',
 'TZ_0054_m5',
 'TZ_0054_m6',
 'TZ_0054_m9',
 'TZ_0054_w2',
 'TZ_0054_w3',
 'TZ_0054_w4',
 'TZ_0055_m12',
 'TZ_0055_m15',
 'TZ_0055_m18',
 'TZ_0055_m2',
 'TZ_0055_m24',
 'TZ_0055_m3',
 'TZ_0055_m4',
 'TZ_0055_m5',
 'TZ_0055_m6',
 'TZ_0055_m9',
 'TZ_0055_w2',
 'TZ_0055_w3',
 'TZ_0055_w4',
 'TZ_0056_m1',
 'TZ_0056_m12',
 'TZ_0056_m15',
 'TZ_0056_m18',
 'TZ_0056_m2',
 'TZ_0056_m24',
 'TZ_0056_m3',
 'TZ_0056_m4',
 'TZ_0056_m5',
 'TZ_0056_m6',
 'TZ_0056_m9',
 'TZ_0056_w1',
 'TZ_0056_w2',
 'TZ_0056_w3',
 'TZ_0056_w4',
 'TZ_0057_m12',
 'TZ_0057_m15',
 'TZ_0057_m18',
 'TZ_0057_m2',
 'TZ_0057_m24',
 'TZ_0057_m3',
 'TZ_0057_m4',
 'TZ_0057_m5',
 'TZ_0057_m6',
 'TZ_0057_m9',
 'TZ_0057_w2',
 'TZ_0057_w3',
 'TZ_0057_w4',
 'TZ_0058_m12',
 'TZ_0058_m15',
 'TZ_0058_m18',
 'TZ_0058_m2',
 'TZ_0058_m24',
 'TZ_0058_m3',
 'TZ_0058_m4',
 'TZ_0058_m5',
 'TZ_0058_m6',
 'TZ_0058_m9',
 'TZ_0058_w2',
 'TZ_0058_w3',
 'TZ_0058_w4',
 'TZ_0059_m12',
 'TZ_0059_m15',
 'TZ_0059_m18',
 'TZ_0059_m2',
 'TZ_0059_m24',
 'TZ_0059_m3',
 'TZ_0059_m4',
 'TZ_0059_m5',
 'TZ_0059_m6',
 'TZ_0059_m9',
 'TZ_0059_w2',
 'TZ_0059_w3',
 'TZ_0059_w4',
 'TZ_0060_m1',
 'TZ_0060_m12',
 'TZ_0060_m15',
 'TZ_0060_m18',
 'TZ_0060_m2',
 'TZ_0060_m24',
 'TZ_0060_m3',
 'TZ_0060_m4',
 'TZ_0060_m5',
 'TZ_0060_m6',
 'TZ_0060_m9',
 'TZ_0060_w1',
 'TZ_0060_w2',
 'TZ_0060_w3',
 'TZ_0060_w4',
 'TZ_0061_m12',
 'TZ_0061_m15',
 'TZ_0061_m18',
 'TZ_0061_m2',
 'TZ_0061_m24',
 'TZ_0061_m3',
 'TZ_0061_m4',
 'TZ_0061_m5',
 'TZ_0061_m6',
 'TZ_0061_m9',
 'TZ_0061_w2',
 'TZ_0061_w3',
 'TZ_0061_w4',
 'TZ_0062_m12',
 'TZ_0062_m15',
 'TZ_0062_m18',
 'TZ_0062_m2',
 'TZ_0062_m24',
 'TZ_0062_m3',
 'TZ_0062_m4',
 'TZ_0062_m5',
 'TZ_0062_m6',
 'TZ_0062_m9',
 'TZ_0062_w2',
 'TZ_0062_w3',
 'TZ_0062_w4',
 'TZ_0063_m12',
 'TZ_0063_m15',
 'TZ_0063_m18',
 'TZ_0063_m2',
 'TZ_0063_m24',
 'TZ_0063_m3',
 'TZ_0063_m4',
 'TZ_0063_m5',
 'TZ_0063_m6',
 'TZ_0063_m9',
 'TZ_0063_w2',
 'TZ_0063_w3',
 'TZ_0063_w4',
 'TZ_0064_m1',
 'TZ_0064_m12',
 'TZ_0064_m15',
 'TZ_0064_m18',
 'TZ_0064_m2',
 'TZ_0064_m24',
 'TZ_0064_m3',
 'TZ_0064_m4',
 'TZ_0064_m5',
 'TZ_0064_m6',
 'TZ_0064_m9',
 'TZ_0064_w1',
 'TZ_0064_w2',
 'TZ_0064_w3',
 'TZ_0064_w4',
 'TZ_0065_m12',
 'TZ_0065_m15',
 'TZ_0065_m18',
 'TZ_0065_m2',
 'TZ_0065_m24',
 'TZ_0065_m3',
 'TZ_0065_m4',
 'TZ_0065_m5',
 'TZ_0065_m6',
 'TZ_0065_m9',
 'TZ_0065_w2',
 'TZ_0065_w3',
 'TZ_0065_w4',
 'TZ_0066_m12',
 'TZ_0066_m15',
 'TZ_0066_m18',
 'TZ_0066_m2',
 'TZ_0066_m24',
 'TZ_0066_m3',
 'TZ_0066_m4',
 'TZ_0066_m5',
 'TZ_0066_m6',
 'TZ_0066_m9',
 'TZ_0066_w2',
 'TZ_0066_w3',
 'TZ_0066_w4',
 'TZ_0067_m12',
 'TZ_0067_m15',
 'TZ_0067_m18',
 'TZ_0067_m2',
 'TZ_0067_m24',
 'TZ_0067_m3',
 'TZ_0067_m4',
 'TZ_0067_m5',
 'TZ_0067_m6',
 'TZ_0067_m9',
 'TZ_0067_w2',
 'TZ_0067_w3',
 'TZ_0067_w4',
 'TZ_0068_m1',
 'TZ_0068_m12',
 'TZ_0068_m15',
 'TZ_0068_m18',
 'TZ_0068_m2',
 'TZ_0068_m24',
 'TZ_0068_m3',
 'TZ_0068_m4',
 'TZ_0068_m5',
 'TZ_0068_m6',
 'TZ_0068_m9',
 'TZ_0068_w1',
 'TZ_0068_w2',
 'TZ_0068_w3',
 'TZ_0068_w4',
 'TZ_0069_m12',
 'TZ_0069_m15',
 'TZ_0069_m18',
 'TZ_0069_m2',
 'TZ_0069_m24',
 'TZ_0069_m3',
 'TZ_0069_m4',
 'TZ_0069_m5',
 'TZ_0069_m6',
 'TZ_0069_m9',
 'TZ_0069_w2',
 'TZ_0069_w3',
 'TZ_0069_w4',
 'TZ_0070_m12',
 'TZ_0070_m15',
 'TZ_0070_m18',
 'TZ_0070_m2',
 'TZ_0070_m24',
 'TZ_0070_m3',
 'TZ_0070_m4',
 'TZ_0070_m5',
 'TZ_0070_m6',
 'TZ_0070_m9',
 'TZ_0070_w2',
 'TZ_0070_w3',
 'TZ_0070_w4',
 'TZ_0071_m12',
 'TZ_0071_m15',
 'TZ_0071_m18',
 'TZ_0071_m2',
 'TZ_0071_m24',
 'TZ_0071_m3',
 'TZ_0071_m4',
 'TZ_0071_m5',
 'TZ_0071_m6',
 'TZ_0071_m9',
 'TZ_0071_w2',
 'TZ_0071_w3',
 'TZ_0071_w4',
 'TZ_0072_m1',
 'TZ_0072_m12',
 'TZ_0072_m15',
 'TZ_0072_m18',
 'TZ_0072_m2',
 'TZ_0072_m24',
 'TZ_0072_m3',
 'TZ_0072_m4',
 'TZ_0072_m5',
 'TZ_0072_m6',
 'TZ_0072_m9',
 'TZ_0072_w1',
 'TZ_0072_w2',
 'TZ_0072_w3',
 'TZ_0072_w4',
 'TZ_0073_m12',
 'TZ_0073_m15',
 'TZ_0073_m18',
 'TZ_0073_m2',
 'TZ_0073_m24',
 'TZ_0073_m3',
 'TZ_0073_m4',
 'TZ_0073_m5',
 'TZ_0073_m6',
 'TZ_0073_m9',
 'TZ_0073_w2',
 'TZ_0073_w3',
 'TZ_0073_w4',
 ...]

In [14]:
len(fea_list)

15160

## 2 转parquet

In [24]:
from new_tools.parquet_utils import prepare_parquet_from_csv_new

In [ ]:
zip_path = the_data_path
force_regenerate = False
encoding = 'utf8'
separator = ','
enable_schema = True
feature_start_index = 5
row_group_size = 10000
batch_size = 10000         
mem_threshold_gb = 16.0

In [25]:
prepare_parquet_from_csv_new(
    zip_path, parquet_zip_path, force_regenerate, encoding, separator, 
    enable_schema, feature_start_index, row_group_size,
    batch_size=batch_size, 
    mem_threshold_gb=mem_threshold_gb
)

开始转换任务 '维信20251106_d1_t2_z2_deltaV1_result.zip' -> '维信20251106_d1_t2_z2_deltaV1_result.parquet'
  - 参数: batch_size=10000, row_group_size=10000, mem_threshold=16.0GB
  - 检测到ZIP文件，准备解压至临时目录: C:\Users\30469\AppData\Local\Temp\tmp664vf930
  - 正在解压: ╬¼╨┼20251106_d1_t2_z2_deltaV1_result.txt
  - 使用高效的 UTF-8 流式路径...
  - 阶段1: 准备混合类型Schema...
✅ 成功构建混合类型Schema，共 15165 列。
  - 阶段2: 开始流式读取并分块写入Parquet文件...
    - 初始化 ParquetWriter, row_group_size: 10000
    - 已处理 5 批次, 累计 50,235 行, 内存: 5.39GB
    - 已处理 10 批次, 累计 100,449 行, 内存: 3.98GB
    - 已处理 15 批次, 累计 150,675 行, 内存: 6.38GB
    - 已处理 20 批次, 累计 200,761 行, 内存: 8.36GB
    - 已处理 25 批次, 累计 250,767 行, 内存: 10.52GB
    - 已处理 30 批次, 累计 300,834 行, 内存: 13.15GB
    - 已处理 35 批次, 累计 350,902 行, 内存: 2.39GB
    - 已处理 40 批次, 累计 401,021 行, 内存: 4.90GB
    - 已处理 45 批次, 累计 451,121 行, 内存: 7.24GB
    - 已处理 50 批次, 累计 501,212 行, 内存: 9.56GB
    - 已处理 55 批次, 累计 551,304 行, 内存: 11.85GB
    - 已处理 60 批次, 累计 601,388 行, 内存: 14.15GB
    - 已处理 65 批次, 累计 651,777 行, 内存: 2.54GB
    - 已处理 70 批次, 累计 703,315 行, 内存: 5.32GB
    ✓ 共处理 73 批次, 724,038 行
  - 临时解压目录已清理
✅ 转换成功完成，文件已保存至 'D:/work/06.std_product/wxjk_test/data_or/维信20251106_d1_t2_z2_deltaV1_result.parquet'
    内存清理后 - 可用内存: 19599 MB (39.7% 已使用)

## 3 feature selection 1

In [27]:
print('debug mode: ', debug)

debug mode:  False

In [28]:
if debug:
    fea_list = fea_list[:1000]

In [29]:
from new_tools import flitter_by_std_fpr
ftr1_keep_dict = {}
length = 500
for i in range(0,(len(fea_list) // length) + 1):
    start,end  = i * length, min((i + 1) * length, len(fea_list))
    print(start, ' - ', end)
    tmp_lst = [i for i in fea_list[start:end] if i not in object_columns]
    each_df = pd.read_parquet(parquet_zip_path, 
                    columns=tmp_lst,
                    engine='pyarrow') 
    ftr1_keep = flitter_by_std_fpr.drop_svr(each_df.fillna(-999), 0.95, tmp_lst)
    ftr1_keep = flitter_by_std_fpr.drop_std(each_df.fillna(-999), 0, ftr1_keep)
    ftr1_keep_dict[i] = ftr1_keep
    del each_df, ftr1_keep
    gc.collect()

0  -  500

筛选单一值率: 100%|██████████| 500/500 [00:02<00:00, 214.51it/s]

舍弃了 242 个单一值占比超过 95.0% 的列

筛选标准差: 100%|██████████| 258/258 [00:01<00:00, 225.34it/s]

舍弃了 0 个标准差小于等于 0 的列
500  -  1000

筛选单一值率: 100%|██████████| 500/500 [00:02<00:00, 226.05it/s]

舍弃了 257 个单一值占比超过 95.0% 的列

筛选标准差: 100%|██████████| 243/243 [00:01<00:00, 234.79it/s]

舍弃了 0 个标准差小于等于 0 的列
1000  -  1500

筛选单一值率: 100%|██████████| 500/500 [00:02<00:00, 221.00it/s]

舍弃了 255 个单一值占比超过 95.0% 的列

筛选标准差: 100%|██████████| 245/245 [00:01<00:00, 228.62it/s]

舍弃了 0 个标准差小于等于 0 的列
1500  -  2000

筛选单一值率: 100%|██████████| 500/500 [00:02<00:00, 203.38it/s]

舍弃了 316 个单一值占比超过 95.0% 的列

筛选标准差: 100%|██████████| 184/184 [00:01<00:00, 163.76it/s]

舍弃了 0 个标准差小于等于 0 的列
2000  -  2500

筛选单一值率: 100%|██████████| 500/500 [00:02<00:00, 184.37it/s]

舍弃了 174 个单一值占比超过 95.0% 的列

筛选标准差: 100%|██████████| 326/326 [00:01<00:00, 204.51it/s]

舍弃了 0 个标准差小于等于 0 的列
2500  -  3000

筛选单一值率: 100%|██████████| 500/500 [00:02<00:00, 216.22it/s]

舍弃了 265 个单一值占比超过 95.0% 的列

筛选标准差: 100%|██████████| 235/235 [00:01<00:00, 234.25it/s]

舍弃了 0 个标准差小于等于 0 的列
3000  -  3500

筛选单一值率: 100%|██████████| 500/500 [00:02<00:00, 182.08it/s]

舍弃了 219 个单一值占比超过 95.0% 的列

筛选标准差: 100%|██████████| 281/281 [00:01<00:00, 231.38it/s]

舍弃了 0 个标准差小于等于 0 的列
3500  -  4000

筛选单一值率: 100%|██████████| 500/500 [00:03<00:00, 143.00it/s]

舍弃了 213 个单一值占比超过 95.0% 的列

筛选标准差: 100%|██████████| 287/287 [00:01<00:00, 223.88it/s]

舍弃了 0 个标准差小于等于 0 的列
4000  -  4500

筛选单一值率: 100%|██████████| 500/500 [00:02<00:00, 199.54it/s]

舍弃了 399 个单一值占比超过 95.0% 的列

筛选标准差: 100%|██████████| 101/101 [00:00<00:00, 228.63it/s]

舍弃了 0 个标准差小于等于 0 的列
4500  -  5000

筛选单一值率: 100%|██████████| 500/500 [00:02<00:00, 191.45it/s]

舍弃了 328 个单一值占比超过 95.0% 的列

筛选标准差: 100%|██████████| 172/172 [00:00<00:00, 228.57it/s]

舍弃了 0 个标准差小于等于 0 的列
5000  -  5500

筛选单一值率: 100%|██████████| 500/500 [00:02<00:00, 211.28it/s]

舍弃了 186 个单一值占比超过 95.0% 的列

筛选标准差: 100%|██████████| 314/314 [00:01<00:00, 225.90it/s]

舍弃了 0 个标准差小于等于 0 的列
5500  -  6000

筛选单一值率: 100%|██████████| 500/500 [00:02<00:00, 237.40it/s]

舍弃了 283 个单一值占比超过 95.0% 的列

筛选标准差: 100%|██████████| 217/217 [00:00<00:00, 225.04it/s]

舍弃了 0 个标准差小于等于 0 的列
6000  -  6500

筛选单一值率: 100%|██████████| 500/500 [00:02<00:00, 239.24it/s]

舍弃了 478 个单一值占比超过 95.0% 的列

筛选标准差: 100%|██████████| 22/22 [00:00<00:00, 197.34it/s]

舍弃了 0 个标准差小于等于 0 的列
6500  -  7000

筛选单一值率: 100%|██████████| 500/500 [00:02<00:00, 214.52it/s]

舍弃了 491 个单一值占比超过 95.0% 的列

筛选标准差: 100%|██████████| 9/9 [00:00<00:00, 138.94it/s]

舍弃了 0 个标准差小于等于 0 的列
7000  -  7500

筛选单一值率: 100%|██████████| 500/500 [00:02<00:00, 234.55it/s]

舍弃了 500 个单一值占比超过 95.0% 的列

筛选标准差: 0it [00:00, ?it/s]

舍弃了 0 个标准差小于等于 0 的列
7500  -  8000

筛选单一值率: 100%|██████████| 500/500 [00:02<00:00, 236.75it/s]

舍弃了 500 个单一值占比超过 95.0% 的列

筛选标准差: 0it [00:00, ?it/s]

舍弃了 0 个标准差小于等于 0 的列
8000  -  8500

筛选单一值率: 100%|██████████| 500/500 [00:01<00:00, 255.05it/s]

舍弃了 469 个单一值占比超过 95.0% 的列

筛选标准差: 100%|██████████| 31/31 [00:00<00:00, 191.07it/s]

舍弃了 0 个标准差小于等于 0 的列
8500  -  9000

筛选单一值率: 100%|██████████| 500/500 [00:02<00:00, 244.61it/s]

舍弃了 415 个单一值占比超过 95.0% 的列

筛选标准差: 100%|██████████| 85/85 [00:00<00:00, 232.70it/s]

舍弃了 0 个标准差小于等于 0 的列
9000  -  9500

筛选单一值率: 100%|██████████| 500/500 [00:02<00:00, 226.35it/s]

舍弃了 368 个单一值占比超过 95.0% 的列

筛选标准差: 100%|██████████| 132/132 [00:00<00:00, 229.49it/s]

舍弃了 0 个标准差小于等于 0 的列
9500  -  10000

筛选单一值率: 100%|██████████| 500/500 [00:02<00:00, 212.20it/s]

舍弃了 247 个单一值占比超过 95.0% 的列

筛选标准差: 100%|██████████| 253/253 [00:01<00:00, 229.47it/s]

舍弃了 0 个标准差小于等于 0 的列
10000  -  10500

筛选单一值率: 100%|██████████| 500/500 [00:02<00:00, 185.98it/s]

舍弃了 171 个单一值占比超过 95.0% 的列

筛选标准差: 100%|██████████| 329/329 [00:01<00:00, 178.72it/s]

舍弃了 0 个标准差小于等于 0 的列
10500  -  11000

筛选单一值率: 100%|██████████| 500/500 [00:02<00:00, 187.46it/s]

舍弃了 158 个单一值占比超过 95.0% 的列

筛选标准差: 100%|██████████| 342/342 [00:01<00:00, 222.73it/s]

舍弃了 0 个标准差小于等于 0 的列
11000  -  11500

筛选单一值率: 100%|██████████| 500/500 [00:03<00:00, 164.13it/s]

舍弃了 224 个单一值占比超过 95.0% 的列

筛选标准差: 100%|██████████| 276/276 [00:01<00:00, 232.42it/s]

舍弃了 0 个标准差小于等于 0 的列
11500  -  12000

筛选单一值率: 100%|██████████| 500/500 [00:03<00:00, 149.67it/s]

舍弃了 185 个单一值占比超过 95.0% 的列

筛选标准差: 100%|██████████| 315/315 [00:01<00:00, 229.17it/s]

舍弃了 0 个标准差小于等于 0 的列
12000  -  12500

筛选单一值率: 100%|██████████| 500/500 [00:02<00:00, 181.18it/s]

舍弃了 222 个单一值占比超过 95.0% 的列

筛选标准差: 100%|██████████| 278/278 [00:01<00:00, 235.21it/s]

舍弃了 0 个标准差小于等于 0 的列
12500  -  13000

筛选单一值率: 100%|██████████| 500/500 [00:02<00:00, 182.94it/s]

舍弃了 182 个单一值占比超过 95.0% 的列

筛选标准差: 100%|██████████| 318/318 [00:01<00:00, 231.63it/s]

舍弃了 0 个标准差小于等于 0 的列
13000  -  13500

筛选单一值率: 100%|██████████| 500/500 [00:02<00:00, 207.85it/s]

舍弃了 207 个单一值占比超过 95.0% 的列

筛选标准差: 100%|██████████| 293/293 [00:01<00:00, 231.46it/s]

舍弃了 0 个标准差小于等于 0 的列
13500  -  14000

筛选单一值率: 100%|██████████| 500/500 [00:02<00:00, 233.46it/s]

舍弃了 281 个单一值占比超过 95.0% 的列

筛选标准差: 100%|██████████| 219/219 [00:00<00:00, 226.75it/s]

舍弃了 0 个标准差小于等于 0 的列
14000  -  14500

筛选单一值率: 100%|██████████| 500/500 [00:02<00:00, 203.61it/s]

舍弃了 221 个单一值占比超过 95.0% 的列

筛选标准差: 100%|██████████| 279/279 [00:01<00:00, 234.99it/s]

舍弃了 0 个标准差小于等于 0 的列
14500  -  15000

筛选单一值率: 100%|██████████| 500/500 [00:02<00:00, 244.84it/s]

舍弃了 336 个单一值占比超过 95.0% 的列

筛选标准差: 100%|██████████| 164/164 [00:00<00:00, 222.10it/s]

舍弃了 0 个标准差小于等于 0 的列
15000  -  15160

筛选单一值率: 100%|██████████| 160/160 [00:00<00:00, 302.45it/s]

舍弃了 148 个单一值占比超过 95.0% 的列

筛选标准差: 100%|██████████| 12/12 [00:00<00:00, 220.46it/s]

舍弃了 0 个标准差小于等于 0 的列

In [30]:
fea_list = []
for k,v in ftr1_keep_dict.items():
    fea_list.extend(v)

In [31]:
fea_list = list(set(fea_list))
fea_list

['TZ_1247_m18',
 'TZ_1812_m18',
 'TZ_0083_w4',
 'TZ_1640_m1',
 'TZ_1747_m24',
 'TZ_0272_m2',
 'TZ_0160_m5',
 'TZ_0005_m15',
 'TZ_0390_m8',
 'TZ_1220_m12',
 'TZ_1870_m24',
 'TZ_1752_m24',
 'TZ_0442_m4',
 'TZ_1711_m12',
 'TZ_0011_m2',
 'TZ_0143_m12',
 'TZ_2019_T3_m24',
 'TZ_0017_m24',
 'TZ_0063_m4',
 'TZ_1225_m3',
 'TZ_1512_m12',
 'TZ_0028_m18',
 'TZ_0338_m9',
 'TZ_0415_m5',
 'TZ_1731_m18',
 'TZ_1972_m18',
 'TZ_1702_m18',
 'TZ_0036_w4',
 'TZ_0033_m12',
 'TZ_0333_m6',
 'TZ_1896_m24',
 'TZ_1103',
 'TZ_0077_m6',
 'TZ_0087_m24',
 'TZ_1358_m6',
 'TZ_0032_w4',
 'TZ_1424_m24',
 'TZ_0141_m12',
 'TZ_0415_m12',
 'TZ_0273_m3',
 'TZ_1521_m1',
 'TZ_1420_m1',
 'TZ_0055_m24',
 'TZ_1144_m12',
 'TZ_0328_m4',
 'TZ_1318_m12',
 'TZ_0088_m9',
 'TZ_1643_m12',
 'TZ_0183_m2',
 'TZ_1772_m6',
 'TZ_1782_m24',
 'TZ_1904_m3',
 'TZ_0108_m18',
 'TZ_1347_m12',
 'TZ_1490_m24',
 'TZ_1544_m12',
 'TZ_0463_m12',
 'TZ_1222_m12',
 'TZ_1546_m12',
 'TZ_1620_m6',
 'TZ_0020_m12',
 'TZ_1672_m6',
 'TZ_0396_m10',
 'TZ_1875_m18',
 'TZ_1864_m24',
 'TZ_1903_m24',
 'TZ_0093_m24',
 'TZ_1331_m18',
 'TZ_0266_m12',
 'TZ_0396_m24',
 'TZ_1585_m24',
 'TZ_0044_m18',
 'TZ_0097_m24',
 'TZ_0177_m5',
 'TZ_1448_m12',
 'TZ_1809_m1',
 'TZ_0185_m2',
 'TZ_1861_m18',
 'TZ_1192_m24',
 'TZ_1396_m6',
 'TZ_0008_w4',
 'TZ_1745_m12',
 'TZ_0156_m24',
 'TZ_0152_m24',
 'TZ_0248_m6',
 'TZ_2019_T2_m9',
 'TZ_0059_m4',
 'TZ_0247_m9',
 'TZ_0420_m8',
 'TZ_1317_m12',
 'TZ_0282_m5',
 'TZ_0252_m18',
 'TZ_0175_m18',
 'TZ_0324_w4',
 'TZ_1450_m12',
 'TZ_0417_m7',
 'TZ_1549_m18',
 'TZ_0959_m6',
 'TZ_0164_m5',
 'TZ_1869_m3',
 'TZ_1137_m6',
 'TZ_0418_m7',
 'TZ_0392_m6',
 'TZ_1219_m3',
 'TZ_0441_m3',
 'TZ_1620_m18',
 'TZ_0037_m2',
 'TZ_1325_m12',
 'TZ_0394_m10',
 'TZ_1166_m6',
 'TZ_1462_m3',
 'TZ_0265_w2',
 'TZ_1156_m24',
 'TZ_0029_m2',
 'TZ_1488_m6',
 'TZ_1322_m3',
 'TZ_1874_m12',
 'TZ_0989',
 'TZ_0248_m4',
 'TZ_1336_m1',
 'TZ_1652_m3',
 'TZ_1905_m3',
 'TZ_1928_m24',
 'TZ_1421_m6',
 'TZ_1622_m12',
 'TZ_1934_m24',
 'TZ_0189_m15',
 'TZ_0441_m10',
 'TZ_1354_m24',
 'TZ_0272_m18',
 'TZ_0267_m18',
 'TZ_1719_m3',
 'TZ_1297_m12',
 'TZ_0357_m12',
 'TZ_1590_m3',
 'TZ_1572_m6',
 'TZ_1975_m12',
 'TZ_0267_w2',
 'TZ_0057_w2',
 'TZ_1351_m24',
 'TZ_1200_m6',
 'TZ_0250_m24',
 'TZ_0265_m15',
 'TZ_0179_m5',
 'TZ_1266_m6',
 'TZ_0465_m24',
 'TZ_1606_m6',
 'TZ_0112_m24',
 'TZ_0015_m15',
 'TZ_1271_m24',
 'TZ_1715_m18',
 'TZ_1931_m1',
 'TZ_1717_m3',
 'TZ_1656_m18',
 'TZ_1835_m12',
 'TZ_1718_m24',
 'TZ_1717_m1',
 'TZ_0979_m24',
 'TZ_1389_m1',
 'TZ_1492_m6',
 'TZ_1387_m24',
 'TZ_0356_m2',
 'TZ_1643_m6',
 'TZ_0988',
 'TZ_1165_m12',
 'TZ_1524_m24',
 'TZ_0177_m3',
 'TZ_0088_m6',
 'TZ_0227_m24',
 'TZ_0220_m5',
 'TZ_0291_m18',
 'TZ_1512_m18',
 'TZ_0968_m12',
 'TZ_0025_m12',
 'TZ_1897_m18',
 'TZ_0445_m12',
 'TZ_0184_m2',
 'TZ_1612_m3',
 'TZ_1706_m6',
 'TZ_1450_m6',
 'TZ_1175_m24',
 'TZ_1357_m18',
 'TZ_0390_m9',
 'TZ_0201_m9',
 'TZ_0083_m15',
 'TZ_0140_m2',
 'TZ_1812_m1',
 'TZ_1701_m18',
 'TZ_1000_w1_to_m1',
 'TZ_1559_m3',
 'TZ_0036_m9',
 'TZ_0464_m24',
 'TZ_0056_w3',
 'TZ_1880_m24',
 'TZ_1380_m3',
 'TZ_0271_m2',
 'TZ_1412_m18',
 'TZ_1552_m12',
 'TZ_0089_m9',
 'TZ_1806_m1',
 'TZ_1974_m12',
 'TZ_0394_m4',
 'TZ_0052_m3',
 'TZ_2017_T3_m15',
 'TZ_0357_m9',
 'TZ_0967_m24',
 'TZ_1364_m24',
 'TZ_0156_m9',
 'TZ_0010_m2',
 'TZ_0402_m7',
 'TZ_1743_m1',
 'TZ_0141_m5',
 'TZ_2019_T3_m4',
 'TZ_0200_m4',
 'TZ_0380_m18',
 'TZ_1319_m24',
 'TZ_0137_m2',
 'TZ_0027_m15',
 'TZ_1400_m24',
 'TZ_1523_m12',
 'TZ_0251_m9',
 'TZ_0292_m15',
 'TZ_0017_m18',
 'TZ_0326_w2',
 'TZ_1294_m24',
 'TZ_0059_m3',
 'TZ_0401_m3',
 'TZ_1238_m3',
 'TZ_1522_m1',
 'TZ_0188_m24',
 'TZ_1396_m18',
 'TZ_0268_m24',
 'TZ_0076_w3',
 'TZ_0422_m7',
 'TZ_0179_m4',
 'TZ_0117_m18',
 'TZ_0465_m12',
 'TZ_1164_m18',
 'TZ_1802_m3',
 'TZ_0173_m4',
 'TZ_1815_m18',
 'TZ_0172_m18',
 'TZ_1608_m3',
 'TZ_0138_m5',
 'TZ_1133_m18',
 'TZ_1323_m24',
 'TZ_1175_m1',
 'TZ_1553_m12',
 'TZ_0236_m5',
 'TZ_1736_m3',
 'TZ_0079_m9',
 'TZ_1960_m12',
 'TZ_0172_m4',
 'TZ_0019_m24',
 'TZ_0249_m3',
 'TZ_1424_m1',
 'TZ_1910_m3',
 'TZ_0282_m15',
 'TZ_0421_m4',
 'TZ_0139_w4',
 'TZ_0053_m5',
 'TZ_1910_m24',
 'TZ_1384_m12',
 'TZ_2019_T3_m15',
 'TZ_0032_m2',
 'TZ_0330_w2',
 'TZ_0371',
 'TZ_1163_m12',
 'TZ_1515_m12',
 'TZ_0077_m3',
 'TZ_1731_m12',
 'TZ_1139_m18',
 'TZ_1774_m12',
 'TZ_1508_m12',
 'TZ_1686_m3',
 'TZ_1019_w4',
 'TZ_1640_m12',
 'TZ_0273_m15',
 'TZ_1481_m3',
 'TZ_0148_m24',
 'TZ_1389_m12',
 'TZ_1419_m24',
 'TZ_0052_m24',
 'TZ_1235_m3',
 'TZ_0265_m18',
 'TZ_1801_m24',
 'TZ_1189_m24',
 'TZ_0039_m5',
 'TZ_1621_m3',
 'TZ_0153_m24',
 'TZ_0416_m11',
 'TZ_0035_m6',
 'TZ_1842_m6',
 'TZ_0155_w4',
 'TZ_1616_m3',
 'TZ_0961_m24',
 'TZ_1715_m24',
 'TZ_1161_m12',
 'TZ_0193_w4',
 'TZ_1809_m24',
 'TZ_1554_m1',
 'TZ_0009_m6',
 'TZ_1899_m18',
 'TZ_0244_m15',
 'TZ_0284_m12',
 'TZ_1965_m6',
 'TZ_0139_m4',
 'TZ_1904_m18',
 'TZ_0005_m5',
 'TZ_0088_m5',
 'TZ_1193_m24',
 'TZ_1685_m3',
 'TZ_1967_m24',
 'TZ_0167_m15',
 'TZ_1171_m6',
 'TZ_1291_m24',
 'TZ_1418_m12',
 'TZ_0325_m24',
 'TZ_1560_m1',
 'TZ_0238_m6',
 'TZ_1870_m3',
 'TZ_0220_m9',
 'TZ_1805_m24',
 'TZ_0008_m3',
 'TZ_0405_m12',
 'TZ_1380_m6',
 'TZ_0237_m9',
 'TZ_1720_m1',
 'TZ_0213_m18',
 'TZ_0155_w2',
 'TZ_0112_m9',
 'TZ_0288_m12',
 'TZ_1450_m24',
 'TZ_1284_m18',
 'TZ_1941_m6',
 'TZ_1978_m6',
 'TZ_1142_m18',
 'TZ_1699_m18',
 'TZ_0007_m9',
 'TZ_0280_m9',
 'TZ_0419_m9',
 'TZ_1527_m24',
 'TZ_1540_m6',
 'TZ_0326_m2',
 'TZ_0020_m15',
 'TZ_1456_m24',
 'TZ_1578_m3',
 'TZ_0442_m7',
 'TZ_1017_m6',
 'TZ_0998_m1_to_m12',
 'TZ_0152_m2',
 'TZ_0220_m6',
 'TZ_0279_m15',
 'TZ_1541_m6',
 'TZ_0325_m6',
 'TZ_1873_m18',
 'TZ_1423_m12',
 'TZ_0285_m15',
 'TZ_0218_m24',
 'TZ_0084_m4',
 'TZ_0324_m3',
 'TZ_0810_m10',
 'TZ_0132_m12',
 'TZ_1962_m12',
 'TZ_1170_m6',
 'TZ_1928_m12',
 'TZ_1265_m18',
 'TZ_1343_m6',
 'TZ_0241_m5',
 'TZ_0331_m2',
 'TZ_1251_m18',
 'TZ_1807_m1',
 'TZ_0444_m10',
 'TZ_0417_m12',
 'TZ_1161_m6',
 'TZ_1454_m18',
 'TZ_1802_m24',
 'TZ_1809_m6',
 'TZ_1266_m1',
 'TZ_1517_m12',
 'TZ_0267_m12',
 'TZ_1399_m18',
 'TZ_1930_m18',
 'TZ_1797_m3',
 'TZ_0265_m3',
 'TZ_1425_m3',
 'TZ_1254_m12',
 'TZ_1775_m6',
 'TZ_1367_m6',
 'TZ_1253_m18',
 'TZ_1577_m24',
 'TZ_1230_m18',
 'TZ_2019_T3_m18',
 'TZ_1676_m18',
 'TZ_1898_m6',
 'TZ_1352_m1',
 'TZ_1861_m12',
 'TZ_1431_m3',
 'TZ_0417_m5',
 'TZ_0267_m15',
 'TZ_1232_m1',
 'TZ_0138_m3',
 'TZ_1393_m24',
 'TZ_0441_m12',
 'TZ_1452_m3',
 'TZ_0237_m15',
 'TZ_0395_m4',
 'TZ_1385_m18',
 'TZ_1258_m12',
 'TZ_0325_m2',
 'TZ_1556_m3',
 'TZ_0226_m15',
 'TZ_0400_m11',
 'TZ_0444_m1',
 'TZ_0228_m6',
 'TZ_1349_m24',
 'TZ_1865_m6',
 'TZ_0165_m9',
 'TZ_0051_m4',
 'TZ_1738_m6',
 'TZ_0011_w3',
 'TZ_0001_m5',
 'TZ_1299_m3',
 'TZ_1239_m6',
 'TZ_1125_m6',
 'TZ_0419_m8',
 'TZ_0179_m18',
 'TZ_0172_w3',
 'TZ_1802_m18',
 'TZ_1840_m6',
 'TZ_0268_m12',
 'TZ_1901_m1',
 'TZ_2020_T4_m12',
 'TZ_0443_m9',
 'TZ_1390_m3',
 'TZ_0177_w3',
 'TZ_0085_m9',
 'TZ_1084_m24',
 'TZ_1974_m24',
 'TZ_1134_m24',
 'TZ_1300_m3',
 'TZ_1734_m12',
 'TZ_1267_m3',
 'TZ_1172_m1',
 'TZ_0332_m6',
 'TZ_0224_m6',
 'TZ_1942_m1',
 'TZ_0244_m24',
 'TZ_1527_m12',
 'TZ_1644_m12',
 'TZ_0167_w3',
 'TZ_0438_m9',
 'TZ_1839_m24',
 'TZ_2017_T2_m3',
 'TZ_1331_m24',
 'TZ_0390_m6',
 'TZ_1912_m24',
 'TZ_0037_m4',
 'TZ_0281_m18',
 'TZ_0279_m24',
 'TZ_1449_m24',
 'TZ_0057_m2',
 'TZ_1430_m3',
 'TZ_0183_m5',
 'TZ_0061_m15',
 'TZ_1232_m18',
 'TZ_0153_m6',
 'TZ_0041_m9',
 'TZ_1876_m24',
 'TZ_1329_m12',
 'TZ_0428_m8',
 'TZ_1549_m24',
 'TZ_1455_m18',
 'TZ_0059_w4',
 'TZ_1235_m6',
 'TZ_0156_m6',
 'TZ_0284_m18',
 'TZ_1610_m6',
 'TZ_1835_m3',
 'TZ_1908_m18',
 'TZ_1204_m18',
 'TZ_0176_m1',
 'TZ_0000_m5',
 'TZ_1336_m6',
 'TZ_1605_m3',
 'TZ_0390_m24',
 'TZ_0179_w3',
 'TZ_1624_m12',
 'TZ_1490_m6',
 'TZ_0241_m18',
 'TZ_1579_m24',
 'TZ_0428_m7',
 'TZ_0267_m24',
 'TZ_0355_m2',
 'TZ_1197_m3',
 'TZ_0329_w4',
 'TZ_1549_m6',
 'TZ_0075_w4',
 'TZ_0289_m9',
 'TZ_1614_m12',
 'TZ_0161_m15',
 'TZ_0404_m6',
 'TZ_1586_m24',
 'TZ_1253_m3',
 'TZ_0452_m12',
 'TZ_1160_m18',
 'TZ_0404_m11',
 'TZ_0440_m2',
 'TZ_0502_m24',
 'TZ_0132_w4',
 'TZ_0305_m9',
 'TZ_0093_m2',
 'TZ_0073_m18',
 'TZ_1140_m18',
 'TZ_1169_m3',
 'TZ_1637_m12',
 'TZ_0203_m24',
 'TZ_0212_m15',
 'TZ_1685_m6',
 'TZ_1727_m1',
 'TZ_1842_m3',
 'TZ_0281_m5',
 'TZ_1203_m12',
 'TZ_0425_m11',
 'TZ_0963_m6',
 'TZ_0176_m24',
 'TZ_1524_m18',
 'TZ_0116_m5',
 'TZ_1905_m6',
 'TZ_0210_m15',
 'TZ_1398_m6',
 'TZ_0234_m6',
 'TZ_0201_m2',
 'TZ_0268_m9',
 'TZ_1589_m18',
 'TZ_0965_m12',
 'TZ_1362_m6',
 'TZ_0961_m6',
 'TZ_1192_m6',
 'TZ_0281_m24',
 'TZ_0155_m24',
 'TZ_0192_m24',
 'TZ_0165_m12',
 'TZ_0041_m3',
 'TZ_0080_m18',
 'TZ_0196_w4',
 'TZ_1542_m24',
 'TZ_0224_m4',
 'TZ_0015_w4',
 'TZ_1296_m24',
 'TZ_0995_m6_to_m12',
 'TZ_0037_w4',
 'TZ_0155_m12',
 'TZ_1317_m24',
 'TZ_1743_m6',
 'TZ_0210_m18',
 'TZ_0180_w3',
 'TZ_0136_m18',
 'TZ_1552_m1',
 'TZ_1944_m18',
 'TZ_0331_m4',
 'TZ_1460_m6',
 'TZ_0096_m5',
 'TZ_0202_m24',
 'TZ_0338_m12',
 'TZ_0390_m12',
 'TZ_1966_m18',
 'TZ_0963_m24',
 'TZ_0355_m6',
 'TZ_1193_m12',
 'TZ_1709_m3',
 'TZ_1221_m3',
 'TZ_1294_m3',
 'TZ_1135_m1',
 'TZ_0402_m6',
 'TZ_0076_m12',
 'TZ_0200_m9',
 'TZ_1361_m6',
 'TZ_0285_m6',
 'TZ_0418_m5',
 'TZ_1574_m3',
 'TZ_0159_w4',
 'TZ_1617_m24',
 'TZ_1162_m6',
 'TZ_1136_m18',
 'TZ_1707_m12',
 'TZ_0404_m10',
 'TZ_0421_m5',
 'TZ_0015_m9',
 'TZ_0460_m12',
 'TZ_1494_m3',
 'TZ_0359_m24',
 'TZ_1624_m3',
 'TZ_1685_m1',
 'TZ_0265_w4',
 'TZ_1838_m12',
 'TZ_0143_m6',
 'TZ_1638_m18',
 'TZ_0442_m8',
 'TZ_0456_m6',
 'TZ_1388_m24',
 'TZ_1804_m12',
 'TZ_1900_m18',
 'TZ_1604_m12',
 'TZ_0250_m5',
 'TZ_1200_m3',
 'TZ_1523_m1',
 'TZ_0045_m15',
 'TZ_0077_w3',
 'TZ_1420_m18',
 'TZ_1011_m1_to_m2',
 'TZ_1262_m6',
 'TZ_1865_m18',
 'TZ_0155_m18',
 'TZ_1221_m6',
 'TZ_0093_m15',
 'TZ_1237_m24',
 'TZ_0423_m6',
 'TZ_1302_m1',
 'TZ_1359_m24',
 'TZ_0399_m11',
 'TZ_0217_m15',
 'TZ_1709_m1',
 'TZ_1781_m12',
 'TZ_0286_m15',
 'TZ_0966_m6',
 'TZ_0147_m12',
 'TZ_0356_m24',
 'TZ_0241_m12',
 'TZ_0171_m15',
 'TZ_0095_m18',
 'TZ_1943_m6',
 'TZ_1707_m6',
 'TZ_0390_m5',
 'TZ_1237_m6',
 'TZ_1330_m6',
 'TZ_0009_m12',
 'TZ_0092_m15',
 'TZ_1357_m12',
 'TZ_1288_m12',
 'TZ_0398_m3',
 'TZ_1586_m3',
 'TZ_1452_m12',
 'TZ_0077_m12',
 'TZ_1448_m6',
 'TZ_0423_m9',
 'TZ_1585_m18',
 'TZ_1515_m3',
 'TZ_0292_m12',
 'TZ_0422_m5',
 'TZ_1220_m18',
 'TZ_0272_m24',
 'TZ_0075_m12',
 'TZ_1221_m24',
 'TZ_1586_m12',
 'TZ_1219_m24',
 'TZ_1389_m24',
 'TZ_1611_m3',
 'TZ_1981_m3',
 'TZ_1226_m6',
 'TZ_2019_T4_m4',
 'TZ_1801_m18',
 'TZ_0160_m4',
 'TZ_1688_m24',
 'TZ_0214_m24',
 'TZ_0960_m24',
 'TZ_1805_m6',
 'TZ_1163_m6',
 'TZ_0196_m18',
 'TZ_0041_m24',
 'TZ_0047_m15',
 'TZ_1902_m12',
 'TZ_0253_m18',
 'TZ_0404_m7',
 'TZ_1688_m6',
 'TZ_0282_m9',
 'TZ_1984_m18',
 'TZ_0338_m15',
 'TZ_1802_m6',
 'TZ_1457_m24',
 'TZ_1240_m24',
 'TZ_1143_m6',
 'TZ_0185_m24',
 'TZ_0078_m4',
 'TZ_1254_m6',
 'TZ_1545_m18',
 'TZ_1587_m12',
 'TZ_0079_m4',
 'TZ_0167_m5',
 'TZ_1390_m6',
 'TZ_1394_m1',
 'TZ_1556_m1',
 'TZ_1770_m18',
 'TZ_1194_m3',
 'TZ_0416_m12',
 'TZ_0444_m6',
 'TZ_0274_m6',
 'TZ_0099_m6',
 'TZ_0053_m6',
 'TZ_0277_m4',
 'TZ_0177_m12',
 'TZ_1735_m24',
 'TZ_1262_m1',
 'TZ_0132_m2',
 'TZ_1128_m1',
 'TZ_0230_m12',
 'TZ_1944_m24',
 'TZ_1840_m18',
 'TZ_0382_m24',
 'TZ_1489_m12',
 'TZ_0224_m3',
 'TZ_1778_m3',
 'TZ_0294_m15',
 'TZ_0444_m2',
 'TZ_0274_w3',
 'TZ_1237_m1',
 'TZ_0249_m2',
 'TZ_1813_m12',
 'TZ_0007_m12',
 'TZ_0267_w3',
 'TZ_0269_m15',
 'TZ_1640_m18',
 'TZ_0077_m9',
 'TZ_0278_m5',
 'TZ_0187_m12',
 'TZ_0137_m18',
 'TZ_0177_w4',
 'TZ_1929_m3',
 'TZ_0210_m9',
 'TZ_1517_m1',
 'TZ_1781_m6',
 'TZ_0047_m6',
 'TZ_1835_m18',
 'TZ_0169_m4',
 'TZ_1226_m24',
 'TZ_1816_m6',
 'TZ_1353_m24',
 'TZ_0196_w2',
 'TZ_0264_w4',
 'TZ_1804_m3',
 'TZ_0008_w3',
 'TZ_0394_m5',
 'TZ_0157_m6',
 'TZ_1901_m6',
 'TZ_1924_m6',
 'TZ_0461_m6',
 'TZ_1984_m3',
 'TZ_1227_m6',
 'TZ_0454_m24',
 'TZ_1131_m3',
 'TZ_1843_m3',
 'TZ_0236_m12',
 'TZ_1368_m18',
 'TZ_1843_m6',
 'TZ_1202_m18',
 'TZ_1669_m18',
 'TZ_2019_T4_m12',
 'TZ_1257_m6',
 'TZ_1239_m24',
 'TZ_1329_m24',
 'TZ_0019_m15',
 'TZ_1425_m18',
 'TZ_1220_m6',
 'TZ_0425_m24',
 'TZ_1483_m18',
 'TZ_1232_m12',
 'TZ_1482_m12',
 'TZ_1526_m3',
 'TZ_1422_m1',
 'TZ_1975_m6',
 'TZ_1169_m1',
 'TZ_1139_m6',
 'TZ_1336_m12',
 'TZ_0247_m4',
 'TZ_0439_m8',
 'TZ_1357_m1',
 'TZ_1163_m24',
 'TZ_2017_T3_m9',
 'TZ_1397_m3',
 'TZ_2017_T3_m5',
 'TZ_0415_m10',
 'TZ_0055_m3',
 'TZ_0193_m15',
 'TZ_0405_m24',
 'TZ_2016_T4_m15',
 'TZ_0394_m7',
 'TZ_0027_m24',
 'TZ_1427_m6',
 'TZ_0274_m4',
 'TZ_0060_m9',
 'TZ_0199_m6',
 'TZ_1156_m6',
 'TZ_1264_m3',
 'TZ_0176_m2',
 'TZ_0004_m18',
 'TZ_1189_m12',
 'TZ_1713_m12',
 'TZ_1751_m6',
 'TZ_1363_m18',
 'TZ_1254_m18',
 'TZ_0415_m6',
 'TZ_1270_m1',
 'TZ_1367_m12',
 'TZ_1509_m18',
 'TZ_0100_m15',
 'TZ_0037_m5',
 'TZ_0403_m8',
 'TZ_0438_m12',
 'TZ_1461_m1',
 'TZ_1808_m24',
 'TZ_0253_m9',
 'TZ_0424_m8',
 'TZ_0155_w3',
 'TZ_1640_m24',
 'TZ_0059_m2',
 'TZ_0224_m15',
 'TZ_1622_m24',
 'TZ_0384_m18',
 'TZ_0078_m9',
 'TZ_1797_m1',
 'TZ_0253_m6',
 'TZ_0041_m12',
 'TZ_0420_m3',
 'TZ_1332_m3',
 'TZ_1783_m6',
 'TZ_0171_m18',
 'TZ_0045_m18',
 'TZ_1720_m12',
 'TZ_1215_m24',
 'TZ_0103_m24',
 'TZ_1866_m24',
 'TZ_1796_m18',
 'TZ_0095_w4',
 'TZ_0172_m3',
 'TZ_1327_m12',
 'TZ_1423_m24',
 'TZ_1573_m12',
 'TZ_0256_m24',
 'TZ_1261_m6',
 'TZ_1573_m24',
 'TZ_0008_m15',
 'TZ_0176_m3',
 'TZ_1196_m12',
 'TZ_0331_m5',
 'TZ_0292_m18',
 'TZ_0463_m24',
 'TZ_1909_m18',
 'TZ_1938_m12',
 'TZ_1645_m3',
 'TZ_0168_m2',
 'TZ_1929_m12',
 'TZ_1171_m3',
 'TZ_0055_m5',
 'TZ_0274_m2',
 'TZ_0143_m15',
 'TZ_0440_m5',
 'TZ_1623_m24',
 'TZ_0271_m12',
 'TZ_1375_m3',
 'TZ_1968_m18',
 'TZ_1746_m12',
 'TZ_1615_m3',
 'TZ_1861_m6',
 'TZ_1301_m3',
 'TZ_1937_m18',
 'TZ_1451_m1',
 'TZ_1907_m1',
 'TZ_0048_m6',
 'TZ_1843_m18',
 'TZ_0153_w3',
 'TZ_0289_m5',
 'TZ_1488_m24',
 'TZ_0461_m1',
 'TZ_0132_m3',
 'TZ_0160_m12',
 'TZ_0980_m6',
 'TZ_1429_m6',
 'TZ_0140_m3',
 'TZ_0277_m15',
 'TZ_0004_m24',
 'TZ_0400_m5',
 'TZ_0277_m18',
 'TZ_1272_m24',
 'TZ_1797_m18',
 'TZ_0019_m18',
 'TZ_1509_m3',
 'TZ_1424_m12',
 'TZ_1417_m6',
 'TZ_1521_m18',
 'TZ_0425_m10',
 'TZ_1329_m3',
 'TZ_0401_m11',
 'TZ_0164_m3',
 'TZ_0418_m3',
 'TZ_1226_m1',
 'TZ_0165_m5',
 'TZ_1418_m18',
 'TZ_1905_m1',
 'TZ_1381_m6',
 'TZ_1813_m3',
 'TZ_1769_m12',
 'TZ_1878_m24',
 'TZ_0141_m2',
 'TZ_1780_m3',
 'TZ_0359_m5',
 'TZ_0274_w4',
 'TZ_0040_m24',
 'TZ_1834_m24',
 'TZ_0061_m5',
 'TZ_0195_m24',
 'TZ_1941_m18',
 'TZ_0402_m11',
 'TZ_1641_m24',
 'TZ_1711_m6',
 'TZ_1326_m3',
 'TZ_1944_m6',
 'TZ_0032_m15',
 'TZ_0401_m12',
 'TZ_1456_m6',
 'TZ_0004_m15',
 'TZ_1515_m1',
 'TZ_1940_m24',
 'TZ_1375_m12',
 'TZ_1451_m3',
 'TZ_0076_w2',
 'TZ_1907_m6',
 'TZ_0324_m18',
 'TZ_0099_m12',
 'TZ_0375',
 'TZ_1380_m24',
 'TZ_1966_m12',
 'TZ_0324_m5',
 'TZ_1326_m18',
 'TZ_0180_m1',
 'TZ_1303_m1',
 'TZ_1648_m1',
 'TZ_1489_m24',
 'TZ_0249_m6',
 'TZ_1451_m24',
 'TZ_1687_m1',
 'TZ_1230_m12',
 'TZ_1356_m24',
 'TZ_0180_m4',
 'TZ_0103_m15',
 'TZ_0188_m9',
 'TZ_0224_m9',
 'TZ_0415_m1',
 'TZ_0210_m24',
 'TZ_0137_m6',
 'TZ_1655_m1',
 'TZ_0080_m24',
 'TZ_1207_m12',
 'TZ_1485_m6',
 'TZ_1395_m3',
 'TZ_0234_m4',
 'TZ_1615_m6',
 'TZ_0132_m9',
 'TZ_0404_m2',
 'TZ_1224_m1',
 'TZ_0461_m24',
 'TZ_1909_m6',
 'TZ_1777_m24',
 'TZ_0160_m9',
 'TZ_0230_m6',
 'TZ_1765_m18',
 'TZ_0015_m2',
 'TZ_0440_m11',
 'TZ_1700_m1',
 'TZ_1315_m12',
 'TZ_1898_m18',
 'TZ_0265_m4',
 'TZ_1714_m6',
 'TZ_1399_m12',
 'TZ_1581_m6',
 'TZ_0048_m4',
 'TZ_1128_m18',
 'TZ_1803_m24',
 'TZ_0440_m8',
 'TZ_0147_m24',
 'TZ_0024_m12',
 'TZ_1172_m6',
 'TZ_2017_T3_m6',
 'TZ_0330_m15',
 'TZ_0454_m12',
 'TZ_0015_m3',
 'TZ_1583_m18',
 'TZ_1591_m18',
 'TZ_0242_m18',
 'TZ_1257_m24',
 'TZ_1375_m24',
 'TZ_0276_m5',
 'TZ_0327_w4',
 'TZ_1269_m24',
 'TZ_1732_m3',
 'TZ_0156_w3',
 'TZ_0400_m12',
 'TZ_1297_m3',
 'TZ_1735_m3',
 'TZ_0241_m6',
 'TZ_1397_m12',
 ...]

In [32]:
pd.DataFrame({'var_names': fea_list}).to_csv(DATA_PATH + 'fea_list.csv')

In [15]:
fea_list = pd.read_csv(DATA_PATH + 'fea_list.csv')
fea_list = fea_list['var_names'].tolist()
fea_list

['TZ_1247_m18',
 'TZ_1812_m18',
 'TZ_0083_w4',
 'TZ_1640_m1',
 'TZ_1747_m24',
 'TZ_0272_m2',
 'TZ_0160_m5',
 'TZ_0005_m15',
 'TZ_0390_m8',
 'TZ_1220_m12',
 'TZ_1870_m24',
 'TZ_1752_m24',
 'TZ_0442_m4',
 'TZ_1711_m12',
 'TZ_0011_m2',
 'TZ_0143_m12',
 'TZ_2019_T3_m24',
 'TZ_0017_m24',
 'TZ_0063_m4',
 'TZ_1225_m3',
 'TZ_1512_m12',
 'TZ_0028_m18',
 'TZ_0338_m9',
 'TZ_0415_m5',
 'TZ_1731_m18',
 'TZ_1972_m18',
 'TZ_1702_m18',
 'TZ_0036_w4',
 'TZ_0033_m12',
 'TZ_0333_m6',
 'TZ_1896_m24',
 'TZ_1103',
 'TZ_0077_m6',
 'TZ_0087_m24',
 'TZ_1358_m6',
 'TZ_0032_w4',
 'TZ_1424_m24',
 'TZ_0141_m12',
 'TZ_0415_m12',
 'TZ_0273_m3',
 'TZ_1521_m1',
 'TZ_1420_m1',
 'TZ_0055_m24',
 'TZ_1144_m12',
 'TZ_0328_m4',
 'TZ_1318_m12',
 'TZ_0088_m9',
 'TZ_1643_m12',
 'TZ_0183_m2',
 'TZ_1772_m6',
 'TZ_1782_m24',
 'TZ_1904_m3',
 'TZ_0108_m18',
 'TZ_1347_m12',
 'TZ_1490_m24',
 'TZ_1544_m12',
 'TZ_0463_m12',
 'TZ_1222_m12',
 'TZ_1546_m12',
 'TZ_1620_m6',
 'TZ_0020_m12',
 'TZ_1672_m6',
 'TZ_0396_m10',
 'TZ_1875_m18',
 'TZ_1864_m24',
 'TZ_1903_m24',
 'TZ_0093_m24',
 'TZ_1331_m18',
 'TZ_0266_m12',
 'TZ_0396_m24',
 'TZ_1585_m24',
 'TZ_0044_m18',
 'TZ_0097_m24',
 'TZ_0177_m5',
 'TZ_1448_m12',
 'TZ_1809_m1',
 'TZ_0185_m2',
 'TZ_1861_m18',
 'TZ_1192_m24',
 'TZ_1396_m6',
 'TZ_0008_w4',
 'TZ_1745_m12',
 'TZ_0156_m24',
 'TZ_0152_m24',
 'TZ_0248_m6',
 'TZ_2019_T2_m9',
 'TZ_0059_m4',
 'TZ_0247_m9',
 'TZ_0420_m8',
 'TZ_1317_m12',
 'TZ_0282_m5',
 'TZ_0252_m18',
 'TZ_0175_m18',
 'TZ_0324_w4',
 'TZ_1450_m12',
 'TZ_0417_m7',
 'TZ_1549_m18',
 'TZ_0959_m6',
 'TZ_0164_m5',
 'TZ_1869_m3',
 'TZ_1137_m6',
 'TZ_0418_m7',
 'TZ_0392_m6',
 'TZ_1219_m3',
 'TZ_0441_m3',
 'TZ_1620_m18',
 'TZ_0037_m2',
 'TZ_1325_m12',
 'TZ_0394_m10',
 'TZ_1166_m6',
 'TZ_1462_m3',
 'TZ_0265_w2',
 'TZ_1156_m24',
 'TZ_0029_m2',
 'TZ_1488_m6',
 'TZ_1322_m3',
 'TZ_1874_m12',
 'TZ_0989',
 'TZ_0248_m4',
 'TZ_1336_m1',
 'TZ_1652_m3',
 'TZ_1905_m3',
 'TZ_1928_m24',
 'TZ_1421_m6',
 'TZ_1622_m12',
 'TZ_1934_m24',
 'TZ_0189_m15',
 'TZ_0441_m10',
 'TZ_1354_m24',
 'TZ_0272_m18',
 'TZ_0267_m18',
 'TZ_1719_m3',
 'TZ_1297_m12',
 'TZ_0357_m12',
 'TZ_1590_m3',
 'TZ_1572_m6',
 'TZ_1975_m12',
 'TZ_0267_w2',
 'TZ_0057_w2',
 'TZ_1351_m24',
 'TZ_1200_m6',
 'TZ_0250_m24',
 'TZ_0265_m15',
 'TZ_0179_m5',
 'TZ_1266_m6',
 'TZ_0465_m24',
 'TZ_1606_m6',
 'TZ_0112_m24',
 'TZ_0015_m15',
 'TZ_1271_m24',
 'TZ_1715_m18',
 'TZ_1931_m1',
 'TZ_1717_m3',
 'TZ_1656_m18',
 'TZ_1835_m12',
 'TZ_1718_m24',
 'TZ_1717_m1',
 'TZ_0979_m24',
 'TZ_1389_m1',
 'TZ_1492_m6',
 'TZ_1387_m24',
 'TZ_0356_m2',
 'TZ_1643_m6',
 'TZ_0988',
 'TZ_1165_m12',
 'TZ_1524_m24',
 'TZ_0177_m3',
 'TZ_0088_m6',
 'TZ_0227_m24',
 'TZ_0220_m5',
 'TZ_0291_m18',
 'TZ_1512_m18',
 'TZ_0968_m12',
 'TZ_0025_m12',
 'TZ_1897_m18',
 'TZ_0445_m12',
 'TZ_0184_m2',
 'TZ_1612_m3',
 'TZ_1706_m6',
 'TZ_1450_m6',
 'TZ_1175_m24',
 'TZ_1357_m18',
 'TZ_0390_m9',
 'TZ_0201_m9',
 'TZ_0083_m15',
 'TZ_0140_m2',
 'TZ_1812_m1',
 'TZ_1701_m18',
 'TZ_1000_w1_to_m1',
 'TZ_1559_m3',
 'TZ_0036_m9',
 'TZ_0464_m24',
 'TZ_0056_w3',
 'TZ_1880_m24',
 'TZ_1380_m3',
 'TZ_0271_m2',
 'TZ_1412_m18',
 'TZ_1552_m12',
 'TZ_0089_m9',
 'TZ_1806_m1',
 'TZ_1974_m12',
 'TZ_0394_m4',
 'TZ_0052_m3',
 'TZ_2017_T3_m15',
 'TZ_0357_m9',
 'TZ_0967_m24',
 'TZ_1364_m24',
 'TZ_0156_m9',
 'TZ_0010_m2',
 'TZ_0402_m7',
 'TZ_1743_m1',
 'TZ_0141_m5',
 'TZ_2019_T3_m4',
 'TZ_0200_m4',
 'TZ_0380_m18',
 'TZ_1319_m24',
 'TZ_0137_m2',
 'TZ_0027_m15',
 'TZ_1400_m24',
 'TZ_1523_m12',
 'TZ_0251_m9',
 'TZ_0292_m15',
 'TZ_0017_m18',
 'TZ_0326_w2',
 'TZ_1294_m24',
 'TZ_0059_m3',
 'TZ_0401_m3',
 'TZ_1238_m3',
 'TZ_1522_m1',
 'TZ_0188_m24',
 'TZ_1396_m18',
 'TZ_0268_m24',
 'TZ_0076_w3',
 'TZ_0422_m7',
 'TZ_0179_m4',
 'TZ_0117_m18',
 'TZ_0465_m12',
 'TZ_1164_m18',
 'TZ_1802_m3',
 'TZ_0173_m4',
 'TZ_1815_m18',
 'TZ_0172_m18',
 'TZ_1608_m3',
 'TZ_0138_m5',
 'TZ_1133_m18',
 'TZ_1323_m24',
 'TZ_1175_m1',
 'TZ_1553_m12',
 'TZ_0236_m5',
 'TZ_1736_m3',
 'TZ_0079_m9',
 'TZ_1960_m12',
 'TZ_0172_m4',
 'TZ_0019_m24',
 'TZ_0249_m3',
 'TZ_1424_m1',
 'TZ_1910_m3',
 'TZ_0282_m15',
 'TZ_0421_m4',
 'TZ_0139_w4',
 'TZ_0053_m5',
 'TZ_1910_m24',
 'TZ_1384_m12',
 'TZ_2019_T3_m15',
 'TZ_0032_m2',
 'TZ_0330_w2',
 'TZ_0371',
 'TZ_1163_m12',
 'TZ_1515_m12',
 'TZ_0077_m3',
 'TZ_1731_m12',
 'TZ_1139_m18',
 'TZ_1774_m12',
 'TZ_1508_m12',
 'TZ_1686_m3',
 'TZ_1019_w4',
 'TZ_1640_m12',
 'TZ_0273_m15',
 'TZ_1481_m3',
 'TZ_0148_m24',
 'TZ_1389_m12',
 'TZ_1419_m24',
 'TZ_0052_m24',
 'TZ_1235_m3',
 'TZ_0265_m18',
 'TZ_1801_m24',
 'TZ_1189_m24',
 'TZ_0039_m5',
 'TZ_1621_m3',
 'TZ_0153_m24',
 'TZ_0416_m11',
 'TZ_0035_m6',
 'TZ_1842_m6',
 'TZ_0155_w4',
 'TZ_1616_m3',
 'TZ_0961_m24',
 'TZ_1715_m24',
 'TZ_1161_m12',
 'TZ_0193_w4',
 'TZ_1809_m24',
 'TZ_1554_m1',
 'TZ_0009_m6',
 'TZ_1899_m18',
 'TZ_0244_m15',
 'TZ_0284_m12',
 'TZ_1965_m6',
 'TZ_0139_m4',
 'TZ_1904_m18',
 'TZ_0005_m5',
 'TZ_0088_m5',
 'TZ_1193_m24',
 'TZ_1685_m3',
 'TZ_1967_m24',
 'TZ_0167_m15',
 'TZ_1171_m6',
 'TZ_1291_m24',
 'TZ_1418_m12',
 'TZ_0325_m24',
 'TZ_1560_m1',
 'TZ_0238_m6',
 'TZ_1870_m3',
 'TZ_0220_m9',
 'TZ_1805_m24',
 'TZ_0008_m3',
 'TZ_0405_m12',
 'TZ_1380_m6',
 'TZ_0237_m9',
 'TZ_1720_m1',
 'TZ_0213_m18',
 'TZ_0155_w2',
 'TZ_0112_m9',
 'TZ_0288_m12',
 'TZ_1450_m24',
 'TZ_1284_m18',
 'TZ_1941_m6',
 'TZ_1978_m6',
 'TZ_1142_m18',
 'TZ_1699_m18',
 'TZ_0007_m9',
 'TZ_0280_m9',
 'TZ_0419_m9',
 'TZ_1527_m24',
 'TZ_1540_m6',
 'TZ_0326_m2',
 'TZ_0020_m15',
 'TZ_1456_m24',
 'TZ_1578_m3',
 'TZ_0442_m7',
 'TZ_1017_m6',
 'TZ_0998_m1_to_m12',
 'TZ_0152_m2',
 'TZ_0220_m6',
 'TZ_0279_m15',
 'TZ_1541_m6',
 'TZ_0325_m6',
 'TZ_1873_m18',
 'TZ_1423_m12',
 'TZ_0285_m15',
 'TZ_0218_m24',
 'TZ_0084_m4',
 'TZ_0324_m3',
 'TZ_0810_m10',
 'TZ_0132_m12',
 'TZ_1962_m12',
 'TZ_1170_m6',
 'TZ_1928_m12',
 'TZ_1265_m18',
 'TZ_1343_m6',
 'TZ_0241_m5',
 'TZ_0331_m2',
 'TZ_1251_m18',
 'TZ_1807_m1',
 'TZ_0444_m10',
 'TZ_0417_m12',
 'TZ_1161_m6',
 'TZ_1454_m18',
 'TZ_1802_m24',
 'TZ_1809_m6',
 'TZ_1266_m1',
 'TZ_1517_m12',
 'TZ_0267_m12',
 'TZ_1399_m18',
 'TZ_1930_m18',
 'TZ_1797_m3',
 'TZ_0265_m3',
 'TZ_1425_m3',
 'TZ_1254_m12',
 'TZ_1775_m6',
 'TZ_1367_m6',
 'TZ_1253_m18',
 'TZ_1577_m24',
 'TZ_1230_m18',
 'TZ_2019_T3_m18',
 'TZ_1676_m18',
 'TZ_1898_m6',
 'TZ_1352_m1',
 'TZ_1861_m12',
 'TZ_1431_m3',
 'TZ_0417_m5',
 'TZ_0267_m15',
 'TZ_1232_m1',
 'TZ_0138_m3',
 'TZ_1393_m24',
 'TZ_0441_m12',
 'TZ_1452_m3',
 'TZ_0237_m15',
 'TZ_0395_m4',
 'TZ_1385_m18',
 'TZ_1258_m12',
 'TZ_0325_m2',
 'TZ_1556_m3',
 'TZ_0226_m15',
 'TZ_0400_m11',
 'TZ_0444_m1',
 'TZ_0228_m6',
 'TZ_1349_m24',
 'TZ_1865_m6',
 'TZ_0165_m9',
 'TZ_0051_m4',
 'TZ_1738_m6',
 'TZ_0011_w3',
 'TZ_0001_m5',
 'TZ_1299_m3',
 'TZ_1239_m6',
 'TZ_1125_m6',
 'TZ_0419_m8',
 'TZ_0179_m18',
 'TZ_0172_w3',
 'TZ_1802_m18',
 'TZ_1840_m6',
 'TZ_0268_m12',
 'TZ_1901_m1',
 'TZ_2020_T4_m12',
 'TZ_0443_m9',
 'TZ_1390_m3',
 'TZ_0177_w3',
 'TZ_0085_m9',
 'TZ_1084_m24',
 'TZ_1974_m24',
 'TZ_1134_m24',
 'TZ_1300_m3',
 'TZ_1734_m12',
 'TZ_1267_m3',
 'TZ_1172_m1',
 'TZ_0332_m6',
 'TZ_0224_m6',
 'TZ_1942_m1',
 'TZ_0244_m24',
 'TZ_1527_m12',
 'TZ_1644_m12',
 'TZ_0167_w3',
 'TZ_0438_m9',
 'TZ_1839_m24',
 'TZ_2017_T2_m3',
 'TZ_1331_m24',
 'TZ_0390_m6',
 'TZ_1912_m24',
 'TZ_0037_m4',
 'TZ_0281_m18',
 'TZ_0279_m24',
 'TZ_1449_m24',
 'TZ_0057_m2',
 'TZ_1430_m3',
 'TZ_0183_m5',
 'TZ_0061_m15',
 'TZ_1232_m18',
 'TZ_0153_m6',
 'TZ_0041_m9',
 'TZ_1876_m24',
 'TZ_1329_m12',
 'TZ_0428_m8',
 'TZ_1549_m24',
 'TZ_1455_m18',
 'TZ_0059_w4',
 'TZ_1235_m6',
 'TZ_0156_m6',
 'TZ_0284_m18',
 'TZ_1610_m6',
 'TZ_1835_m3',
 'TZ_1908_m18',
 'TZ_1204_m18',
 'TZ_0176_m1',
 'TZ_0000_m5',
 'TZ_1336_m6',
 'TZ_1605_m3',
 'TZ_0390_m24',
 'TZ_0179_w3',
 'TZ_1624_m12',
 'TZ_1490_m6',
 'TZ_0241_m18',
 'TZ_1579_m24',
 'TZ_0428_m7',
 'TZ_0267_m24',
 'TZ_0355_m2',
 'TZ_1197_m3',
 'TZ_0329_w4',
 'TZ_1549_m6',
 'TZ_0075_w4',
 'TZ_0289_m9',
 'TZ_1614_m12',
 'TZ_0161_m15',
 'TZ_0404_m6',
 'TZ_1586_m24',
 'TZ_1253_m3',
 'TZ_0452_m12',
 'TZ_1160_m18',
 'TZ_0404_m11',
 'TZ_0440_m2',
 'TZ_0502_m24',
 'TZ_0132_w4',
 'TZ_0305_m9',
 'TZ_0093_m2',
 'TZ_0073_m18',
 'TZ_1140_m18',
 'TZ_1169_m3',
 'TZ_1637_m12',
 'TZ_0203_m24',
 'TZ_0212_m15',
 'TZ_1685_m6',
 'TZ_1727_m1',
 'TZ_1842_m3',
 'TZ_0281_m5',
 'TZ_1203_m12',
 'TZ_0425_m11',
 'TZ_0963_m6',
 'TZ_0176_m24',
 'TZ_1524_m18',
 'TZ_0116_m5',
 'TZ_1905_m6',
 'TZ_0210_m15',
 'TZ_1398_m6',
 'TZ_0234_m6',
 'TZ_0201_m2',
 'TZ_0268_m9',
 'TZ_1589_m18',
 'TZ_0965_m12',
 'TZ_1362_m6',
 'TZ_0961_m6',
 'TZ_1192_m6',
 'TZ_0281_m24',
 'TZ_0155_m24',
 'TZ_0192_m24',
 'TZ_0165_m12',
 'TZ_0041_m3',
 'TZ_0080_m18',
 'TZ_0196_w4',
 'TZ_1542_m24',
 'TZ_0224_m4',
 'TZ_0015_w4',
 'TZ_1296_m24',
 'TZ_0995_m6_to_m12',
 'TZ_0037_w4',
 'TZ_0155_m12',
 'TZ_1317_m24',
 'TZ_1743_m6',
 'TZ_0210_m18',
 'TZ_0180_w3',
 'TZ_0136_m18',
 'TZ_1552_m1',
 'TZ_1944_m18',
 'TZ_0331_m4',
 'TZ_1460_m6',
 'TZ_0096_m5',
 'TZ_0202_m24',
 'TZ_0338_m12',
 'TZ_0390_m12',
 'TZ_1966_m18',
 'TZ_0963_m24',
 'TZ_0355_m6',
 'TZ_1193_m12',
 'TZ_1709_m3',
 'TZ_1221_m3',
 'TZ_1294_m3',
 'TZ_1135_m1',
 'TZ_0402_m6',
 'TZ_0076_m12',
 'TZ_0200_m9',
 'TZ_1361_m6',
 'TZ_0285_m6',
 'TZ_0418_m5',
 'TZ_1574_m3',
 'TZ_0159_w4',
 'TZ_1617_m24',
 'TZ_1162_m6',
 'TZ_1136_m18',
 'TZ_1707_m12',
 'TZ_0404_m10',
 'TZ_0421_m5',
 'TZ_0015_m9',
 'TZ_0460_m12',
 'TZ_1494_m3',
 'TZ_0359_m24',
 'TZ_1624_m3',
 'TZ_1685_m1',
 'TZ_0265_w4',
 'TZ_1838_m12',
 'TZ_0143_m6',
 'TZ_1638_m18',
 'TZ_0442_m8',
 'TZ_0456_m6',
 'TZ_1388_m24',
 'TZ_1804_m12',
 'TZ_1900_m18',
 'TZ_1604_m12',
 'TZ_0250_m5',
 'TZ_1200_m3',
 'TZ_1523_m1',
 'TZ_0045_m15',
 'TZ_0077_w3',
 'TZ_1420_m18',
 'TZ_1011_m1_to_m2',
 'TZ_1262_m6',
 'TZ_1865_m18',
 'TZ_0155_m18',
 'TZ_1221_m6',
 'TZ_0093_m15',
 'TZ_1237_m24',
 'TZ_0423_m6',
 'TZ_1302_m1',
 'TZ_1359_m24',
 'TZ_0399_m11',
 'TZ_0217_m15',
 'TZ_1709_m1',
 'TZ_1781_m12',
 'TZ_0286_m15',
 'TZ_0966_m6',
 'TZ_0147_m12',
 'TZ_0356_m24',
 'TZ_0241_m12',
 'TZ_0171_m15',
 'TZ_0095_m18',
 'TZ_1943_m6',
 'TZ_1707_m6',
 'TZ_0390_m5',
 'TZ_1237_m6',
 'TZ_1330_m6',
 'TZ_0009_m12',
 'TZ_0092_m15',
 'TZ_1357_m12',
 'TZ_1288_m12',
 'TZ_0398_m3',
 'TZ_1586_m3',
 'TZ_1452_m12',
 'TZ_0077_m12',
 'TZ_1448_m6',
 'TZ_0423_m9',
 'TZ_1585_m18',
 'TZ_1515_m3',
 'TZ_0292_m12',
 'TZ_0422_m5',
 'TZ_1220_m18',
 'TZ_0272_m24',
 'TZ_0075_m12',
 'TZ_1221_m24',
 'TZ_1586_m12',
 'TZ_1219_m24',
 'TZ_1389_m24',
 'TZ_1611_m3',
 'TZ_1981_m3',
 'TZ_1226_m6',
 'TZ_2019_T4_m4',
 'TZ_1801_m18',
 'TZ_0160_m4',
 'TZ_1688_m24',
 'TZ_0214_m24',
 'TZ_0960_m24',
 'TZ_1805_m6',
 'TZ_1163_m6',
 'TZ_0196_m18',
 'TZ_0041_m24',
 'TZ_0047_m15',
 'TZ_1902_m12',
 'TZ_0253_m18',
 'TZ_0404_m7',
 'TZ_1688_m6',
 'TZ_0282_m9',
 'TZ_1984_m18',
 'TZ_0338_m15',
 'TZ_1802_m6',
 'TZ_1457_m24',
 'TZ_1240_m24',
 'TZ_1143_m6',
 'TZ_0185_m24',
 'TZ_0078_m4',
 'TZ_1254_m6',
 'TZ_1545_m18',
 'TZ_1587_m12',
 'TZ_0079_m4',
 'TZ_0167_m5',
 'TZ_1390_m6',
 'TZ_1394_m1',
 'TZ_1556_m1',
 'TZ_1770_m18',
 'TZ_1194_m3',
 'TZ_0416_m12',
 'TZ_0444_m6',
 'TZ_0274_m6',
 'TZ_0099_m6',
 'TZ_0053_m6',
 'TZ_0277_m4',
 'TZ_0177_m12',
 'TZ_1735_m24',
 'TZ_1262_m1',
 'TZ_0132_m2',
 'TZ_1128_m1',
 'TZ_0230_m12',
 'TZ_1944_m24',
 'TZ_1840_m18',
 'TZ_0382_m24',
 'TZ_1489_m12',
 'TZ_0224_m3',
 'TZ_1778_m3',
 'TZ_0294_m15',
 'TZ_0444_m2',
 'TZ_0274_w3',
 'TZ_1237_m1',
 'TZ_0249_m2',
 'TZ_1813_m12',
 'TZ_0007_m12',
 'TZ_0267_w3',
 'TZ_0269_m15',
 'TZ_1640_m18',
 'TZ_0077_m9',
 'TZ_0278_m5',
 'TZ_0187_m12',
 'TZ_0137_m18',
 'TZ_0177_w4',
 'TZ_1929_m3',
 'TZ_0210_m9',
 'TZ_1517_m1',
 'TZ_1781_m6',
 'TZ_0047_m6',
 'TZ_1835_m18',
 'TZ_0169_m4',
 'TZ_1226_m24',
 'TZ_1816_m6',
 'TZ_1353_m24',
 'TZ_0196_w2',
 'TZ_0264_w4',
 'TZ_1804_m3',
 'TZ_0008_w3',
 'TZ_0394_m5',
 'TZ_0157_m6',
 'TZ_1901_m6',
 'TZ_1924_m6',
 'TZ_0461_m6',
 'TZ_1984_m3',
 'TZ_1227_m6',
 'TZ_0454_m24',
 'TZ_1131_m3',
 'TZ_1843_m3',
 'TZ_0236_m12',
 'TZ_1368_m18',
 'TZ_1843_m6',
 'TZ_1202_m18',
 'TZ_1669_m18',
 'TZ_2019_T4_m12',
 'TZ_1257_m6',
 'TZ_1239_m24',
 'TZ_1329_m24',
 'TZ_0019_m15',
 'TZ_1425_m18',
 'TZ_1220_m6',
 'TZ_0425_m24',
 'TZ_1483_m18',
 'TZ_1232_m12',
 'TZ_1482_m12',
 'TZ_1526_m3',
 'TZ_1422_m1',
 'TZ_1975_m6',
 'TZ_1169_m1',
 'TZ_1139_m6',
 'TZ_1336_m12',
 'TZ_0247_m4',
 'TZ_0439_m8',
 'TZ_1357_m1',
 'TZ_1163_m24',
 'TZ_2017_T3_m9',
 'TZ_1397_m3',
 'TZ_2017_T3_m5',
 'TZ_0415_m10',
 'TZ_0055_m3',
 'TZ_0193_m15',
 'TZ_0405_m24',
 'TZ_2016_T4_m15',
 'TZ_0394_m7',
 'TZ_0027_m24',
 'TZ_1427_m6',
 'TZ_0274_m4',
 'TZ_0060_m9',
 'TZ_0199_m6',
 'TZ_1156_m6',
 'TZ_1264_m3',
 'TZ_0176_m2',
 'TZ_0004_m18',
 'TZ_1189_m12',
 'TZ_1713_m12',
 'TZ_1751_m6',
 'TZ_1363_m18',
 'TZ_1254_m18',
 'TZ_0415_m6',
 'TZ_1270_m1',
 'TZ_1367_m12',
 'TZ_1509_m18',
 'TZ_0100_m15',
 'TZ_0037_m5',
 'TZ_0403_m8',
 'TZ_0438_m12',
 'TZ_1461_m1',
 'TZ_1808_m24',
 'TZ_0253_m9',
 'TZ_0424_m8',
 'TZ_0155_w3',
 'TZ_1640_m24',
 'TZ_0059_m2',
 'TZ_0224_m15',
 'TZ_1622_m24',
 'TZ_0384_m18',
 'TZ_0078_m9',
 'TZ_1797_m1',
 'TZ_0253_m6',
 'TZ_0041_m12',
 'TZ_0420_m3',
 'TZ_1332_m3',
 'TZ_1783_m6',
 'TZ_0171_m18',
 'TZ_0045_m18',
 'TZ_1720_m12',
 'TZ_1215_m24',
 'TZ_0103_m24',
 'TZ_1866_m24',
 'TZ_1796_m18',
 'TZ_0095_w4',
 'TZ_0172_m3',
 'TZ_1327_m12',
 'TZ_1423_m24',
 'TZ_1573_m12',
 'TZ_0256_m24',
 'TZ_1261_m6',
 'TZ_1573_m24',
 'TZ_0008_m15',
 'TZ_0176_m3',
 'TZ_1196_m12',
 'TZ_0331_m5',
 'TZ_0292_m18',
 'TZ_0463_m24',
 'TZ_1909_m18',
 'TZ_1938_m12',
 'TZ_1645_m3',
 'TZ_0168_m2',
 'TZ_1929_m12',
 'TZ_1171_m3',
 'TZ_0055_m5',
 'TZ_0274_m2',
 'TZ_0143_m15',
 'TZ_0440_m5',
 'TZ_1623_m24',
 'TZ_0271_m12',
 'TZ_1375_m3',
 'TZ_1968_m18',
 'TZ_1746_m12',
 'TZ_1615_m3',
 'TZ_1861_m6',
 'TZ_1301_m3',
 'TZ_1937_m18',
 'TZ_1451_m1',
 'TZ_1907_m1',
 'TZ_0048_m6',
 'TZ_1843_m18',
 'TZ_0153_w3',
 'TZ_0289_m5',
 'TZ_1488_m24',
 'TZ_0461_m1',
 'TZ_0132_m3',
 'TZ_0160_m12',
 'TZ_0980_m6',
 'TZ_1429_m6',
 'TZ_0140_m3',
 'TZ_0277_m15',
 'TZ_0004_m24',
 'TZ_0400_m5',
 'TZ_0277_m18',
 'TZ_1272_m24',
 'TZ_1797_m18',
 'TZ_0019_m18',
 'TZ_1509_m3',
 'TZ_1424_m12',
 'TZ_1417_m6',
 'TZ_1521_m18',
 'TZ_0425_m10',
 'TZ_1329_m3',
 'TZ_0401_m11',
 'TZ_0164_m3',
 'TZ_0418_m3',
 'TZ_1226_m1',
 'TZ_0165_m5',
 'TZ_1418_m18',
 'TZ_1905_m1',
 'TZ_1381_m6',
 'TZ_1813_m3',
 'TZ_1769_m12',
 'TZ_1878_m24',
 'TZ_0141_m2',
 'TZ_1780_m3',
 'TZ_0359_m5',
 'TZ_0274_w4',
 'TZ_0040_m24',
 'TZ_1834_m24',
 'TZ_0061_m5',
 'TZ_0195_m24',
 'TZ_1941_m18',
 'TZ_0402_m11',
 'TZ_1641_m24',
 'TZ_1711_m6',
 'TZ_1326_m3',
 'TZ_1944_m6',
 'TZ_0032_m15',
 'TZ_0401_m12',
 'TZ_1456_m6',
 'TZ_0004_m15',
 'TZ_1515_m1',
 'TZ_1940_m24',
 'TZ_1375_m12',
 'TZ_1451_m3',
 'TZ_0076_w2',
 'TZ_1907_m6',
 'TZ_0324_m18',
 'TZ_0099_m12',
 'TZ_0375',
 'TZ_1380_m24',
 'TZ_1966_m12',
 'TZ_0324_m5',
 'TZ_1326_m18',
 'TZ_0180_m1',
 'TZ_1303_m1',
 'TZ_1648_m1',
 'TZ_1489_m24',
 'TZ_0249_m6',
 'TZ_1451_m24',
 'TZ_1687_m1',
 'TZ_1230_m12',
 'TZ_1356_m24',
 'TZ_0180_m4',
 'TZ_0103_m15',
 'TZ_0188_m9',
 'TZ_0224_m9',
 'TZ_0415_m1',
 'TZ_0210_m24',
 'TZ_0137_m6',
 'TZ_1655_m1',
 'TZ_0080_m24',
 'TZ_1207_m12',
 'TZ_1485_m6',
 'TZ_1395_m3',
 'TZ_0234_m4',
 'TZ_1615_m6',
 'TZ_0132_m9',
 'TZ_0404_m2',
 'TZ_1224_m1',
 'TZ_0461_m24',
 'TZ_1909_m6',
 'TZ_1777_m24',
 'TZ_0160_m9',
 'TZ_0230_m6',
 'TZ_1765_m18',
 'TZ_0015_m2',
 'TZ_0440_m11',
 'TZ_1700_m1',
 'TZ_1315_m12',
 'TZ_1898_m18',
 'TZ_0265_m4',
 'TZ_1714_m6',
 'TZ_1399_m12',
 'TZ_1581_m6',
 'TZ_0048_m4',
 'TZ_1128_m18',
 'TZ_1803_m24',
 'TZ_0440_m8',
 'TZ_0147_m24',
 'TZ_0024_m12',
 'TZ_1172_m6',
 'TZ_2017_T3_m6',
 'TZ_0330_m15',
 'TZ_0454_m12',
 'TZ_0015_m3',
 'TZ_1583_m18',
 'TZ_1591_m18',
 'TZ_0242_m18',
 'TZ_1257_m24',
 'TZ_1375_m24',
 'TZ_0276_m5',
 'TZ_0327_w4',
 'TZ_1269_m24',
 'TZ_1732_m3',
 'TZ_0156_w3',
 'TZ_0400_m12',
 'TZ_1297_m3',
 'TZ_1735_m3',
 'TZ_0241_m6',
 'TZ_1397_m12',
 ...]

In [16]:
len(fea_list)

6220

## 4 label process

In [17]:
import gc
gc.collect()

0

In [18]:
label = pd.read_csv(DATA_OR_PATH + 'wxjk_data.csv')

In [19]:
label.head()

,id_no_md5,id_no_sha256,mobile_md5,mobile_sha256,name_md5,name_sha256,auth_time,devflag,t10,mob2m2,mob4m2,mob7m2,ever_m2,train_or_test,weight,if_app,cust_type
0,8b3a71e6517de7391e5f2fc1f20eb778,0cda4b6dc3689892b6dd352682ab992f1133e352da5b67...,6afc7f594e81633d58bf091562d0ae43,825cff373793a29d4b54a5b79ffd675e7bfa3f9994e17a...,729599939935314ad7796963a4ac81f4,285914ed0f7dfffcd51e4932bf3c0efea0d30ba037947d...,2025-01-22 13:31:51,新贷,0,0,0,0,0,train,2.399906,NaN,0
1,58d6eedcf45eebfed22b506a03e8feb7,d230035d3290ec890f65b7e4799ae0fcc18a5c4736823b...,02947e5fb54d2203bf03f2a13f13d92e,6f4cafd6770dcc2541bf465b1bf96484a97f919732c8ed...,d74b62337c90fb492cf1d27a35500e79,35949913a1731771be314e4f962ee3d29f6125a5c1d42b...,2025-09-20 11:24:34,缓存测试,-1,-1,-1,-1,-1,NaN,1.000000,NaN,0
2,d3f71f697b5f0a8cbde4772e7bb18f06,b6b019e7109962bf72047627c996e1f88c0ccda5fa52fe...,642f657575362a912b6ce80606b79cf9,54e5b2dae4064667605de2629fc16aa3bfefcd8ddc59ed...,0deee47fffaa56cab2b085c3b173d2eb,a63f7347fcae08bf743cf765655ba9dd3c561b5a729ef5...,2024-11-29 21:15:36,新贷,0,0,0,0,0,test,2.399906,NaN,0
3,8f5161712dc8c618598ad4ec0632036a,07d75636e2960ed5ceed4fd27c5de4d127dd2f73d48a0b...,71d234b2a1b0ee10fb36229d8575f6c9,8c2099a4ffb5950eb5fe1cad3dcfc4f9cfba1b9a7ef778...,8dd18d524f30529d8f0910dbd2d015af,676bc534e5cef03794ac310b12d4f0e77f1dfb92c834a3...,2024-12-26 07:31:29,新贷,0,0,0,0,0,test,2.399906,NaN,0
4,98cfd4e53010fcede77dcde9bd7787be,05590f96fbf327fe2dfda4ffb55274ee39f75d9d5e2165...,eb2d382e9f02be6e4d24498d324a64d1,831c5d53539eeadc6f06acf271b59318efe5c8bfccb1bf...,2ecc12f6df07e5d0b982592df0c0924f,60497f66353f01dd2bd1eee45b381958c0912534171f76...,2024-10-22 09:27:24,新贷,0,0,0,0,0,test,2.399906,NaN,0

In [20]:
label = label[['mobile_md5','auth_time','mob4m2','devflag','weight','if_app']]
label.rename(columns={'mobile_md5':'mobile','auth_time':'backPointTime','mob4m2':'label'},inplace=True)
label['backPointTime'] = pd.to_datetime(label['backPointTime']).dt.strftime('%Y-%m-%d')

In [21]:
label['new_flag'] = label.apply(lambda x: x['devflag']+'_'+str(int(x['if_app'])) if x['if_app'] == 1 or x['if_app'] == 0 else x['devflag'], axis=1)

In [22]:
label['new_flag'].value_counts()

新贷         244144
复贷_1       226015
复贷_0       103905
新贷基测        73029
复贷基测        69127
评分进件-复贷      3200
评分进件-新贷      3200
缓存测试          918
回溯测试          500
Name: new_flag, dtype: int64

In [23]:
label = label[label['new_flag'].isin(['新贷', '复贷_1', '复贷_0','新贷基测','复贷基测'])]

In [24]:
label.drop(['if_app'], axis=1, inplace=True)

In [25]:
label.head()

,mobile,backPointTime,label,devflag,weight,new_flag
0,6afc7f594e81633d58bf091562d0ae43,2025-01-22,0,新贷,2.399906,新贷
2,642f657575362a912b6ce80606b79cf9,2024-11-29,0,新贷,2.399906,新贷
3,71d234b2a1b0ee10fb36229d8575f6c9,2024-12-26,0,新贷,2.399906,新贷
4,eb2d382e9f02be6e4d24498d324a64d1,2024-10-22,0,新贷,2.399906,新贷
5,e671a7d592ac58d7f44710b3902f2acd,2024-10-17,0,新贷,1.000000,新贷

## 5 label merge

In [31]:
from new_tools.reduce_mem_usage import reduce_mem_usage_dic 

def chunk_reduce_mem_usage(file_name,columns):
    chunks = pd.read_csv(file_name, usecols=columns, chunksize=200_000)
    chunk_list = []
    for chunk in chunks:
        chunk_reduce_mem = reduce_mem_usage_dic(chunk)
        del chunk
        chunk_list.append(chunk_reduce_mem)
        del chunk_reduce_mem
    df = pd.concat(chunk_list)
    return df

In [32]:
object_columns

[]

In [33]:
gc.collect()

0

In [ ]:
import polars as pl
from new_tools.reduce_mem_usage import reduce_mem_usage_dic

processed_chunks = []
label_index_lst = (label['mobile'] + label['backPointTime']).to_list()
label_tmp = label.copy()

use_cols = ['mobile', 'backPointTime'] + fea_list + object_columns

# 惰性扫描，不实际加载数据（不指定列）
lazy_df = pl.scan_parquet(parquet_zip_path).select(use_cols)

# 获取总行数（这个会执行一次快速扫描）
total_rows = lazy_df.select(pl.count()).collect().item()
print(f"总行数: {total_rows}")

batch_size = 100_000
i = 1

# 使用 slice 分批获取数据
for offset in range(0, total_rows, batch_size):
    # 惰性切片 + collect 只加载当前批次
    chunk = lazy_df.slice(offset, batch_size).collect().to_pandas()
    
    if len(chunk) == 0:
        continue
        
    temp_df = reduce_mem_usage_dic(chunk)
    del chunk
    gc.collect()
    
    temp_df.drop_duplicates(['mobile', 'backPointTime'], inplace=True)
    print(f"Chunk {i}: 去重后 {len(temp_df)} 行")
    
    temp_df['backPointTime'] = pd.to_datetime(temp_df['backPointTime']).dt.strftime('%Y-%m-%d')            
    temp_df = pd.merge(label_tmp, temp_df, how='inner', on=['mobile', 'backPointTime'])
    
    remove_set = set((temp_df['mobile'] + temp_df['backPointTime']).to_list())
    label_index_lst = list(set(label_index_lst) - remove_set)
    label_tmp = label[(label['mobile'] + label['backPointTime'].astype(str)).isin(label_index_lst)]
    
    temp_df.to_parquet(DATA_PATH + f'chunk_{i}.parquet')
    processed_chunks.append(temp_df)
    print(f"Chunk {i}: 保存完成, 剩余未匹配: {len(label_index_lst)}")
    
    del temp_df, remove_set
    gc.collect()
    i += 1

# 处理 mobile 为空的记录
mobile_num_df = label[pd.isna(label['mobile'])]
mobile_num_df[fea_list] = np.nan
processed_chunks.append(mobile_num_df)

print(f"最终未匹配数量: {len(label_index_lst)}")

总行数: 724038
当前内存占用: 2374.27 MB

100%|██████████| 6222/6222 [00:03<00:00, 1595.08it/s]

最终内存占用: 2374.27 MB
下降了 0.0%
Chunk 1: 去重后 99990 行
Chunk 1: 保存完成, 剩余未匹配: 617195
当前内存占用: 2374.27 MB

100%|██████████| 6222/6222 [00:05<00:00, 1172.38it/s]

最终内存占用: 2374.27 MB
下降了 0.0%
Chunk 2: 去重后 99981 行
Chunk 2: 保存完成, 剩余未匹配: 518222
当前内存占用: 2374.27 MB

100%|██████████| 6222/6222 [00:05<00:00, 1129.38it/s]

最终内存占用: 2374.27 MB
下降了 0.0%
Chunk 3: 去重后 99983 行
Chunk 3: 保存完成, 剩余未匹配: 419322
当前内存占用: 2374.27 MB

100%|██████████| 6222/6222 [00:04<00:00, 1503.70it/s]

最终内存占用: 2374.27 MB
下降了 0.0%
Chunk 4: 去重后 99983 行
Chunk 4: 保存完成, 剩余未匹配: 320435
当前内存占用: 2374.27 MB

100%|██████████| 6222/6222 [00:05<00:00, 1219.56it/s]

最终内存占用: 2374.27 MB
下降了 0.0%
Chunk 5: 去重后 99997 行
Chunk 5: 保存完成, 剩余未匹配: 221467
当前内存占用: 2374.27 MB

100%|██████████| 6222/6222 [00:05<00:00, 1189.02it/s]

最终内存占用: 2374.27 MB
下降了 0.0%
Chunk 6: 去重后 99990 行
Chunk 6: 保存完成, 剩余未匹配: 122642
当前内存占用: 2374.27 MB

100%|██████████| 6222/6222 [00:04<00:00, 1453.05it/s]

最终内存占用: 2374.27 MB
下降了 0.0%
Chunk 7: 去重后 99989 行
Chunk 7: 保存完成, 剩余未匹配: 23759
当前内存占用: 570.73 MB

100%|██████████| 6222/6222 [00:02<00:00, 2355.81it/s]

最终内存占用: 570.73 MB
下降了 0.0%
Chunk 8: 去重后 24037 行
Chunk 8: 保存完成, 剩余未匹配: 0
最终未匹配数量: 0

In [36]:
# from new_tools.reduce_mem_usage import reduce_mem_usage_dic

# processed_chunks = []
# label_index_lst = (label['mobile'] + label['backPointTime']).to_list()
# label_tmp = label.copy()

# with zipfile.ZipFile(DATA_OR_PATH + '信飞20251023_d1_t2_z2_deltaV1_result.zip', 'r') as zip_file:
#     file_list = zip_file.namelist()
#     csv_filename = [f for f in file_list if f.endswith('.txt') or f.endswith('.csv')][0]
    
#     with zip_file.open(csv_filename) as csv_file:
#         chunks = pd.read_csv(csv_file, usecols=['mobile','backPointTime'] + fea_list + object_columns, chunksize=200_000)
#         i = 1
#         for chunk in chunks:  # 在 with 块内完成迭代
#             temp_df = reduce_mem_usage_dic(chunk)
#             temp_df.drop_duplicates(['mobile', 'backPointTime'], inplace=True)
#             print(1)
#             temp_df['backPointTime'] = pd.to_datetime(temp_df['backPointTime']).dt.strftime('%Y-%m-%d')            
#             print(2)
#             temp_df = pd.merge(label_tmp, temp_df, how='inner', on=['mobile', 'backPointTime'])
#             print(3)
#             remove_set = set((temp_df['mobile'] + temp_df['backPointTime']).to_list())
#             label_index_lst = list(set(label_index_lst) - remove_set)
#             label_tmp = label[(label['mobile'] + label['backPointTime'].astype(str)).isin(label_index_lst)]
#             print(4)
#             # processed_chunks.append(temp_df)
#             temp_df.to_parquet(DATA_PATH + f'chunk_{i}.parquet')
#             print(5)
#             del chunk, temp_df, remove_set
#             gc.collect()
#             i = i+1
#         mobile_num_df = label[pd.isna(label['mobile'])]  # 或者根据实际逻辑调整
#         mobile_num_df[fea_list] = np.nan
#         # processed_chunks.append(mobile_num_df)

# print(len(label_index_lst))

In [ ]:
label_index_lst

[]

In [27]:
gc.collect()

0

In [26]:
from new_tools.parquet_utils import concat_parquet_streaming

files = [DATA_PATH + f"chunk_{i}.parquet" for i in range(1,9)]
# print(files)
concat_parquet_streaming(
    files,
    output_path=DATA_OR_PATH + f"{data}_data_all1.parquet",
    batch_size=50_000,     # 可按内存调小
    mem_threshold_gb=8.0,  # 建议设为物理内存的30%~50%
    columns_consistent=True  # 如果所有文件的列都一致，设为True以提速
)

正在处理文件 1/8: D:/work/06.std_product/wxjk_test/delta/data/chunk_1.parquet
正在处理文件 2/8: D:/work/06.std_product/wxjk_test/delta/data/chunk_2.parquet
正在处理文件 3/8: D:/work/06.std_product/wxjk_test/delta/data/chunk_3.parquet
正在处理文件 4/8: D:/work/06.std_product/wxjk_test/delta/data/chunk_4.parquet
正在处理文件 5/8: D:/work/06.std_product/wxjk_test/delta/data/chunk_5.parquet
正在处理文件 6/8: D:/work/06.std_product/wxjk_test/delta/data/chunk_6.parquet
正在处理文件 7/8: D:/work/06.std_product/wxjk_test/delta/data/chunk_7.parquet
正在处理文件 8/8: D:/work/06.std_product/wxjk_test/delta/data/chunk_8.parquet

In [30]:
data_all1 = pd.read_parquet(DATA_OR_PATH + f"{data}_data_all1.parquet")

:

:

In [ ]:
data_all1 = pd.concat(processed_chunks, ignore_index=True)
del processed_chunks
gc.collect()

In [ ]:
data_all1.shape

NameError: name 'data_all1' is not defined

In [25]:
data_all1.head()

,ms_no,mobile_sha256,hs_date,prod_flag,sample_type,target1_mi,target2_mi,stage,TZ_0000_m1,TZ_0000_m12,...,TZ_0073_m2,TZ_0073_m24,TZ_0073_m3,TZ_0073_m4,TZ_0073_m5,TZ_0073_m6,TZ_0073_m9,TZ_0073_w2,TZ_0073_w3,TZ_0073_w4
0,2618468494244577696,d45735e2015b20c4e8f95645096ae0dac3c9924b9e6b35...,2024-11-21,S,CA,0.0,0.0,test,0.0,0.0,...,0.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0
1,2626479791808743072,dff94df987f14dd7304d25f291729f0b4926adad0df39b...,2024-12-02,S,CA,0.0,0.0,test,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2582720644667933856,4d4d2304e9265b029491e1fec60e7431d55285fcad426e...,2024-10-03,S,CA,0.0,0.0,train,0.0,8.0,...,0.0,3.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0
3,2597987997622206880,f05c3b1367d78a5da0b060110d8724e72664c86dc456a4...,2024-10-24,S,CA,0.0,0.0,train,0.0,4.0,...,3.0,3.0,3.0,3.0,3.0,3.0,3.0,0.0,0.0,1.0
4,2654564558907114656,d92c8174bf3dd98aa5d11edefef13f24512c53b694071d...,2025-01-10,S,CA,0.0,NaN,test,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [26]:
data_all1['ms_no'] = data_all1['ms_no'].astype('str')

In [27]:
data_all1.to_parquet(DATA_PATH + 'data_all1.parquet')

In [28]:
# data_all1 = pd.read_parquet(DATA_PATH + 'data_all1.parquet')

In [29]:
# data_all1[object_columns] = data_all1[object_columns].apply(
#     lambda x: x.astype('category').cat.codes.replace({-1: np.nan}).astype('float64')
# )

In [30]:
data_all1[object_columns]

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]

[2000578 rows x 0 columns]

In [31]:
# data_all1[object_columns].count()

In [32]:
data_all1[data_all1['sample_type'] == 'CA'].to_parquet(DATA_PATH + 'data_all1_CA.parquet')

In [33]:
gc.collect()

0

In [34]:
data_all1[data_all1['sample_type'] == 'CR'].to_parquet(DATA_PATH + 'data_all1_CR.parquet')

In [35]:
%reset -f